/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type DeleteApiAuth200 = any;

export type DeleteApiAuthMutationResponse = DeleteApiAuth200;

export type DeleteApiAuthMutation = {
  Response: DeleteApiAuth200;
  PathParams: DeleteApiAuthPathParams;
  Errors: any;
};
