/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type GetApiAuth200 = any;

export type GetApiAuthQueryResponse = GetApiAuth200;

export type GetApiAuthQuery = {
  Response: GetApiAuth200;
  PathParams: GetApiAuthPathParams;
  Errors: any;
};
