/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type HeadApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type HeadApiAuth200 = any;

export type HeadApiAuthMutationResponse = HeadApiAuth200;

export type HeadApiAuthMutation = {
  Response: HeadApiAuth200;
  PathParams: HeadApiAuthPathParams;
  Errors: any;
};
