/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type OptionsApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type OptionsApiAuth200 = any;

export type OptionsApiAuthMutationResponse = OptionsApiAuth200;

export type OptionsApiAuthMutation = {
  Response: OptionsApiAuth200;
  PathParams: OptionsApiAuthPathParams;
  Errors: any;
};
