/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type PatchApiAuth200 = any;

export type PatchApiAuthMutationResponse = PatchApiAuth200;

export type PatchApiAuthMutation = {
  Response: PatchApiAuth200;
  PathParams: PatchApiAuthPathParams;
  Errors: any;
};
