/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type PostApiAuth200 = any;

export type PostApiAuthMutationResponse = PostApiAuth200;

export type PostApiAuthMutation = {
  Response: PostApiAuth200;
  PathParams: PostApiAuthPathParams;
  Errors: any;
};
