/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type PutApiAuth200 = any;

export type PutApiAuthMutationResponse = PutApiAuth200;

export type PutApiAuthMutation = {
  Response: PutApiAuth200;
  PathParams: PutApiAuthPathParams;
  Errors: any;
};
