/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TraceApiAuthPathParams = {
  /**
   * @type string
   */
  "*": string;
};

/**
 * @description Default Response
 */
export type TraceApiAuth200 = any;

export type TraceApiAuthMutationResponse = TraceApiAuth200;

export type TraceApiAuthMutation = {
  Response: TraceApiAuth200;
  PathParams: TraceApiAuthPathParams;
  Errors: any;
};
