/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteBrandsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

export type DeleteBrandsId204EnumKey = never

/**
 * @description Default Response
 */
export type DeleteBrandsId204 = DeleteBrandsId204EnumKey | null

/**
 * @description Default Response
 */
export type DeleteBrandsId404 = {
  /**
   * @type string
   */
  error: string
}

/**
 * @description Default Response
 */
export type DeleteBrandsId409 = {
  /**
   * @type string
   */
  error: string
}

export type DeleteBrandsIdMutationResponse = DeleteBrandsId204

export type DeleteBrandsIdMutation = {
  Response: DeleteBrandsId204
  PathParams: DeleteBrandsIdPathParams
  Errors: DeleteBrandsId404 | DeleteBrandsId409
}
