/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetBrands200 = {
  /**
   * @type array
   */
  brands: {
    /**
     * @type string, uuid
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
  }[]
}

export type GetBrandsQueryResponse = GetBrands200

export type GetBrandsQuery = {
  Response: GetBrands200
  Errors: any
}
