/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchBrandsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Default Response
 */
export type PatchBrandsId200 = {
  /**
   * @type object
   */
  brand: {
    /**
     * @type string, uuid
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
  }
}

/**
 * @description Default Response
 */
export type PatchBrandsId404 = {
  /**
   * @type string
   */
  error: string
}

/**
 * @description Default Response
 */
export type PatchBrandsId409 = {
  /**
   * @type string
   */
  error: string
}

export type PatchBrandsIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
}

export type PatchBrandsIdMutationResponse = PatchBrandsId200

export type PatchBrandsIdMutation = {
  Response: PatchBrandsId200
  Request: PatchBrandsIdMutationRequest
  PathParams: PatchBrandsIdPathParams
  Errors: PatchBrandsId404 | PatchBrandsId409
}
