/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type PostBrands201 = {
  /**
   * @type object
   */
  brand: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    name: string;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PostBrands409 = {
  /**
   * @type string
   */
  error: string;
};

export type PostBrandsMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string;
};

export type PostBrandsMutationResponse = PostBrands201;

export type PostBrandsMutation = {
  Response: PostBrands201;
  Request: PostBrandsMutationRequest;
  Errors: PostBrands409;
};
