/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type {
  GetStockEntriesQueryResponse,
  GetStockEntriesQueryParams,
} from '../../types/stockEntriesController/GetStockEntries.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getStockEntries } from '../../clients/stockEntriesController/getStockEntries.ts'

export const getStockEntriesQueryKey = (params?: GetStockEntriesQueryParams) =>
  [{ url: '/stock-entries' }, ...(params ? [params] : [])] as const

export type GetStockEntriesQueryKey = ReturnType<typeof getStockEntriesQueryKey>

export function getStockEntriesQueryOptions(
  params?: GetStockEntriesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getStockEntriesQueryKey(params)
  return queryOptions<
    GetStockEntriesQueryResponse,
    ResponseErrorConfig<Error>,
    GetStockEntriesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getStockEntries(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Retorna histórico global de entradas de estoque. Use brandId para uma marca específica, noBrand=true para produtos sem marca, ou omita para todas as marcas.
 * {@link /stock-entries}
 */
export function useGetStockEntries<
  TData = GetStockEntriesQueryResponse,
  TQueryData = GetStockEntriesQueryResponse,
  TQueryKey extends QueryKey = GetStockEntriesQueryKey,
>(
  params?: GetStockEntriesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetStockEntriesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getStockEntriesQueryKey(params)

  const query = useQuery(
    {
      ...getStockEntriesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
