/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetProductsProductIdStockEntriesQueryResponse,
  GetProductsProductIdStockEntriesPathParams,
} from "../../types/stockEntriesController/GetProductsProductIdStockEntries.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getProductsProductIdStockEntries } from "../../clients/stockEntriesController/getProductsProductIdStockEntries.ts";

export const getProductsProductIdStockEntriesQueryKey = (
  productId: GetProductsProductIdStockEntriesPathParams["productId"],
) =>
  [
    {
      url: "/products/:productId/stock-entries",
      params: { productId: productId },
    },
  ] as const;

export type GetProductsProductIdStockEntriesQueryKey = ReturnType<
  typeof getProductsProductIdStockEntriesQueryKey
>;

export function getProductsProductIdStockEntriesQueryOptions(
  productId: GetProductsProductIdStockEntriesPathParams["productId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProductsProductIdStockEntriesQueryKey(productId);
  return queryOptions<
    GetProductsProductIdStockEntriesQueryResponse,
    ResponseErrorConfig<Error>,
    GetProductsProductIdStockEntriesQueryResponse,
    typeof queryKey
  >({
    enabled: !!productId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProductsProductIdStockEntries(productId, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna histórico de entradas de estoque de um produto
 * {@link /products/:productId/stock-entries}
 */
export function useGetProductsProductIdStockEntries<
  TData = GetProductsProductIdStockEntriesQueryResponse,
  TQueryData = GetProductsProductIdStockEntriesQueryResponse,
  TQueryKey extends QueryKey = GetProductsProductIdStockEntriesQueryKey,
>(
  productId: GetProductsProductIdStockEntriesPathParams["productId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProductsProductIdStockEntriesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getProductsProductIdStockEntriesQueryKey(productId);

  const query = useQuery(
    {
      ...getProductsProductIdStockEntriesQueryOptions(productId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
