/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type {
  GetStockEntriesQueryResponse,
  GetStockEntriesQueryParams,
} from '../../types/stockEntriesController/GetStockEntries.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getStockEntries } from '../../clients/stockEntriesController/getStockEntries.ts'

export const getStockEntriesSuspenseQueryKey = (
  params?: GetStockEntriesQueryParams
) => [{ url: '/stock-entries' }, ...(params ? [params] : [])] as const

export type GetStockEntriesSuspenseQueryKey = ReturnType<
  typeof getStockEntriesSuspenseQueryKey
>

export function getStockEntriesSuspenseQueryOptions(
  params?: GetStockEntriesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getStockEntriesSuspenseQueryKey(params)
  return queryOptions<
    GetStockEntriesQueryResponse,
    ResponseErrorConfig<Error>,
    GetStockEntriesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getStockEntries(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Retorna histórico global de entradas de estoque. Use brandId para uma marca específica, noBrand=true para produtos sem marca, ou omita para todas as marcas.
 * {@link /stock-entries}
 */
export function useGetStockEntriesSuspense<
  TData = GetStockEntriesQueryResponse,
  TQueryKey extends QueryKey = GetStockEntriesSuspenseQueryKey,
>(
  params?: GetStockEntriesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetStockEntriesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getStockEntriesSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getStockEntriesSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
