/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostStocksStockIdExitsMutationRequest,
  PostStocksStockIdExitsMutationResponse,
  PostStocksStockIdExitsPathParams,
  PostStocksStockIdExits404,
  PostStocksStockIdExits422,
} from "../../types/stockEntriesController/PostStocksStockIdExits.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postStocksStockIdExits } from "../../clients/stockEntriesController/postStocksStockIdExits.ts";

export const postStocksStockIdExitsMutationKey = () =>
  [{ url: "/stocks/:stockId/exits" }] as const;

export type PostStocksStockIdExitsMutationKey = ReturnType<
  typeof postStocksStockIdExitsMutationKey
>;

export function postStocksStockIdExitsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostStocksStockIdExitsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postStocksStockIdExitsMutationKey();
  return mutationOptions<
    PostStocksStockIdExitsMutationResponse,
    ResponseErrorConfig<PostStocksStockIdExits404 | PostStocksStockIdExits422>,
    {
      stockId: PostStocksStockIdExitsPathParams["stockId"];
      data: PostStocksStockIdExitsMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ stockId, data }) => {
      return postStocksStockIdExits(stockId, data, config);
    },
  });
}

/**
 * @description Registra uma saída de estoque e decrementa a quantidade atual. Fica no histórico como lançamento de quantidade negativa.
 * {@link /stocks/:stockId/exits}
 */
export function usePostStocksStockIdExits<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostStocksStockIdExitsMutationResponse,
      ResponseErrorConfig<
        PostStocksStockIdExits404 | PostStocksStockIdExits422
      >,
      {
        stockId: PostStocksStockIdExitsPathParams["stockId"];
        data: PostStocksStockIdExitsMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostStocksStockIdExitsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postStocksStockIdExitsMutationKey();

  const baseOptions = postStocksStockIdExitsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostStocksStockIdExitsMutationResponse,
    ResponseErrorConfig<PostStocksStockIdExits404 | PostStocksStockIdExits422>,
    {
      stockId: PostStocksStockIdExitsPathParams["stockId"];
      data: PostStocksStockIdExitsMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostStocksStockIdExitsMutationResponse,
    ResponseErrorConfig<PostStocksStockIdExits404 | PostStocksStockIdExits422>,
    {
      stockId: PostStocksStockIdExitsPathParams["stockId"];
      data: PostStocksStockIdExitsMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostStocksStockIdExitsMutationResponse,
    ResponseErrorConfig<PostStocksStockIdExits404 | PostStocksStockIdExits422>,
    {
      stockId: PostStocksStockIdExitsPathParams["stockId"];
      data: PostStocksStockIdExitsMutationRequest;
    },
    TContext
  >;
}
