/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostStocksStockIdEntriesMutationRequest,
  PostStocksStockIdEntriesMutationResponse,
  PostStocksStockIdEntriesPathParams,
  PostStocksStockIdEntries404,
} from "../../types/stockEntriesController/PostStocksStockIdEntries.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postStocksStockIdEntries } from "../../clients/stockEntriesController/postStocksStockIdEntries.ts";

export const postStocksStockIdEntriesMutationKey = () =>
  [{ url: "/stocks/:stockId/entries" }] as const;

export type PostStocksStockIdEntriesMutationKey = ReturnType<
  typeof postStocksStockIdEntriesMutationKey
>;

export function postStocksStockIdEntriesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostStocksStockIdEntriesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postStocksStockIdEntriesMutationKey();
  return mutationOptions<
    PostStocksStockIdEntriesMutationResponse,
    ResponseErrorConfig<PostStocksStockIdEntries404>,
    {
      stockId: PostStocksStockIdEntriesPathParams["stockId"];
      data: PostStocksStockIdEntriesMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ stockId, data }) => {
      return postStocksStockIdEntries(stockId, data, config);
    },
  });
}

/**
 * @description Registra uma entrada de estoque e incrementa a quantidade atual
 * {@link /stocks/:stockId/entries}
 */
export function usePostStocksStockIdEntries<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostStocksStockIdEntriesMutationResponse,
      ResponseErrorConfig<PostStocksStockIdEntries404>,
      {
        stockId: PostStocksStockIdEntriesPathParams["stockId"];
        data: PostStocksStockIdEntriesMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostStocksStockIdEntriesMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postStocksStockIdEntriesMutationKey();

  const baseOptions = postStocksStockIdEntriesMutationOptions(
    config,
  ) as UseMutationOptions<
    PostStocksStockIdEntriesMutationResponse,
    ResponseErrorConfig<PostStocksStockIdEntries404>,
    {
      stockId: PostStocksStockIdEntriesPathParams["stockId"];
      data: PostStocksStockIdEntriesMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostStocksStockIdEntriesMutationResponse,
    ResponseErrorConfig<PostStocksStockIdEntries404>,
    {
      stockId: PostStocksStockIdEntriesPathParams["stockId"];
      data: PostStocksStockIdEntriesMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostStocksStockIdEntriesMutationResponse,
    ResponseErrorConfig<PostStocksStockIdEntries404>,
    {
      stockId: PostStocksStockIdEntriesPathParams["stockId"];
      data: PostStocksStockIdEntriesMutationRequest;
    },
    TContext
  >;
}
