/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeleteApiAuthMutationResponse, DeleteApiAuthPathParams } from "../../types/undefinedController/DeleteApiAuth.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteApiAuth } from "../../clients/undefinedController/deleteApiAuth.ts";

export const deleteApiAuthMutationKey = () => [{ url: '/api/auth/:*' }] as const

export type DeleteApiAuthMutationKey = ReturnType<typeof deleteApiAuthMutationKey>

export function deleteApiAuthMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteApiAuthMutationKey()
        return mutationOptions<DeleteApiAuthMutationResponse, ResponseErrorConfig<Error>, {: DeleteApiAuthPathParams["*"]}, TContext>({
          mutationKey,
          mutationFn: async({  }) => {
            return deleteApiAuth(, config)
          },
        })

}

/**
 * {@link /api/auth/:*}
 */
export function useDeleteApiAuth<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteApiAuthMutationResponse, ResponseErrorConfig<Error>, {: DeleteApiAuthPathParams["*"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteApiAuthMutationKey()

          const baseOptions = deleteApiAuthMutationOptions(config) as UseMutationOptions<DeleteApiAuthMutationResponse, ResponseErrorConfig<Error>, {: DeleteApiAuthPathParams["*"]}, TContext>
          

          return useMutation<DeleteApiAuthMutationResponse, ResponseErrorConfig<Error>, {: DeleteApiAuthPathParams["*"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteApiAuthMutationResponse, ResponseErrorConfig<Error>, {: DeleteApiAuthPathParams["*"]}, TContext>
      
}