/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthQueryResponse, GetApiAuthPathParams } from "../../types/undefinedController/GetApiAuth.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getApiAuth } from "../../clients/undefinedController/getApiAuth.ts";

export const getApiAuthQueryKey = (: GetApiAuthPathParams["*"]) => [{ url: '/api/auth/:*', params: {:} }] as const

export type GetApiAuthQueryKey = ReturnType<typeof getApiAuthQueryKey>

export function getApiAuthQueryOptions(: GetApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiAuthQueryKey()
        return queryOptions<GetApiAuthQueryResponse, ResponseErrorConfig<Error>, GetApiAuthQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiAuth(, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/auth/:*}
 */
export function useGetApiAuth<TData = GetApiAuthQueryResponse, TQueryData = GetApiAuthQueryResponse, TQueryKey extends QueryKey = GetApiAuthQueryKey>(: GetApiAuthPathParams["*"], options: 
{
  query?: Partial<QueryObserverOptions<GetApiAuthQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiAuthQueryKey()
         

         const query = useQuery({
          ...getApiAuthQueryOptions(, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}