/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetApiAuthQueryResponse, GetApiAuthPathParams } from "../../types/undefinedController/GetApiAuth.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getApiAuth } from "../../clients/undefinedController/getApiAuth.ts";

export const getApiAuthSuspenseQueryKey = (: GetApiAuthPathParams["*"]) => [{ url: '/api/auth/:*', params: {:} }] as const

export type GetApiAuthSuspenseQueryKey = ReturnType<typeof getApiAuthSuspenseQueryKey>

export function getApiAuthSuspenseQueryOptions(: GetApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getApiAuthSuspenseQueryKey()
        return queryOptions<GetApiAuthQueryResponse, ResponseErrorConfig<Error>, GetApiAuthQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getApiAuth(, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /api/auth/:*}
 */
export function useGetApiAuthSuspense<TData = GetApiAuthQueryResponse, TQueryKey extends QueryKey = GetApiAuthSuspenseQueryKey>(: GetApiAuthPathParams["*"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetApiAuthQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getApiAuthSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getApiAuthSuspenseQueryOptions(, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}