/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostApiAuthMutationResponse, PostApiAuthPathParams } from "../../types/undefinedController/PostApiAuth.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postApiAuth } from "../../clients/undefinedController/postApiAuth.ts";

export const postApiAuthMutationKey = () => [{ url: '/api/auth/:*' }] as const

export type PostApiAuthMutationKey = ReturnType<typeof postApiAuthMutationKey>

export function postApiAuthMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = postApiAuthMutationKey()
        return mutationOptions<PostApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PostApiAuthPathParams["*"]}, TContext>({
          mutationKey,
          mutationFn: async({  }) => {
            return postApiAuth(, config)
          },
        })

}

/**
 * {@link /api/auth/:*}
 */
export function usePostApiAuth<TContext>(options: 
{
  mutation?: UseMutationOptions<PostApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PostApiAuthPathParams["*"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postApiAuthMutationKey()

          const baseOptions = postApiAuthMutationOptions(config) as UseMutationOptions<PostApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PostApiAuthPathParams["*"]}, TContext>
          

          return useMutation<PostApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PostApiAuthPathParams["*"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PostApiAuthPathParams["*"]}, TContext>
      
}