/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PatchApiAuthMutationResponse, PatchApiAuthPathParams } from "../../types/undefinedController/PatchApiAuth.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { patchApiAuth } from "../../clients/undefinedController/patchApiAuth.ts";

export const patchApiAuthMutationKey = () => [{ url: '/api/auth/:*' }] as const

export type PatchApiAuthMutationKey = ReturnType<typeof patchApiAuthMutationKey>

export function patchApiAuthMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = patchApiAuthMutationKey()
        return mutationOptions<PatchApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PatchApiAuthPathParams["*"]}, TContext>({
          mutationKey,
          mutationFn: async({  }) => {
            return patchApiAuth(, config)
          },
        })

}

/**
 * {@link /api/auth/:*}
 */
export function usePatchApiAuth<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PatchApiAuthPathParams["*"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? patchApiAuthMutationKey()

          const baseOptions = patchApiAuthMutationOptions(config) as UseMutationOptions<PatchApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PatchApiAuthPathParams["*"]}, TContext>
          

          return useMutation<PatchApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PatchApiAuthPathParams["*"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PatchApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PatchApiAuthPathParams["*"]}, TContext>
      
}