/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PutApiAuthMutationResponse, PutApiAuthPathParams } from "../../types/undefinedController/PutApiAuth.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { putApiAuth } from "../../clients/undefinedController/putApiAuth.ts";

export const putApiAuthMutationKey = () => [{ url: '/api/auth/:*' }] as const

export type PutApiAuthMutationKey = ReturnType<typeof putApiAuthMutationKey>

export function putApiAuthMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = putApiAuthMutationKey()
        return mutationOptions<PutApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PutApiAuthPathParams["*"]}, TContext>({
          mutationKey,
          mutationFn: async({  }) => {
            return putApiAuth(, config)
          },
        })

}

/**
 * {@link /api/auth/:*}
 */
export function usePutApiAuth<TContext>(options: 
{
  mutation?: UseMutationOptions<PutApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PutApiAuthPathParams["*"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? putApiAuthMutationKey()

          const baseOptions = putApiAuthMutationOptions(config) as UseMutationOptions<PutApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PutApiAuthPathParams["*"]}, TContext>
          

          return useMutation<PutApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PutApiAuthPathParams["*"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PutApiAuthMutationResponse, ResponseErrorConfig<Error>, {: PutApiAuthPathParams["*"]}, TContext>
      
}