/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  GetReportsStockByBrandQueryResponse,
  GetReportsStockByBrandQueryParams,
} from '../../types/reportsController/GetReportsStockByBrand.ts'

function getGetReportsStockByBrandUrl() {
  const res = { method: 'GET', url: `/reports/stock-by-brand` as const }
  return res
}

/**
 * @description Retorna distribuição de estoque por produto de uma marca. Use brandId para uma marca específica ou noBrand=true para produtos sem marca.
 * {@link /reports/stock-by-brand}
 */
export async function getReportsStockByBrand(
  params?: GetReportsStockByBrandQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetReportsStockByBrandQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetReportsStockByBrandUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
