/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetReportsFullReplenishmentAlertsQueryResponse } from "../../types/reportsController/GetReportsFullReplenishmentAlerts.ts";

function getGetReportsFullReplenishmentAlertsUrl() {
  const res = {
    method: "GET",
    url: `/reports/full-replenishment-alerts` as const,
  };
  return res;
}

/**
 * @description Alerta de Abastecimento do Full: dias de autonomia por depósito full, quantidade sugerida, estoque parado e SKUs que a conta vende fora do full
 * {@link /reports/full-replenishment-alerts}
 */
export async function getReportsFullReplenishmentAlerts(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetReportsFullReplenishmentAlertsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetReportsFullReplenishmentAlertsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
