/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  GetReportsAbcQueryResponse,
  GetReportsAbcQueryParams,
} from "../../types/reportsController/GetReportsAbc.ts";

function getGetReportsAbcUrl() {
  const res = { method: "GET", url: `/reports/abc` as const };
  return res;
}

/**
 * {@link /reports/abc}
 */
export async function getReportsAbc(
  params: GetReportsAbcQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetReportsAbcQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetReportsAbcUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
