/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  GetReportsSalesQueryResponse,
  GetReportsSalesQueryParams,
} from "../../types/reportsController/GetReportsSales.ts";

function getGetReportsSalesUrl() {
  const res = { method: "GET", url: `/reports/sales` as const };
  return res;
}

/**
 * @description Retorna relatório de vendas por período, sem paginação, com SKU, loja, canal, depósito e valor.
 * {@link /reports/sales}
 */
export async function getReportsSales(
  params: GetReportsSalesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetReportsSalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetReportsSalesUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
