/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostReportsFullReplenishmentAlertsAnalyzeMutationRequest,
  PostReportsFullReplenishmentAlertsAnalyzeMutationResponse,
  PostReportsFullReplenishmentAlertsAnalyze404,
  PostReportsFullReplenishmentAlertsAnalyze501,
  PostReportsFullReplenishmentAlertsAnalyze502,
} from "../../types/reportsController/PostReportsFullReplenishmentAlertsAnalyze.ts";

function getPostReportsFullReplenishmentAlertsAnalyzeUrl() {
  const res = {
    method: "POST",
    url: `/reports/full-replenishment-alerts/analyze` as const,
  };
  return res;
}

/**
 * @description Leitura crítica de uma linha do Abastecimento do Full: identifica o produto, pesa o calendário comercial e propõe um fator sazonal. A quantidade da regra continua sendo o padrão.
 * {@link /reports/full-replenishment-alerts/analyze}
 */
export async function postReportsFullReplenishmentAlertsAnalyze(
  data: PostReportsFullReplenishmentAlertsAnalyzeMutationRequest,
  config: Partial<
    RequestConfig<PostReportsFullReplenishmentAlertsAnalyzeMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostReportsFullReplenishmentAlertsAnalyzeMutationResponse,
    ResponseErrorConfig<
      | PostReportsFullReplenishmentAlertsAnalyze404
      | PostReportsFullReplenishmentAlertsAnalyze501
      | PostReportsFullReplenishmentAlertsAnalyze502
    >,
    PostReportsFullReplenishmentAlertsAnalyzeMutationRequest
  >({
    method: "POST",
    url: getPostReportsFullReplenishmentAlertsAnalyzeUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
