/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type { GetStoresQueryResponse } from '../../types/storesController/GetStores.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getStores } from '../../clients/storesController/getStores.ts'

export const getStoresQueryKey = () => [{ url: '/stores' }] as const

export type GetStoresQueryKey = ReturnType<typeof getStoresQueryKey>

export function getStoresQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getStoresQueryKey()
  return queryOptions<
    GetStoresQueryResponse,
    ResponseErrorConfig<Error>,
    GetStoresQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getStores({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Lista todas as lojas
 * {@link /stores}
 */
export function useGetStores<
  TData = GetStoresQueryResponse,
  TQueryData = GetStoresQueryResponse,
  TQueryKey extends QueryKey = GetStoresQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetStoresQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getStoresQueryKey()

  const query = useQuery(
    {
      ...getStoresQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
