/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { GetStoresQueryResponse } from "../../types/storesController/GetStores.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getStores } from "../../clients/storesController/getStores.ts";

export const getStoresSuspenseQueryKey = () => [{ url: "/stores" }] as const;

export type GetStoresSuspenseQueryKey = ReturnType<
  typeof getStoresSuspenseQueryKey
>;

export function getStoresSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getStoresSuspenseQueryKey();
  return queryOptions<
    GetStoresQueryResponse,
    ResponseErrorConfig<Error>,
    GetStoresQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getStores({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Lista todas as lojas
 * {@link /stores}
 */
export function useGetStoresSuspense<
  TData = GetStoresQueryResponse,
  TQueryKey extends QueryKey = GetStoresSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetStoresQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getStoresSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getStoresSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
