/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteSalesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

export type DeleteSalesId204EnumKey = never

/**
 * @description Default Response
 */
export type DeleteSalesId204 = DeleteSalesId204EnumKey | null

/**
 * @description Default Response
 */
export type DeleteSalesId404 = {
  /**
   * @type string
   */
  error: string
}

export type DeleteSalesIdMutationResponse = DeleteSalesId204

export type DeleteSalesIdMutation = {
  Response: DeleteSalesId204
  PathParams: DeleteSalesIdPathParams
  Errors: DeleteSalesId404
}
