/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetSalesQueryParams = {
  /**
   * @type string | undefined, date-time
   */
  startDate?: string;
  /**
   * @type string | undefined, date-time
   */
  endDate?: string;
  /**
   * @type string | undefined, uuid
   */
  brandId?: string;
  /**
   * @type string | undefined, uuid
   */
  storeId?: string;
  /**
   * @minLength 1
   * @maxLength 9007199254740991
   * @default 1
   * @type integer | undefined
   */
  page?: number;
  /**
   * @minLength 1
   * @maxLength 100
   * @default 10
   * @type integer | undefined
   */
  limit?: number;
};

export const itemsChannelEnum = {
  Amazon: "Amazon",
  "Mercado Livre": "Mercado Livre",
  Shopee: "Shopee",
  Direto: "Direto",
} as const;

export type ItemsChannelEnumKey =
  (typeof itemsChannelEnum)[keyof typeof itemsChannelEnum];

export const stockMarketplaceEnum2 = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type StockMarketplaceEnum2Key =
  (typeof stockMarketplaceEnum2)[keyof typeof stockMarketplaceEnum2];

/**
 * @description Default Response
 */
export type GetSales200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @type string, uuid
     */
    stock_id: string;
    /**
     * @type string, uuid
     */
    store_id: string | null;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    sale_price: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total_price: number;
    /**
     * @type string
     */
    channel: ItemsChannelEnumKey;
    /**
     * @type string, date-time
     */
    sale_date: string;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
    /**
     * @type object
     */
    product: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      sku: string;
      /**
       * @type string
       */
      ean: string;
      /**
       * @type string, uuid
       */
      brand_id: string | null;
      /**
       * @type string
       */
      url_image: string | null;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    };
    /**
     * @type object
     */
    stock: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type string
       */
      title: string;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number;
      /**
       * @type boolean
       */
      full: boolean;
      /**
       * @type string
       */
      marketplace: StockMarketplaceEnum2Key | null;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    };
    /**
     * @type object
     */
    store: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      name: string;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    } | null;
  }[];
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  totalCount: number;
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  totalPages: number;
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  currentPage: number;
  /**
   * @type array
   */
  brandCounts: {
    /**
     * @type string, uuid
     */
    brand_id: string;
    /**
     * @type string
     */
    brand_name: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    count: number;
  }[];
};

export type GetSalesQueryResponse = GetSales200;

export type GetSalesQuery = {
  Response: GetSales200;
  QueryParams: GetSalesQueryParams;
  Errors: any;
};
