/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchSalesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

export const saleChannelEnum2 = {
  Amazon: 'Amazon',
  'Mercado Livre': 'Mercado Livre',
  Shopee: 'Shopee',
  Direto: 'Direto',
} as const

export type SaleChannelEnum2Key =
  (typeof saleChannelEnum2)[keyof typeof saleChannelEnum2]

/**
 * @description Default Response
 */
export type PatchSalesId200 = {
  /**
   * @type object
   */
  sale: {
    /**
     * @type string, uuid
     */
    id: string
    /**
     * @type string, uuid
     */
    product_id: string
    /**
     * @type string, uuid
     */
    stock_id: string
    /**
     * @type string, uuid
     */
    store_id: string | null
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    sale_price: number
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total_price: number
    /**
     * @type string
     */
    channel: SaleChannelEnum2Key
    /**
     * @type string, date-time
     */
    sale_date: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
    /**
     * @type object
     */
    product: {
      /**
       * @type string, uuid
       */
      id: string
      /**
       * @type string
       */
      sku: string
      /**
       * @type string
       */
      ean: string
      /**
       * @type string, uuid
       */
      brand_id: string | null
      /**
       * @type string
       */
      url_image: string | null
      /**
       * @type string, date-time
       */
      created_at: string
      /**
       * @type string, date-time
       */
      updated_at: string
    }
    /**
     * @type object
     */
    stock: {
      /**
       * @type string, uuid
       */
      id: string
      /**
       * @type string, uuid
       */
      product_id: string
      /**
       * @type string
       */
      title: string
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number
      /**
       * @type boolean
       */
      full: boolean
      /**
       * @type string, date-time
       */
      created_at: string
      /**
       * @type string, date-time
       */
      updated_at: string
    }
    /**
     * @type object
     */
    store: {
      /**
       * @type string, uuid
       */
      id: string
      /**
       * @type string
       */
      name: string
      /**
       * @type string, date-time
       */
      created_at: string
      /**
       * @type string, date-time
       */
      updated_at: string
    } | null
  }
}

/**
 * @description Default Response
 */
export type PatchSalesId400 = {
  /**
   * @type string
   */
  error: string
}

/**
 * @description Default Response
 */
export type PatchSalesId404 = {
  /**
   * @type string
   */
  error: string
}

export const patchSalesIdMutationRequestChannelEnum = {
  Amazon: 'Amazon',
  'Mercado Livre': 'Mercado Livre',
  Shopee: 'Shopee',
  Direto: 'Direto',
} as const

export type PatchSalesIdMutationRequestChannelEnumKey =
  (typeof patchSalesIdMutationRequestChannelEnum)[keyof typeof patchSalesIdMutationRequestChannelEnum]

export type PatchSalesIdMutationRequest = {
  /**
   * @maxLength 9007199254740991
   * @type integer | undefined
   */
  quantity?: number
  /**
   * @minLength 0
   * @maxLength 9007199254740991
   * @type integer | undefined
   */
  sale_price?: number
  /**
   * @type string | undefined
   */
  channel?: PatchSalesIdMutationRequestChannelEnumKey
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   * @type string | undefined
   */
  sale_date?: string
  /**
   * @type string, uuid
   */
  store_id?: string | null
}

export type PatchSalesIdMutationResponse = PatchSalesId200

export type PatchSalesIdMutation = {
  Response: PatchSalesId200
  Request: PatchSalesIdMutationRequest
  PathParams: PatchSalesIdPathParams
  Errors: PatchSalesId400 | PatchSalesId404
}
