/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const saleChannelEnum = {
  Amazon: "Amazon",
  "Mercado Livre": "Mercado Livre",
  Shopee: "Shopee",
  Direto: "Direto",
} as const;

export type SaleChannelEnumKey =
  (typeof saleChannelEnum)[keyof typeof saleChannelEnum];

export const stockMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type StockMarketplaceEnumKey =
  (typeof stockMarketplaceEnum)[keyof typeof stockMarketplaceEnum];

/**
 * @description Default Response
 */
export type PostSales201 = {
  /**
   * @type object
   */
  sale: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @type string, uuid
     */
    stock_id: string;
    /**
     * @type string, uuid
     */
    store_id: string | null;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    sale_price: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total_price: number;
    /**
     * @type string
     */
    channel: SaleChannelEnumKey;
    /**
     * @type string, date-time
     */
    sale_date: string;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
    /**
     * @type object
     */
    product: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      sku: string;
      /**
       * @type string
       */
      ean: string;
      /**
       * @type string, uuid
       */
      brand_id: string | null;
      /**
       * @type string
       */
      url_image: string | null;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    };
    /**
     * @type object
     */
    stock: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type string
       */
      title: string;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number;
      /**
       * @type boolean
       */
      full: boolean;
      /**
       * @type string
       */
      marketplace: StockMarketplaceEnumKey | null;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    };
    /**
     * @type object
     */
    store: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      name: string;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    } | null;
  };
};

/**
 * @description Default Response
 */
export type PostSales400 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostSales404 = {
  /**
   * @type string
   */
  error: string;
};

export const postSalesMutationRequestChannelEnum = {
  Amazon: "Amazon",
  "Mercado Livre": "Mercado Livre",
  Shopee: "Shopee",
  Direto: "Direto",
} as const;

export type PostSalesMutationRequestChannelEnumKey =
  (typeof postSalesMutationRequestChannelEnum)[keyof typeof postSalesMutationRequestChannelEnum];

export type PostSalesMutationRequest = {
  /**
   * @type string, uuid
   */
  product_id: string;
  /**
   * @type string, uuid
   */
  stock_id: string;
  /**
   * @type string, uuid
   */
  store_id?: string | null;
  /**
   * @maxLength 9007199254740991
   * @type integer
   */
  quantity: number;
  /**
   * @minLength 0
   * @maxLength 9007199254740991
   * @type integer
   */
  sale_price: number;
  /**
   * @type string
   */
  channel: PostSalesMutationRequestChannelEnumKey;
  /**
   * @pattern ^\d{4}-\d{2}-\d{2}$
   * @type string
   */
  sale_date: string;
};

export type PostSalesMutationResponse = PostSales201;

export type PostSalesMutation = {
  Response: PostSales201;
  Request: PostSalesMutationRequest;
  Errors: PostSales400 | PostSales404;
};
