/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteShipmentAccountsByIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Default Response
 */
export type DeleteShipmentAccountsById204 = any;

/**
 * @description Default Response
 */
export type DeleteShipmentAccountsById404 = {
  /**
   * @type string
   */
  error: string;
};

export type DeleteShipmentAccountsByIdMutationResponse =
  DeleteShipmentAccountsById204;

export type DeleteShipmentAccountsByIdMutation = {
  Response: DeleteShipmentAccountsById204;
  PathParams: DeleteShipmentAccountsByIdPathParams;
  Errors: DeleteShipmentAccountsById404;
};
