/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetShipmentAccounts200 = {
  /**
   * @type array
   */
  accounts: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    name: string;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  }[];
};

export type GetShipmentAccountsQueryResponse = GetShipmentAccounts200;

export type GetShipmentAccountsQuery = {
  Response: GetShipmentAccounts200;
  Errors: any;
};
