/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type PostShipmentAccounts201 = {
  /**
   * @type object
   */
  account: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    name: string;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PostShipmentAccounts409 = {
  /**
   * @type string
   */
  error: string;
};

export type PostShipmentAccountsMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string;
};

export type PostShipmentAccountsMutationResponse = PostShipmentAccounts201;

export type PostShipmentAccountsMutation = {
  Response: PostShipmentAccounts201;
  Request: PostShipmentAccountsMutationRequest;
  Errors: PostShipmentAccounts409;
};
