/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutShipmentAccountsByIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Default Response
 */
export type PutShipmentAccountsById200 = {
  /**
   * @type object
   */
  account: {
    /**
     * @type string, uuid
     */
    id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string, date-time
     */
    created_at: string
    /**
     * @type string, date-time
     */
    updated_at: string
  }
}

/**
 * @description Default Response
 */
export type PutShipmentAccountsById404 = {
  /**
   * @type string
   */
  error: string
}

/**
 * @description Default Response
 */
export type PutShipmentAccountsById409 = {
  /**
   * @type string
   */
  error: string
}

export type PutShipmentAccountsByIdMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  name: string
}

export type PutShipmentAccountsByIdMutationResponse = PutShipmentAccountsById200

export type PutShipmentAccountsByIdMutation = {
  Response: PutShipmentAccountsById200
  Request: PutShipmentAccountsByIdMutationRequest
  PathParams: PutShipmentAccountsByIdPathParams
  Errors: PutShipmentAccountsById404 | PutShipmentAccountsById409
}
