/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  PostShipmentAccountsMutationRequest,
  PostShipmentAccountsMutationResponse,
  PostShipmentAccounts409,
} from '../../types/shipmentAccountsController/PostShipmentAccounts.ts'

function getPostShipmentAccountsUrl() {
  const res = { method: 'POST', url: `/shipment-accounts` as const }
  return res
}

/**
 * {@link /shipment-accounts}
 */
export async function postShipmentAccounts(
  data: PostShipmentAccountsMutationRequest,
  config: Partial<RequestConfig<PostShipmentAccountsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostShipmentAccountsMutationResponse,
    ResponseErrorConfig<PostShipmentAccounts409>,
    PostShipmentAccountsMutationRequest
  >({
    method: 'POST',
    url: getPostShipmentAccountsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
