/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PutShipmentAccountsByIdMutationRequest,
  PutShipmentAccountsByIdMutationResponse,
  PutShipmentAccountsByIdPathParams,
  PutShipmentAccountsById404,
  PutShipmentAccountsById409,
} from "../../types/shipmentAccountsController/PutShipmentAccountsById.ts";

function getPutShipmentAccountsByIdUrl(
  id: PutShipmentAccountsByIdPathParams["id"],
) {
  const res = { method: "PUT", url: `/shipment-accounts/${id}` as const };
  return res;
}

/**
 * {@link /shipment-accounts/:id}
 */
export async function putShipmentAccountsById(
  id: PutShipmentAccountsByIdPathParams["id"],
  data: PutShipmentAccountsByIdMutationRequest,
  config: Partial<RequestConfig<PutShipmentAccountsByIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PutShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<
      PutShipmentAccountsById404 | PutShipmentAccountsById409
    >,
    PutShipmentAccountsByIdMutationRequest
  >({
    method: "PUT",
    url: getPutShipmentAccountsByIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
