/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetMetricsMonthlySalesQueryResponse } from "../../types/metricsController/GetMetricsMonthlySales.ts";

function getGetMetricsMonthlySalesUrl() {
  const res = { method: "GET", url: `/metrics/monthly-sales` as const };
  return res;
}

/**
 * @description Retorna faturamento diario do mes atual com media diaria
 * {@link /metrics/monthly-sales}
 */
export async function getMetricsMonthlySales(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMetricsMonthlySalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetMetricsMonthlySalesUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
