/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetMetricsLastMonthSalesQueryResponse } from "../../types/metricsController/GetMetricsLastMonthSales.ts";

function getGetMetricsLastMonthSalesUrl() {
  const res = { method: "GET", url: `/metrics/last-month-sales` as const };
  return res;
}

/**
 * @description Retorna o total de vendas do mes passado em centavos
 * {@link /metrics/last-month-sales}
 */
export async function getMetricsLastMonthSales(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMetricsLastMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetMetricsLastMonthSalesUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
