/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  GetProductsProductIdStockEntriesQueryResponse,
  GetProductsProductIdStockEntriesPathParams,
} from "../../types/stockEntriesController/GetProductsProductIdStockEntries.ts";

function getGetProductsProductIdStockEntriesUrl(
  productId: GetProductsProductIdStockEntriesPathParams["productId"],
) {
  const res = {
    method: "GET",
    url: `/products/${productId}/stock-entries` as const,
  };
  return res;
}

/**
 * @description Retorna histórico de entradas de estoque de um produto
 * {@link /products/:productId/stock-entries}
 */
export async function getProductsProductIdStockEntries(
  productId: GetProductsProductIdStockEntriesPathParams["productId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProductsProductIdStockEntriesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetProductsProductIdStockEntriesUrl(productId).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
