/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  GetStockEntriesQueryResponse,
  GetStockEntriesQueryParams,
} from '../../types/stockEntriesController/GetStockEntries.ts'

function getGetStockEntriesUrl() {
  const res = { method: 'GET', url: `/stock-entries` as const }
  return res
}

/**
 * @description Retorna histórico global de entradas de estoque. Use brandId para uma marca específica, noBrand=true para produtos sem marca, ou omita para todas as marcas.
 * {@link /stock-entries}
 */
export async function getStockEntries(
  params?: GetStockEntriesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetStockEntriesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetStockEntriesUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
