/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostStocksStockIdExitsMutationRequest,
  PostStocksStockIdExitsMutationResponse,
  PostStocksStockIdExitsPathParams,
  PostStocksStockIdExits404,
  PostStocksStockIdExits422,
} from "../../types/stockEntriesController/PostStocksStockIdExits.ts";

function getPostStocksStockIdExitsUrl(
  stockId: PostStocksStockIdExitsPathParams["stockId"],
) {
  const res = { method: "POST", url: `/stocks/${stockId}/exits` as const };
  return res;
}

/**
 * @description Registra uma saída de estoque e decrementa a quantidade atual. Fica no histórico como lançamento de quantidade negativa.
 * {@link /stocks/:stockId/exits}
 */
export async function postStocksStockIdExits(
  stockId: PostStocksStockIdExitsPathParams["stockId"],
  data: PostStocksStockIdExitsMutationRequest,
  config: Partial<RequestConfig<PostStocksStockIdExitsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostStocksStockIdExitsMutationResponse,
    ResponseErrorConfig<PostStocksStockIdExits404 | PostStocksStockIdExits422>,
    PostStocksStockIdExitsMutationRequest
  >({
    method: "POST",
    url: getPostStocksStockIdExitsUrl(stockId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
