/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  PostStocksStockIdEntriesMutationRequest,
  PostStocksStockIdEntriesMutationResponse,
  PostStocksStockIdEntriesPathParams,
  PostStocksStockIdEntries404,
} from '../../types/stockEntriesController/PostStocksStockIdEntries.ts'

function getPostStocksStockIdEntriesUrl(
  stockId: PostStocksStockIdEntriesPathParams['stockId']
) {
  const res = { method: 'POST', url: `/stocks/${stockId}/entries` as const }
  return res
}

/**
 * @description Registra uma entrada de estoque e incrementa a quantidade atual
 * {@link /stocks/:stockId/entries}
 */
export async function postStocksStockIdEntries(
  stockId: PostStocksStockIdEntriesPathParams['stockId'],
  data: PostStocksStockIdEntriesMutationRequest,
  config: Partial<RequestConfig<PostStocksStockIdEntriesMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostStocksStockIdEntriesMutationResponse,
    ResponseErrorConfig<PostStocksStockIdEntries404>,
    PostStocksStockIdEntriesMutationRequest
  >({
    method: 'POST',
    url: getPostStocksStockIdEntriesUrl(stockId).url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
