/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const notificationsKindEnum = {
  reposicao: "reposicao",
  abastecimento_full: "abastecimento_full",
  fora_do_full: "fora_do_full",
} as const;

export type NotificationsKindEnumKey =
  (typeof notificationsKindEnum)[keyof typeof notificationsKindEnum];

export const notificationsTransitionEnum = {
  entrou: "entrou",
  piorou: "piorou",
} as const;

export type NotificationsTransitionEnumKey =
  (typeof notificationsTransitionEnum)[keyof typeof notificationsTransitionEnum];

export const notificationsSeverityEnum = {
  critico: "critico",
  atencao: "atencao",
} as const;

export type NotificationsSeverityEnumKey =
  (typeof notificationsSeverityEnum)[keyof typeof notificationsSeverityEnum];

export const notificationsMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type NotificationsMarketplaceEnumKey =
  (typeof notificationsMarketplaceEnum)[keyof typeof notificationsMarketplaceEnum];

/**
 * @description Default Response
 */
export type GetNotifications200 = {
  /**
   * @type number
   */
  unread_count: number;
  /**
   * @type array
   */
  notifications: {
    /**
     * @type string
     */
    id: string;
    /**
     * @type string
     */
    kind: NotificationsKindEnumKey;
    /**
     * @type string
     */
    transition: NotificationsTransitionEnumKey;
    /**
     * @type string
     */
    severity: NotificationsSeverityEnumKey | null;
    /**
     * @type string
     */
    product_id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    stock_id: string | null;
    /**
     * @type string
     */
    stock_title: string | null;
    /**
     * @type string
     */
    store_id: string | null;
    /**
     * @type string
     */
    store_name: string | null;
    /**
     * @type string
     */
    marketplace: NotificationsMarketplaceEnumKey | null;
    /**
     * @type number
     */
    physical_stock_qty: number | null;
    /**
     * @type number
     */
    units_30d: number | null;
    /**
     * @type number
     */
    days_of_autonomy: number | null;
    /**
     * @type number
     */
    lead_time_days: number | null;
    /**
     * @type number
     */
    account_units: number | null;
    /**
     * @type string
     */
    created_at: string;
    /**
     * @type string
     */
    read_at: string | null;
    /**
     * @type string
     */
    resolved_at: string | null;
  }[];
};

export type GetNotificationsQueryResponse = GetNotifications200;

export type GetNotificationsQuery = {
  Response: GetNotifications200;
  Errors: any;
};
