/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchNotificationsByIdReadPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Default Response
 */
export type PatchNotificationsByIdRead204 = any;

/**
 * @description Default Response
 */
export type PatchNotificationsByIdRead404 = {
  /**
   * @type string
   */
  error: string;
};

export type PatchNotificationsByIdReadMutationResponse =
  PatchNotificationsByIdRead204;

export type PatchNotificationsByIdReadMutation = {
  Response: PatchNotificationsByIdRead204;
  PathParams: PatchNotificationsByIdReadPathParams;
  Errors: PatchNotificationsByIdRead404;
};
