/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type PostNotificationsReadAll200 = {
  /**
   * @type number
   */
  updated: number;
};

export type PostNotificationsReadAllMutationResponse =
  PostNotificationsReadAll200;

export type PostNotificationsReadAllMutation = {
  Response: PostNotificationsReadAll200;
  Errors: any;
};
