/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-axios-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-axios-client";
import type { DeleteApiAuthMutationResponse, DeleteApiAuthPathParams } from "../../types/undefinedController/DeleteApiAuth.ts";

function getDeleteApiAuthUrl(: DeleteApiAuthPathParams["*"]) {
  const res = { method: 'DELETE', url: `/api/auth/${}` as const }
  return res
}

/**
 * {@link /api/auth/:*}
 */
export async function deleteApiAuth(: DeleteApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<DeleteApiAuthMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteApiAuthUrl().url.toString(), ... requestConfig })
  return res.data
}