/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-axios-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-axios-client";
import type { GetApiAuthQueryResponse, GetApiAuthPathParams } from "../../types/undefinedController/GetApiAuth.ts";

function getGetApiAuthUrl(: GetApiAuthPathParams["*"]) {
  const res = { method: 'GET', url: `/api/auth/${}` as const }
  return res
}

/**
 * {@link /api/auth/:*}
 */
export async function getApiAuth(: GetApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<GetApiAuthQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetApiAuthUrl().url.toString(), ... requestConfig })
  return res.data
}