/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-axios-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-axios-client";
import type { HeadApiAuthMutationResponse, HeadApiAuthPathParams } from "../../types/undefinedController/HeadApiAuth.ts";

function getHeadApiAuthUrl(: HeadApiAuthPathParams["*"]) {
  const res = { method: 'HEAD', url: `/api/auth/${}` as const }
  return res
}

/**
 * {@link /api/auth/:*}
 */
export async function headApiAuth(: HeadApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<HeadApiAuthMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "HEAD", url : getHeadApiAuthUrl().url.toString(), ... requestConfig })
  return res.data
}