/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-axios-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-axios-client";
import type { OptionsApiAuthMutationResponse, OptionsApiAuthPathParams } from "../../types/undefinedController/OptionsApiAuth.ts";

function getOptionsApiAuthUrl(: OptionsApiAuthPathParams["*"]) {
  const res = { method: 'OPTIONS', url: `/api/auth/${}` as const }
  return res
}

/**
 * {@link /api/auth/:*}
 */
export async function optionsApiAuth(: OptionsApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<OptionsApiAuthMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "OPTIONS", url : getOptionsApiAuthUrl().url.toString(), ... requestConfig })
  return res.data
}