/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-axios-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-axios-client";
import type { PostApiAuthMutationResponse, PostApiAuthPathParams } from "../../types/undefinedController/PostApiAuth.ts";

function getPostApiAuthUrl(: PostApiAuthPathParams["*"]) {
  const res = { method: 'POST', url: `/api/auth/${}` as const }
  return res
}

/**
 * {@link /api/auth/:*}
 */
export async function postApiAuth(: PostApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PostApiAuthMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getPostApiAuthUrl().url.toString(), ... requestConfig })
  return res.data
}