/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-axios-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-axios-client";
import type { PutApiAuthMutationResponse, PutApiAuthPathParams } from "../../types/undefinedController/PutApiAuth.ts";

function getPutApiAuthUrl(: PutApiAuthPathParams["*"]) {
  const res = { method: 'PUT', url: `/api/auth/${}` as const }
  return res
}

/**
 * {@link /api/auth/:*}
 */
export async function putApiAuth(: PutApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<PutApiAuthMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "PUT", url : getPutApiAuthUrl().url.toString(), ... requestConfig })
  return res.data
}