/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/kubb-axios-client";
import type { Client, RequestConfig, ResponseErrorConfig } from "@/lib/kubb-axios-client";
import type { TraceApiAuthMutationResponse, TraceApiAuthPathParams } from "../../types/undefinedController/TraceApiAuth.ts";

function getTraceApiAuthUrl(: TraceApiAuthPathParams["*"]) {
  const res = { method: 'TRACE', url: `/api/auth/${}` as const }
  return res
}

/**
 * {@link /api/auth/:*}
 */
export async function traceApiAuth(: TraceApiAuthPathParams["*"], config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config



  const res = await request<TraceApiAuthMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "TRACE", url : getTraceApiAuthUrl().url.toString(), ... requestConfig })
  return res.data
}