/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteStocksStockIdPathParams = {
  /**
   * @type string, uuid
   */
  stockId: string
}

export type DeleteStocksStockId204EnumKey = never

/**
 * @description Default Response
 */
export type DeleteStocksStockId204 = DeleteStocksStockId204EnumKey | null

/**
 * @description Default Response
 */
export type DeleteStocksStockId404 = {
  /**
   * @type string
   */
  error: string
}

export type DeleteStocksStockIdMutationResponse = DeleteStocksStockId204

export type DeleteStocksStockIdMutation = {
  Response: DeleteStocksStockId204
  PathParams: DeleteStocksStockIdPathParams
  Errors: DeleteStocksStockId404
}
