/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProductsProductIdStocksPathParams = {
  /**
   * @type string, uuid
   */
  productId: string;
};

/**
 * @description Default Response
 */
export type GetProductsProductIdStocks200 = {
  /**
   * @type array
   */
  stocks: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @type string
     */
    title: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    qtde: number;
    /**
     * @type boolean
     */
    full: boolean;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  }[];
};

/**
 * @description Default Response
 */
export type GetProductsProductIdStocks404 = {
  /**
   * @type string
   */
  error: string;
};

export type GetProductsProductIdStocksQueryResponse =
  GetProductsProductIdStocks200;

export type GetProductsProductIdStocksQuery = {
  Response: GetProductsProductIdStocks200;
  PathParams: GetProductsProductIdStocksPathParams;
  Errors: GetProductsProductIdStocks404;
};
