/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchStocksStockIdPathParams = {
  /**
   * @type string, uuid
   */
  stockId: string;
};

/**
 * @description Default Response
 */
export type PatchStocksStockId200 = {
  /**
   * @type object
   */
  stock: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @type string
     */
    title: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    qtde: number;
    /**
     * @type boolean
     */
    full: boolean;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PatchStocksStockId404 = {
  /**
   * @type string
   */
  error: string;
};

export type PatchStocksStockIdMutationRequest = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  title?: string;
  /**
   * @minLength 0
   * @maxLength 9007199254740991
   * @type integer | undefined
   */
  qtde?: number;
  /**
   * @type boolean | undefined
   */
  full?: boolean;
};

export type PatchStocksStockIdMutationResponse = PatchStocksStockId200;

export type PatchStocksStockIdMutation = {
  Response: PatchStocksStockId200;
  Request: PatchStocksStockIdMutationRequest;
  PathParams: PatchStocksStockIdPathParams;
  Errors: PatchStocksStockId404;
};
