/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostProductsProductIdStocksPathParams = {
  /**
   * @type string, uuid
   */
  productId: string;
};

export const stockMarketplaceEnum4 = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type StockMarketplaceEnum4Key =
  (typeof stockMarketplaceEnum4)[keyof typeof stockMarketplaceEnum4];

/**
 * @description Default Response
 */
export type PostProductsProductIdStocks201 = {
  /**
   * @type object
   */
  stock: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @type string
     */
    title: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    qtde: number;
    /**
     * @type boolean
     */
    full: boolean;
    /**
     * @type string
     */
    marketplace: StockMarketplaceEnum4Key | null;
    /**
     * @type string, uuid
     */
    store_id: string | null;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PostProductsProductIdStocks404 = {
  /**
   * @type string
   */
  error: string;
};

export const postProductsProductIdStocksMutationRequestMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type PostProductsProductIdStocksMutationRequestMarketplaceEnumKey =
  (typeof postProductsProductIdStocksMutationRequestMarketplaceEnum)[keyof typeof postProductsProductIdStocksMutationRequestMarketplaceEnum];

export type PostProductsProductIdStocksMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 9007199254740991
   * @type integer
   */
  qtde: number;
  /**
   * @type boolean
   */
  full: boolean;
  /**
   * @type string
   */
  marketplace?: PostProductsProductIdStocksMutationRequestMarketplaceEnumKey | null;
  /**
   * @type string, uuid
   */
  store_id?: string | null;
};

export type PostProductsProductIdStocksMutationResponse =
  PostProductsProductIdStocks201;

export type PostProductsProductIdStocksMutation = {
  Response: PostProductsProductIdStocks201;
  Request: PostProductsProductIdStocksMutationRequest;
  PathParams: PostProductsProductIdStocksPathParams;
  Errors: PostProductsProductIdStocks404;
};
