/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const alertsMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type AlertsMarketplaceEnumKey =
  (typeof alertsMarketplaceEnum)[keyof typeof alertsMarketplaceEnum];

export const alertsSeverityEnum = {
  critico: "critico",
  atencao: "atencao",
} as const;

export type AlertsSeverityEnumKey =
  (typeof alertsSeverityEnum)[keyof typeof alertsSeverityEnum];

export const idleMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type IdleMarketplaceEnumKey =
  (typeof idleMarketplaceEnum)[keyof typeof idleMarketplaceEnum];

export const idleReasonEnum = {
  sem_venda: "sem_venda",
  excesso: "excesso",
  conta_secundaria: "conta_secundaria",
} as const;

export type IdleReasonEnumKey =
  (typeof idleReasonEnum)[keyof typeof idleReasonEnum];

/**
 * @description Default Response
 */
export type GetReportsFullReplenishmentAlerts200 = {
  /**
   * @type array
   */
  alerts: {
    /**
     * @type string
     */
    product_id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    brand_name: string | null;
    /**
     * @type string
     */
    stock_id: string;
    /**
     * @type string
     */
    stock_title: string;
    /**
     * @type string
     */
    marketplace: AlertsMarketplaceEnumKey;
    /**
     * @type number
     */
    available_qty: number;
    /**
     * @type number
     */
    in_transit_qty: number;
    /**
     * @type number
     */
    units_window: number;
    /**
     * @type number
     */
    demand_rate_per_day: number;
    /**
     * @type number
     */
    days_of_autonomy: number | null;
    /**
     * @type boolean
     */
    rate_is_estimated: boolean;
    /**
     * @type number
     */
    reorder_point_days: number;
    /**
     * @type string
     */
    severity: AlertsSeverityEnumKey;
    /**
     * @type number
     */
    suggested_quantity: number;
    /**
     * @type boolean
     */
    limited_by_physical_stock: boolean;
    /**
     * @type string
     */
    physical_stock_id: string | null;
    /**
     * @type string
     */
    physical_stock_title: string | null;
    /**
     * @type number
     */
    physical_available_qty: number;
  }[];
  /**
   * @type array
   */
  idle: {
    /**
     * @type string
     */
    product_id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    brand_name: string | null;
    /**
     * @type string
     */
    stock_id: string;
    /**
     * @type string
     */
    stock_title: string;
    /**
     * @type string
     */
    marketplace: IdleMarketplaceEnumKey;
    /**
     * @type number
     */
    qtde: number;
    /**
     * @type number
     */
    units_window: number;
    /**
     * @type number
     */
    days_of_autonomy: number | null;
    /**
     * @type number
     */
    max_days: number;
    /**
     * @type string
     */
    reason: IdleReasonEnumKey;
    /**
     * @type string
     */
    winner_stock_title: string | null;
  }[];
};

export type GetReportsFullReplenishmentAlertsQueryResponse =
  GetReportsFullReplenishmentAlerts200;

export type GetReportsFullReplenishmentAlertsQuery = {
  Response: GetReportsFullReplenishmentAlerts200;
  Errors: any;
};
