/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const alertsMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type AlertsMarketplaceEnumKey =
  (typeof alertsMarketplaceEnum)[keyof typeof alertsMarketplaceEnum];

export const alertsDemandSourceEnum = {
  deposito: "deposito",
  conta: "conta",
} as const;

export type AlertsDemandSourceEnumKey =
  (typeof alertsDemandSourceEnum)[keyof typeof alertsDemandSourceEnum];

export const alertsDemandTrendEnum = {
  acelerando: "acelerando",
  estavel: "estavel",
  desacelerando: "desacelerando",
} as const;

export type AlertsDemandTrendEnumKey =
  (typeof alertsDemandTrendEnum)[keyof typeof alertsDemandTrendEnum];

export const alertsSeverityEnum = {
  critico: "critico",
  atencao: "atencao",
} as const;

export type AlertsSeverityEnumKey =
  (typeof alertsSeverityEnum)[keyof typeof alertsSeverityEnum];

export const alertsShortfallReasonEnum = {
  sem_estoque_fisico: "sem_estoque_fisico",
  estoque_insuficiente: "estoque_insuficiente",
  reserva_venda_direta: "reserva_venda_direta",
  rascunho_pendente: "rascunho_pendente",
  dividido_entre_cds: "dividido_entre_cds",
} as const;

export type AlertsShortfallReasonEnumKey =
  (typeof alertsShortfallReasonEnum)[keyof typeof alertsShortfallReasonEnum];

export const idleMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type IdleMarketplaceEnumKey =
  (typeof idleMarketplaceEnum)[keyof typeof idleMarketplaceEnum];

export const idleReasonEnum = {
  sem_venda: "sem_venda",
  excesso: "excesso",
  conta_secundaria: "conta_secundaria",
} as const;

export type IdleReasonEnumKey =
  (typeof idleReasonEnum)[keyof typeof idleReasonEnum];

export const missingMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type MissingMarketplaceEnumKey =
  (typeof missingMarketplaceEnum)[keyof typeof missingMarketplaceEnum];

export const missingDemandTrendEnum = {
  acelerando: "acelerando",
  estavel: "estavel",
  desacelerando: "desacelerando",
} as const;

export type MissingDemandTrendEnumKey =
  (typeof missingDemandTrendEnum)[keyof typeof missingDemandTrendEnum];

/**
 * @description Default Response
 */
export type GetReportsFullReplenishmentAlerts200 = {
  /**
   * @type array
   */
  alerts: {
    /**
     * @type string
     */
    product_id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    brand_name: string | null;
    /**
     * @type string
     */
    stock_id: string;
    /**
     * @type string
     */
    stock_title: string;
    /**
     * @type string
     */
    store_id: string | null;
    /**
     * @type string
     */
    store_name: string | null;
    /**
     * @type string
     */
    marketplace: AlertsMarketplaceEnumKey;
    /**
     * @type number
     */
    available_qty: number;
    /**
     * @type number
     */
    in_transit_qty: number;
    /**
     * @type number
     */
    units_window: number;
    /**
     * @type number
     */
    demand_rate_per_day: number;
    /**
     * @type string
     */
    demand_source: AlertsDemandSourceEnumKey;
    /**
     * @type string
     */
    demand_trend: AlertsDemandTrendEnumKey;
    /**
     * @type number
     */
    account_units_long: number;
    /**
     * @type number
     */
    account_units_short: number;
    /**
     * @type number
     */
    days_of_autonomy: number | null;
    /**
     * @type boolean
     */
    rate_is_estimated: boolean;
    /**
     * @type number
     */
    reorder_point_days: number;
    /**
     * @type string
     */
    severity: AlertsSeverityEnumKey;
    /**
     * @type number
     */
    needed_quantity: number;
    /**
     * @type number
     */
    suggested_quantity: number;
    /**
     * @type array
     */
    sources: {
      /**
       * @type string
       */
      stock_id: string;
      /**
       * @type string
       */
      stock_title: string;
      /**
       * @type number
       */
      quantity: number;
    }[];
    /**
     * @type number
     */
    physical_total_qty: number;
    /**
     * @type number
     */
    physical_reserved_qty: number;
    /**
     * @type number
     */
    physical_committed_qty: number;
    /**
     * @type number
     */
    physical_available_qty: number;
    /**
     * @type string
     */
    shortfall_reason: AlertsShortfallReasonEnumKey | null;
  }[];
  /**
   * @type array
   */
  idle: {
    /**
     * @type string
     */
    product_id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    brand_name: string | null;
    /**
     * @type string
     */
    stock_id: string;
    /**
     * @type string
     */
    stock_title: string;
    /**
     * @type string
     */
    marketplace: IdleMarketplaceEnumKey;
    /**
     * @type number
     */
    qtde: number;
    /**
     * @type number
     */
    units_window: number;
    /**
     * @type number
     */
    days_of_autonomy: number | null;
    /**
     * @type number
     */
    max_days: number;
    /**
     * @type string
     */
    reason: IdleReasonEnumKey;
    /**
     * @type string
     */
    winner_stock_title: string | null;
  }[];
  /**
   * @type array
   */
  missing: {
    /**
     * @type string
     */
    product_id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    brand_name: string | null;
    /**
     * @type string
     */
    store_id: string;
    /**
     * @type string
     */
    store_name: string;
    /**
     * @type string
     */
    marketplace: MissingMarketplaceEnumKey;
    /**
     * @type number
     */
    account_units_long: number;
    /**
     * @type number
     */
    account_units_short: number;
    /**
     * @type number
     */
    demand_rate_per_day: number;
    /**
     * @type string
     */
    demand_trend: MissingDemandTrendEnumKey;
    /**
     * @type number
     */
    target_quantity: number;
    /**
     * @type number
     */
    physical_available_qty: number;
    /**
     * @type string
     */
    suggested_stock_title: string;
  }[];
};

export type GetReportsFullReplenishmentAlertsQueryResponse =
  GetReportsFullReplenishmentAlerts200;

export type GetReportsFullReplenishmentAlertsQuery = {
  Response: GetReportsFullReplenishmentAlerts200;
  Errors: any;
};
