/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetReportsAbcQueryParams = {
  /**
   * @type string, date-time
   */
  startDate: string;
  /**
   * @type string, date-time
   */
  endDate: string;
};

export const itemsClassEnum = {
  A: "A",
  B: "B",
  C: "C",
} as const;

export type ItemsClassEnumKey =
  (typeof itemsClassEnum)[keyof typeof itemsClassEnum];

/**
 * @description Default Response
 */
export type GetReportsAbc200 = {
  /**
   * @type array
   */
  stores: {
    /**
     * @type string
     */
    store_name: string;
    /**
     * @type number
     */
    total_revenue: number;
    /**
     * @type array
     */
    items: {
      /**
       * @type number
       */
      rank: number;
      /**
       * @type string
       */
      sku: string;
      /**
       * @type number
       */
      total_revenue: number;
      /**
       * @type number
       */
      qty_sales: number;
      /**
       * @type number
       */
      qty_units: number;
      /**
       * @type number
       */
      percentage: number;
      /**
       * @type number
       */
      cumulative_percentage: number;
      /**
       * @type string
       */
      class: ItemsClassEnumKey;
      /**
       * @type number
       */
      stock_qty: number;
      /**
       * @type number
       */
      units_90d: number;
      /**
       * @type number
       */
      coverage_percentage: number | null;
      /**
       * @type boolean
       */
      needs_purchase: boolean;
    }[];
  }[];
};

export type GetReportsAbcQueryResponse = GetReportsAbc200;

export type GetReportsAbcQuery = {
  Response: GetReportsAbc200;
  QueryParams: GetReportsAbcQueryParams;
  Errors: any;
};
