/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetReportsSalesQueryParams = {
  /**
   * @type string, date-time
   */
  startDate: string;
  /**
   * @type string, date-time
   */
  endDate: string;
};

/**
 * @description Default Response
 */
export type GetReportsSales200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @type string, date-time
     */
    sale_date: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    store_name: string | null;
    /**
     * @type string
     */
    channel: string;
    /**
     * @type string
     */
    stock_title: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    sale_price: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total_price: number;
  }[];
};

export type GetReportsSalesQueryResponse = GetReportsSales200;

export type GetReportsSalesQuery = {
  Response: GetReportsSales200;
  QueryParams: GetReportsSalesQueryParams;
  Errors: any;
};
