/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const itemsSeverityEnum = {
  critico: "critico",
  atencao: "atencao",
} as const;

export type ItemsSeverityEnumKey =
  (typeof itemsSeverityEnum)[keyof typeof itemsSeverityEnum];

export const itemsReasonsEnum = {
  perto_do_limite: "perto_do_limite",
  vendas_acelerando: "vendas_acelerando",
} as const;

export type ItemsReasonsEnumKey =
  (typeof itemsReasonsEnum)[keyof typeof itemsReasonsEnum];

/**
 * @description Default Response
 */
export type GetReportsRestockAlerts200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @type string
     */
    product_id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    brand_name: string | null;
    /**
     * @type number
     */
    physical_stock_qty: number;
    /**
     * @type number
     */
    units_15d: number;
    /**
     * @type number
     */
    units_30d: number;
    /**
     * @type number
     */
    coverage_percentage: number;
    /**
     * @type string
     */
    severity: ItemsSeverityEnumKey;
    /**
     * @type array
     */
    reasons: ItemsReasonsEnumKey[];
  }[];
};

export type GetReportsRestockAlertsQueryResponse = GetReportsRestockAlerts200;

export type GetReportsRestockAlertsQuery = {
  Response: GetReportsRestockAlerts200;
  Errors: any;
};
