/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetReportsStockByBrandQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  brandId?: string
  /**
   * @type string | undefined
   */
  noBrand?: string
}

/**
 * @description Default Response
 */
export type GetReportsStockByBrand200 = {
  /**
   * @type array
   */
  products: {
    /**
     * @type string, uuid
     */
    productId: string
    /**
     * @type string
     */
    sku: string
    /**
     * @type array
     */
    stocks: {
      /**
       * @type string, uuid
       */
      id: string
      /**
       * @type string
       */
      title: string
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number
    }[]
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total: number
  }[]
}

export type GetReportsStockByBrandQueryResponse = GetReportsStockByBrand200

export type GetReportsStockByBrandQuery = {
  Response: GetReportsStockByBrand200
  QueryParams: GetReportsStockByBrandQueryParams
  Errors: any
}
