/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getReportsStockByBrandQueryParamsNoBrandEnum = {
  true: "true",
} as const;

export type GetReportsStockByBrandQueryParamsNoBrandEnumKey =
  (typeof getReportsStockByBrandQueryParamsNoBrandEnum)[keyof typeof getReportsStockByBrandQueryParamsNoBrandEnum];

export type GetReportsStockByBrandQueryParams = {
  /**
   * @type string | undefined, uuid
   */
  brandId?: string;
  /**
   * @type string | undefined
   */
  noBrand?: GetReportsStockByBrandQueryParamsNoBrandEnumKey;
};

/**
 * @description Default Response
 */
export type GetReportsStockByBrand200 = {
  /**
   * @type array
   */
  products: {
    /**
     * @type string, uuid
     */
    productId: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total: number;
    /**
     * @type array
     */
    stocks: {
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number;
      /**
       * @type string
       */
      title: string;
      /**
       * @type string, uuid
       */
      id: string;
    }[];
    /**
     * @type string
     */
    sku: string;
  }[];
};

/**
 * @description Default Response
 */
export type GetReportsStockByBrand400 = {
  /**
   * @type string
   */
  error: string;
};

export type GetReportsStockByBrandQueryResponse = GetReportsStockByBrand200;

export type GetReportsStockByBrandQuery = {
  Response: GetReportsStockByBrand200;
  QueryParams: GetReportsStockByBrandQueryParams;
  Errors: GetReportsStockByBrand400;
};
