/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postReportsFullReplenishmentAlertsAnalyze200VerdictEnum = {
  antecipar: "antecipar",
  manter: "manter",
  segurar: "segurar",
} as const;

export type PostReportsFullReplenishmentAlertsAnalyze200VerdictEnumKey =
  (typeof postReportsFullReplenishmentAlertsAnalyze200VerdictEnum)[keyof typeof postReportsFullReplenishmentAlertsAnalyze200VerdictEnum];

/**
 * @description Default Response
 */
export type PostReportsFullReplenishmentAlertsAnalyze200 = {
  /**
   * @type string
   */
  verdict: PostReportsFullReplenishmentAlertsAnalyze200VerdictEnumKey;
  /**
   * @type number
   */
  seasonal_factor: number;
  /**
   * @type string
   */
  identity: string;
  /**
   * @type string
   */
  rationale: string;
  /**
   * @type string
   */
  critique: string | null;
  /**
   * @type array
   */
  sources: {
    /**
     * @type string
     */
    title: string;
    /**
     * @type string
     */
    url: string;
  }[];
  /**
   * @type boolean
   */
  grounded: boolean;
  /**
   * @type string
   */
  model: string;
  /**
   * @type string
   */
  analyzed_at: string;
  /**
   * @type number
   */
  suggested_quantity: number;
  /**
   * @type number
   */
  adjusted_quantity: number;
  /**
   * @type array
   */
  adjusted_sources: {
    /**
     * @type string
     */
    stock_id: string;
    /**
     * @type string
     */
    stock_title: string;
    /**
     * @type number
     */
    quantity: number;
  }[];
  /**
   * @type boolean
   */
  adjustment_capped: boolean;
  /**
   * @type boolean
   */
  stale: boolean;
  /**
   * @type boolean
   */
  from_cache: boolean;
};

/**
 * @description Default Response
 */
export type PostReportsFullReplenishmentAlertsAnalyze404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostReportsFullReplenishmentAlertsAnalyze501 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostReportsFullReplenishmentAlertsAnalyze502 = {
  /**
   * @type string
   */
  error: string;
};

export type PostReportsFullReplenishmentAlertsAnalyzeMutationRequest = {
  /**
   * @type string, uuid
   */
  product_id: string;
  /**
   * @type string, uuid
   */
  stock_id: string;
  /**
   * @default false
   * @type boolean | undefined
   */
  refresh?: boolean;
};

export type PostReportsFullReplenishmentAlertsAnalyzeMutationResponse =
  PostReportsFullReplenishmentAlertsAnalyze200;

export type PostReportsFullReplenishmentAlertsAnalyzeMutation = {
  Response: PostReportsFullReplenishmentAlertsAnalyze200;
  Request: PostReportsFullReplenishmentAlertsAnalyzeMutationRequest;
  Errors:
    | PostReportsFullReplenishmentAlertsAnalyze404
    | PostReportsFullReplenishmentAlertsAnalyze501
    | PostReportsFullReplenishmentAlertsAnalyze502;
};
