/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetNotificationsQueryResponse } from "../../types/notificationsController/GetNotifications.ts";

function getGetNotificationsUrl() {
  const res = { method: "GET", url: `/notifications` as const };
  return res;
}

/**
 * @description Notificações de alerta do sininho. Compara os alertas de agora com o último estado conhecido antes de listar, então uma transição causada pelo lançamento que acabou de acontecer já volta nesta resposta.
 * {@link /notifications}
 */
export async function getNotifications(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetNotificationsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetNotificationsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
