/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PatchNotificationsByIdReadMutationResponse,
  PatchNotificationsByIdReadPathParams,
  PatchNotificationsByIdRead404,
} from "../../types/notificationsController/PatchNotificationsByIdRead.ts";

function getPatchNotificationsByIdReadUrl(
  id: PatchNotificationsByIdReadPathParams["id"],
) {
  const res = { method: "PATCH", url: `/notifications/${id}/read` as const };
  return res;
}

/**
 * @description Marca uma notificação como lida. Uma já lida mantém a data original.
 * {@link /notifications/:id/read}
 */
export async function patchNotificationsByIdRead(
  id: PatchNotificationsByIdReadPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PatchNotificationsByIdReadMutationResponse,
    ResponseErrorConfig<PatchNotificationsByIdRead404>,
    unknown
  >({
    method: "PATCH",
    url: getPatchNotificationsByIdReadUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
