/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { PostNotificationsReadAllMutationResponse } from "../../types/notificationsController/PostNotificationsReadAll.ts";

function getPostNotificationsReadAllUrl() {
  const res = { method: "POST", url: `/notifications/read-all` as const };
  return res;
}

/**
 * @description Marca como lidas todas as notificações ainda não lidas.
 * {@link /notifications/read-all}
 */
export async function postNotificationsReadAll(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostNotificationsReadAllMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: getPostNotificationsReadAllUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
