/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetBrandsQueryResponse } from "../../types/brandsController/GetBrands.ts";

function getGetBrandsUrl() {
  const res = { method: "GET", url: `/brands` as const };
  return res;
}

/**
 * @description Lista todas as marcas
 * {@link /brands}
 */
export async function getBrands(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetBrandsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getGetBrandsUrl().url.toString(), ...requestConfig });
  return res.data;
}
