/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostBrandsMutationRequest,
  PostBrandsMutationResponse,
  PostBrands409,
} from "../../types/brandsController/PostBrands.ts";

function getPostBrandsUrl() {
  const res = { method: "POST", url: `/brands` as const };
  return res;
}

/**
 * @description Cria uma marca
 * {@link /brands}
 */
export async function postBrands(
  data: PostBrandsMutationRequest,
  config: Partial<RequestConfig<PostBrandsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostBrandsMutationResponse,
    ResponseErrorConfig<PostBrands409>,
    PostBrandsMutationRequest
  >({
    method: "POST",
    url: getPostBrandsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
