/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetReportsAbcQueryResponse,
  GetReportsAbcQueryParams,
} from "../../types/reportsController/GetReportsAbc.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getReportsAbc } from "../../clients/reportsController/getReportsAbc.ts";

export const getReportsAbcQueryKey = (params: GetReportsAbcQueryParams) =>
  [{ url: "/reports/abc" }, ...(params ? [params] : [])] as const;

export type GetReportsAbcQueryKey = ReturnType<typeof getReportsAbcQueryKey>;

export function getReportsAbcQueryOptions(
  params: GetReportsAbcQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getReportsAbcQueryKey(params);
  return queryOptions<
    GetReportsAbcQueryResponse,
    ResponseErrorConfig<Error>,
    GetReportsAbcQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      return getReportsAbc(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /reports/abc}
 */
export function useGetReportsAbc<
  TData = GetReportsAbcQueryResponse,
  TQueryData = GetReportsAbcQueryResponse,
  TQueryKey extends QueryKey = GetReportsAbcQueryKey,
>(
  params: GetReportsAbcQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetReportsAbcQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getReportsAbcQueryKey(params);

  const query = useQuery(
    {
      ...getReportsAbcQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
