/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetReportsStockByBrandQueryResponse, GetReportsStockByBrandQueryParams } from "../../types/reportsController/GetReportsStockByBrand.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getReportsStockByBrand } from "../../clients/reportsController/getReportsStockByBrand.ts";

export const getReportsStockByBrandQueryKey = (params?: GetReportsStockByBrandQueryParams) => [{ url: '/reports/stock-by-brand' }, ...(params ? [params] : [])] as const

export type GetReportsStockByBrandQueryKey = ReturnType<typeof getReportsStockByBrandQueryKey>

export function getReportsStockByBrandQueryOptions(params?: GetReportsStockByBrandQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getReportsStockByBrandQueryKey(params)
        return queryOptions<GetReportsStockByBrandQueryResponse, ResponseErrorConfig<Error>, GetReportsStockByBrandQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getReportsStockByBrand(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Retorna distribuição de estoque por produto de uma marca. Use brandId para uma marca específica ou noBrand=true para produtos sem marca.
 * {@link /reports/stock-by-brand}
 */
export function useGetReportsStockByBrand<TData = GetReportsStockByBrandQueryResponse, TQueryData = GetReportsStockByBrandQueryResponse, TQueryKey extends QueryKey = GetReportsStockByBrandQueryKey>(params?: GetReportsStockByBrandQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetReportsStockByBrandQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getReportsStockByBrandQueryKey(params)
         

         const query = useQuery({
          ...getReportsStockByBrandQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}