/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetReportsFullReplenishmentAlertsQueryResponse } from "../../types/reportsController/GetReportsFullReplenishmentAlerts.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getReportsFullReplenishmentAlerts } from "../../clients/reportsController/getReportsFullReplenishmentAlerts.ts";

export const getReportsFullReplenishmentAlertsQueryKey = () =>
  [{ url: "/reports/full-replenishment-alerts" }] as const;

export type GetReportsFullReplenishmentAlertsQueryKey = ReturnType<
  typeof getReportsFullReplenishmentAlertsQueryKey
>;

export function getReportsFullReplenishmentAlertsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getReportsFullReplenishmentAlertsQueryKey();
  return queryOptions<
    GetReportsFullReplenishmentAlertsQueryResponse,
    ResponseErrorConfig<Error>,
    GetReportsFullReplenishmentAlertsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getReportsFullReplenishmentAlerts({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Alerta de Abastecimento do Full: dias de autonomia por depósito full, quantidade sugerida, estoque parado e SKUs que a conta vende fora do full
 * {@link /reports/full-replenishment-alerts}
 */
export function useGetReportsFullReplenishmentAlerts<
  TData = GetReportsFullReplenishmentAlertsQueryResponse,
  TQueryData = GetReportsFullReplenishmentAlertsQueryResponse,
  TQueryKey extends QueryKey = GetReportsFullReplenishmentAlertsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetReportsFullReplenishmentAlertsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getReportsFullReplenishmentAlertsQueryKey();

  const query = useQuery(
    {
      ...getReportsFullReplenishmentAlertsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
