/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type {
  GetReportsAbcQueryResponse,
  GetReportsAbcQueryParams,
} from '../../types/reportsController/GetReportsAbc.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getReportsAbc } from '../../clients/reportsController/getReportsAbc.ts'

export const getReportsAbcSuspenseQueryKey = (
  params: GetReportsAbcQueryParams
) => [{ url: '/reports/abc' }, ...(params ? [params] : [])] as const

export type GetReportsAbcSuspenseQueryKey = ReturnType<
  typeof getReportsAbcSuspenseQueryKey
>

export function getReportsAbcSuspenseQueryOptions(
  params: GetReportsAbcQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getReportsAbcSuspenseQueryKey(params)
  return queryOptions<
    GetReportsAbcQueryResponse,
    ResponseErrorConfig<Error>,
    GetReportsAbcQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      return getReportsAbc(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /reports/abc}
 */
export function useGetReportsAbcSuspense<
  TData = GetReportsAbcQueryResponse,
  TQueryKey extends QueryKey = GetReportsAbcSuspenseQueryKey,
>(
  params: GetReportsAbcQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetReportsAbcQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getReportsAbcSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getReportsAbcSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
