/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetReportsRestockAlertsQueryResponse } from "../../types/reportsController/GetReportsRestockAlerts.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getReportsRestockAlerts } from "../../clients/reportsController/getReportsRestockAlerts.ts";

export const getReportsRestockAlertsQueryKey = () => [{ url: '/reports/restock-alerts' }] as const

export type GetReportsRestockAlertsQueryKey = ReturnType<typeof getReportsRestockAlertsQueryKey>

export function getReportsRestockAlertsQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getReportsRestockAlertsQueryKey()
        return queryOptions<GetReportsRestockAlertsQueryResponse, ResponseErrorConfig<Error>, GetReportsRestockAlertsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getReportsRestockAlerts({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /reports/restock-alerts}
 */
export function useGetReportsRestockAlerts<TData = GetReportsRestockAlertsQueryResponse, TQueryData = GetReportsRestockAlertsQueryResponse, TQueryKey extends QueryKey = GetReportsRestockAlertsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetReportsRestockAlertsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getReportsRestockAlertsQueryKey()
         

         const query = useQuery({
          ...getReportsRestockAlertsQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}