/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetReportsSalesQueryResponse, GetReportsSalesQueryParams } from "../../types/reportsController/GetReportsSales.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getReportsSales } from "../../clients/reportsController/getReportsSales.ts";

export const getReportsSalesSuspenseQueryKey = (params: GetReportsSalesQueryParams) => [{ url: '/reports/sales' }, ...(params ? [params] : [])] as const

export type GetReportsSalesSuspenseQueryKey = ReturnType<typeof getReportsSalesSuspenseQueryKey>

export function getReportsSalesSuspenseQueryOptions(params: GetReportsSalesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getReportsSalesSuspenseQueryKey(params)
        return queryOptions<GetReportsSalesQueryResponse, ResponseErrorConfig<Error>, GetReportsSalesQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            return getReportsSales(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Retorna relatório de vendas por período, sem paginação, com SKU, loja, canal, depósito e valor.
 * {@link /reports/sales}
 */
export function useGetReportsSalesSuspense<TData = GetReportsSalesQueryResponse, TQueryKey extends QueryKey = GetReportsSalesSuspenseQueryKey>(params: GetReportsSalesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetReportsSalesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getReportsSalesSuspenseQueryKey(params)
         

         const query = useSuspenseQuery({
          ...getReportsSalesSuspenseQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}