/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetReportsStockByBrandQueryResponse,
  GetReportsStockByBrandQueryParams,
  GetReportsStockByBrand400,
} from "../../types/reportsController/GetReportsStockByBrand.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getReportsStockByBrand } from "../../clients/reportsController/getReportsStockByBrand.ts";

export const getReportsStockByBrandSuspenseQueryKey = (
  params?: GetReportsStockByBrandQueryParams,
) => [{ url: "/reports/stock-by-brand" }, ...(params ? [params] : [])] as const;

export type GetReportsStockByBrandSuspenseQueryKey = ReturnType<
  typeof getReportsStockByBrandSuspenseQueryKey
>;

export function getReportsStockByBrandSuspenseQueryOptions(
  params?: GetReportsStockByBrandQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getReportsStockByBrandSuspenseQueryKey(params);
  return queryOptions<
    GetReportsStockByBrandQueryResponse,
    ResponseErrorConfig<GetReportsStockByBrand400>,
    GetReportsStockByBrandQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getReportsStockByBrand(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna distribuição de estoque por produto de uma marca. Use brandId para uma marca específica ou noBrand=true para produtos sem marca.
 * {@link /reports/stock-by-brand}
 */
export function useGetReportsStockByBrandSuspense<
  TData = GetReportsStockByBrandQueryResponse,
  TQueryKey extends QueryKey = GetReportsStockByBrandSuspenseQueryKey,
>(
  params?: GetReportsStockByBrandQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetReportsStockByBrandQueryResponse,
        ResponseErrorConfig<GetReportsStockByBrand400>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getReportsStockByBrandSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getReportsStockByBrandSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetReportsStockByBrand400>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
