/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { GetReportsFullReplenishmentAlertsQueryResponse } from "../../types/reportsController/GetReportsFullReplenishmentAlerts.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getReportsFullReplenishmentAlerts } from "../../clients/reportsController/getReportsFullReplenishmentAlerts.ts";

export const getReportsFullReplenishmentAlertsSuspenseQueryKey = () =>
  [{ url: "/reports/full-replenishment-alerts" }] as const;

export type GetReportsFullReplenishmentAlertsSuspenseQueryKey = ReturnType<
  typeof getReportsFullReplenishmentAlertsSuspenseQueryKey
>;

export function getReportsFullReplenishmentAlertsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getReportsFullReplenishmentAlertsSuspenseQueryKey();
  return queryOptions<
    GetReportsFullReplenishmentAlertsQueryResponse,
    ResponseErrorConfig<Error>,
    GetReportsFullReplenishmentAlertsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getReportsFullReplenishmentAlerts({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Alerta de Abastecimento do Full: dias de autonomia por depósito full, quantidade sugerida e estoque parado
 * {@link /reports/full-replenishment-alerts}
 */
export function useGetReportsFullReplenishmentAlertsSuspense<
  TData = GetReportsFullReplenishmentAlertsQueryResponse,
  TQueryKey extends QueryKey =
    GetReportsFullReplenishmentAlertsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetReportsFullReplenishmentAlertsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getReportsFullReplenishmentAlertsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getReportsFullReplenishmentAlertsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
