/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import type { GetReportsRestockAlertsQueryResponse } from "../../types/reportsController/GetReportsRestockAlerts.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getReportsRestockAlerts } from "../../clients/reportsController/getReportsRestockAlerts.ts";

export const getReportsRestockAlertsSuspenseQueryKey = () => [{ url: '/reports/restock-alerts' }] as const

export type GetReportsRestockAlertsSuspenseQueryKey = ReturnType<typeof getReportsRestockAlertsSuspenseQueryKey>

export function getReportsRestockAlertsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getReportsRestockAlertsSuspenseQueryKey()
        return queryOptions<GetReportsRestockAlertsQueryResponse, ResponseErrorConfig<Error>, GetReportsRestockAlertsQueryResponse, typeof queryKey>({
         
         queryKey,
         queryFn: async ({ signal }) => {
            return getReportsRestockAlerts({ ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * {@link /reports/restock-alerts}
 */
export function useGetReportsRestockAlertsSuspense<TData = GetReportsRestockAlertsQueryResponse, TQueryKey extends QueryKey = GetReportsRestockAlertsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetReportsRestockAlertsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getReportsRestockAlertsSuspenseQueryKey()
         

         const query = useSuspenseQuery({
          ...getReportsRestockAlertsSuspenseQueryOptions(config),
          ...resolvedOptions,
          queryKey,
         } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}