/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import type { GetReportsSalesQueryResponse, GetReportsSalesQueryParams } from "../../types/reportsController/GetReportsSales.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getReportsSales } from "../../clients/reportsController/getReportsSales.ts";

export const getReportsSalesQueryKey = (params: GetReportsSalesQueryParams) => [{ url: '/reports/sales' }, ...(params ? [params] : [])] as const

export type GetReportsSalesQueryKey = ReturnType<typeof getReportsSalesQueryKey>

export function getReportsSalesQueryOptions(params: GetReportsSalesQueryParams, config: Partial<RequestConfig> & { client?: Client } = {}) {

        const queryKey = getReportsSalesQueryKey(params)
        return queryOptions<GetReportsSalesQueryResponse, ResponseErrorConfig<Error>, GetReportsSalesQueryResponse, typeof queryKey>({
         enabled: !!(params),
         queryKey,
         queryFn: async ({ signal }) => {
            return getReportsSales(params, { ...config, signal: config.signal ?? signal })
         },
        })

}

/**
 * @description Retorna relatório de vendas por período, sem paginação, com SKU, loja, canal, depósito e valor.
 * {@link /reports/sales}
 */
export function useGetReportsSales<TData = GetReportsSalesQueryResponse, TQueryData = GetReportsSalesQueryResponse, TQueryKey extends QueryKey = GetReportsSalesQueryKey>(params: GetReportsSalesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetReportsSalesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client }
}
 = {}) {

         const { query: queryConfig = {}, client: config = {} } = options ?? {}
         const { client: queryClient, ...resolvedOptions } = queryConfig
         const queryKey = resolvedOptions?.queryKey ?? getReportsSalesQueryKey(params)
         

         const query = useQuery({
          ...getReportsSalesQueryOptions(params, config),
          ...resolvedOptions,
          queryKey,
         } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

         query.queryKey = queryKey as TQueryKey

         return query
         
}