/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostReportsFullReplenishmentAlertsAnalyzeMutationRequest, PostReportsFullReplenishmentAlertsAnalyzeMutationResponse, PostReportsFullReplenishmentAlertsAnalyze404, PostReportsFullReplenishmentAlertsAnalyze501, PostReportsFullReplenishmentAlertsAnalyze502 } from "../../types/reportsController/PostReportsFullReplenishmentAlertsAnalyze.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postReportsFullReplenishmentAlertsAnalyze } from "../../clients/reportsController/postReportsFullReplenishmentAlertsAnalyze.ts";

export const postReportsFullReplenishmentAlertsAnalyzeMutationKey = () => [{ url: '/reports/full-replenishment-alerts/analyze' }] as const

export type PostReportsFullReplenishmentAlertsAnalyzeMutationKey = ReturnType<typeof postReportsFullReplenishmentAlertsAnalyzeMutationKey>

export function postReportsFullReplenishmentAlertsAnalyzeMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostReportsFullReplenishmentAlertsAnalyzeMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postReportsFullReplenishmentAlertsAnalyzeMutationKey()
        return mutationOptions<PostReportsFullReplenishmentAlertsAnalyzeMutationResponse, ResponseErrorConfig<PostReportsFullReplenishmentAlertsAnalyze404 | PostReportsFullReplenishmentAlertsAnalyze501 | PostReportsFullReplenishmentAlertsAnalyze502>, {data: PostReportsFullReplenishmentAlertsAnalyzeMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postReportsFullReplenishmentAlertsAnalyze(data, config)
          },
        })

}

/**
 * @description Leitura crítica de uma linha do Abastecimento do Full: identifica o produto, pesa o calendário comercial e propõe um fator sazonal. A quantidade da regra continua sendo o padrão.
 * {@link /reports/full-replenishment-alerts/analyze}
 */
export function usePostReportsFullReplenishmentAlertsAnalyze<TContext>(options: 
{
  mutation?: UseMutationOptions<PostReportsFullReplenishmentAlertsAnalyzeMutationResponse, ResponseErrorConfig<PostReportsFullReplenishmentAlertsAnalyze404 | PostReportsFullReplenishmentAlertsAnalyze501 | PostReportsFullReplenishmentAlertsAnalyze502>, {data: PostReportsFullReplenishmentAlertsAnalyzeMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostReportsFullReplenishmentAlertsAnalyzeMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postReportsFullReplenishmentAlertsAnalyzeMutationKey()

          const baseOptions = postReportsFullReplenishmentAlertsAnalyzeMutationOptions(config) as UseMutationOptions<PostReportsFullReplenishmentAlertsAnalyzeMutationResponse, ResponseErrorConfig<PostReportsFullReplenishmentAlertsAnalyze404 | PostReportsFullReplenishmentAlertsAnalyze501 | PostReportsFullReplenishmentAlertsAnalyze502>, {data: PostReportsFullReplenishmentAlertsAnalyzeMutationRequest}, TContext>
          

          return useMutation<PostReportsFullReplenishmentAlertsAnalyzeMutationResponse, ResponseErrorConfig<PostReportsFullReplenishmentAlertsAnalyze404 | PostReportsFullReplenishmentAlertsAnalyze501 | PostReportsFullReplenishmentAlertsAnalyze502>, {data: PostReportsFullReplenishmentAlertsAnalyzeMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostReportsFullReplenishmentAlertsAnalyzeMutationResponse, ResponseErrorConfig<PostReportsFullReplenishmentAlertsAnalyze404 | PostReportsFullReplenishmentAlertsAnalyze501 | PostReportsFullReplenishmentAlertsAnalyze502>, {data: PostReportsFullReplenishmentAlertsAnalyzeMutationRequest}, TContext>
      
}