/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const summaryAnalysisSourceEnum = {
  gemini: "gemini",
  fallback: "fallback",
} as const;

export type SummaryAnalysisSourceEnumKey =
  (typeof summaryAnalysisSourceEnum)[keyof typeof summaryAnalysisSourceEnum];

export const itemsConfidenceEnum = {
  high: "high",
  medium: "medium",
  low: "low",
} as const;

export type ItemsConfidenceEnumKey =
  (typeof itemsConfidenceEnum)[keyof typeof itemsConfidenceEnum];

export const itemsAnalysisSourceEnum = {
  gemini: "gemini",
  fallback: "fallback",
} as const;

export type ItemsAnalysisSourceEnumKey =
  (typeof itemsAnalysisSourceEnum)[keyof typeof itemsAnalysisSourceEnum];

/**
 * @description Default Response
 */
export type PostFbaAnalyze200 = {
  /**
   * @type object
   */
  summary: {
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total_rows: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    analyzed_items: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    pending_items: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total_recommended_units: number;
    /**
     * @type string
     */
    top_sku_by_recommendation: string | null;
    /**
     * @type string
     */
    analysis_source: SummaryAnalysisSourceEnumKey;
  };
  /**
   * @type array
   */
  items: {
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    asin: string;
    /**
     * @type string
     */
    title: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    physical_stock: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    units_sold_90d: number;
    /**
     * @type number
     */
    conversion_rate: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    recommended_send_quantity: number;
    /**
     * @type string
     */
    confidence: ItemsConfidenceEnumKey;
    /**
     * @type array
     */
    decision_tags: string[];
    /**
     * @type string
     */
    analysis_source: ItemsAnalysisSourceEnumKey;
    /**
     * @type string
     */
    reason: string;
  }[];
  /**
   * @type array
   */
  pending_items: {
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    title: string;
    /**
     * @type string
     */
    reason: string;
    /**
     * @type string
     */
    detail: string;
  }[];
};

/**
 * @description Default Response
 */
export type PostFbaAnalyze400 = {
  /**
   * @type string
   */
  error: string;
};

export type PostFbaAnalyzeMutationRequest = {
  /**
   * @minLength 1
   * @type string
   */
  csv_content: string;
};

export type PostFbaAnalyzeMutationResponse = PostFbaAnalyze200;

export type PostFbaAnalyzeMutation = {
  Response: PostFbaAnalyze200;
  Request: PostFbaAnalyzeMutationRequest;
  Errors: PostFbaAnalyze400;
};
