/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostShipmentsByIdDispatchMutationResponse,
  PostShipmentsByIdDispatchPathParams,
  PostShipmentsByIdDispatch404,
  PostShipmentsByIdDispatch409,
  PostShipmentsByIdDispatch422,
} from "../../types/shipmentsController/PostShipmentsByIdDispatch.ts";

function getPostShipmentsByIdDispatchUrl(
  id: PostShipmentsByIdDispatchPathParams["id"],
) {
  const res = { method: "POST", url: `/shipments/${id}/dispatch` as const };
  return res;
}

/**
 * @description Despacha o envio: debita o estoque de origem e marca como em trânsito
 * {@link /shipments/:id/dispatch}
 */
export async function postShipmentsByIdDispatch(
  id: PostShipmentsByIdDispatchPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostShipmentsByIdDispatchMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdDispatch404
      | PostShipmentsByIdDispatch409
      | PostShipmentsByIdDispatch422
    >,
    unknown
  >({
    method: "POST",
    url: getPostShipmentsByIdDispatchUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
