/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostShipmentsByIdConfirmMutationResponse,
  PostShipmentsByIdConfirmPathParams,
  PostShipmentsByIdConfirm404,
  PostShipmentsByIdConfirm409,
  PostShipmentsByIdConfirm422,
} from "../../types/shipmentsController/PostShipmentsByIdConfirm.ts";

function getPostShipmentsByIdConfirmUrl(
  id: PostShipmentsByIdConfirmPathParams["id"],
) {
  const res = { method: "POST", url: `/shipments/${id}/confirm` as const };
  return res;
}

/**
 * {@link /shipments/:id/confirm}
 */
export async function postShipmentsByIdConfirm(
  id: PostShipmentsByIdConfirmPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostShipmentsByIdConfirmMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdConfirm404
      | PostShipmentsByIdConfirm409
      | PostShipmentsByIdConfirm422
    >,
    unknown
  >({
    method: "POST",
    url: getPostShipmentsByIdConfirmUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
