/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostShipmentsByIdReceiveMutationResponse,
  PostShipmentsByIdReceivePathParams,
  PostShipmentsByIdReceive404,
  PostShipmentsByIdReceive409,
} from "../../types/shipmentsController/PostShipmentsByIdReceive.ts";

function getPostShipmentsByIdReceiveUrl(
  id: PostShipmentsByIdReceivePathParams["id"],
) {
  const res = { method: "POST", url: `/shipments/${id}/receive` as const };
  return res;
}

/**
 * @description Confirma a entrada no centro de distribuição: credita o estoque full de destino
 * {@link /shipments/:id/receive}
 */
export async function postShipmentsByIdReceive(
  id: PostShipmentsByIdReceivePathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostShipmentsByIdReceiveMutationResponse,
    ResponseErrorConfig<
      PostShipmentsByIdReceive404 | PostShipmentsByIdReceive409
    >,
    unknown
  >({
    method: "POST",
    url: getPostShipmentsByIdReceiveUrl(id).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
