/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetStoresQueryResponse } from "../../types/storesController/GetStores.ts";

function getGetStoresUrl() {
  const res = { method: "GET", url: `/stores` as const };
  return res;
}

/**
 * @description Lista todas as lojas
 * {@link /stores}
 */
export async function getStores(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetStoresQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: getGetStoresUrl().url.toString(), ...requestConfig });
  return res.data;
}
