/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  GetSalesQueryResponse,
  GetSalesQueryParams,
} from '../../types/salesController/GetSales.ts'

function getGetSalesUrl() {
  const res = { method: 'GET', url: `/sales` as const }
  return res
}

/**
 * @description Lista vendas com filtros por período
 * {@link /sales}
 */
export async function getSales(
  params?: GetSalesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetSalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetSalesUrl().url.toString(),
    params,
    ...requestConfig,
  })
  return res.data
}
