/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostSalesMutationRequest,
  PostSalesMutationResponse,
  PostSales400,
  PostSales404,
} from "../../types/salesController/PostSales.ts";

function getPostSalesUrl() {
  const res = { method: "POST", url: `/sales` as const };
  return res;
}

/**
 * @description Cria uma venda com baixa automática no estoque
 * {@link /sales}
 */
export async function postSales(
  data: PostSalesMutationRequest,
  config: Partial<RequestConfig<PostSalesMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostSalesMutationResponse,
    ResponseErrorConfig<PostSales400 | PostSales404>,
    PostSalesMutationRequest
  >({
    method: "POST",
    url: getPostSalesUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
