/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetDashboardLast15DaysSalesQueryResponse } from "../../types/dashboardController/GetDashboardLast15DaysSales.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDashboardLast15DaysSales } from "../../clients/dashboardController/getDashboardLast15DaysSales.ts";

export const getDashboardLast15DaysSalesQueryKey = () =>
  [{ url: "/dashboard/last-15-days-sales" }] as const;

export type GetDashboardLast15DaysSalesQueryKey = ReturnType<
  typeof getDashboardLast15DaysSalesQueryKey
>;

export function getDashboardLast15DaysSalesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDashboardLast15DaysSalesQueryKey();
  return queryOptions<
    GetDashboardLast15DaysSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardLast15DaysSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardLast15DaysSales({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna faturamento diario dos ultimos 15 dias com media diaria
 * {@link /dashboard/last-15-days-sales}
 */
export function useGetDashboardLast15DaysSales<
  TData = GetDashboardLast15DaysSalesQueryResponse,
  TQueryData = GetDashboardLast15DaysSalesQueryResponse,
  TQueryKey extends QueryKey = GetDashboardLast15DaysSalesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDashboardLast15DaysSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getDashboardLast15DaysSalesQueryKey();

  const query = useQuery(
    {
      ...getDashboardLast15DaysSalesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
