/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetDashboardCurrentMonthSalesQueryResponse } from "../../types/dashboardController/GetDashboardCurrentMonthSales.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDashboardCurrentMonthSales } from "../../clients/dashboardController/getDashboardCurrentMonthSales.ts";

export const getDashboardCurrentMonthSalesQueryKey = () =>
  [{ url: "/dashboard/current-month-sales" }] as const;

export type GetDashboardCurrentMonthSalesQueryKey = ReturnType<
  typeof getDashboardCurrentMonthSalesQueryKey
>;

export function getDashboardCurrentMonthSalesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDashboardCurrentMonthSalesQueryKey();
  return queryOptions<
    GetDashboardCurrentMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardCurrentMonthSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardCurrentMonthSales({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna o total de vendas do mes atual em centavos
 * {@link /dashboard/current-month-sales}
 */
export function useGetDashboardCurrentMonthSales<
  TData = GetDashboardCurrentMonthSalesQueryResponse,
  TQueryData = GetDashboardCurrentMonthSalesQueryResponse,
  TQueryKey extends QueryKey = GetDashboardCurrentMonthSalesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDashboardCurrentMonthSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getDashboardCurrentMonthSalesQueryKey();

  const query = useQuery(
    {
      ...getDashboardCurrentMonthSalesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
