/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetDashboardMonthlySalesPaceQueryResponse } from "../../types/dashboardController/GetDashboardMonthlySalesPace.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDashboardMonthlySalesPace } from "../../clients/dashboardController/getDashboardMonthlySalesPace.ts";

export const getDashboardMonthlySalesPaceQueryKey = () =>
  [{ url: "/dashboard/monthly-sales-pace" }] as const;

export type GetDashboardMonthlySalesPaceQueryKey = ReturnType<
  typeof getDashboardMonthlySalesPaceQueryKey
>;

export function getDashboardMonthlySalesPaceQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDashboardMonthlySalesPaceQueryKey();
  return queryOptions<
    GetDashboardMonthlySalesPaceQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardMonthlySalesPaceQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardMonthlySalesPace({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna faturamento acumulado por dia do mes, comparando o mes atual com o mes passado
 * {@link /dashboard/monthly-sales-pace}
 */
export function useGetDashboardMonthlySalesPace<
  TData = GetDashboardMonthlySalesPaceQueryResponse,
  TQueryData = GetDashboardMonthlySalesPaceQueryResponse,
  TQueryKey extends QueryKey = GetDashboardMonthlySalesPaceQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDashboardMonthlySalesPaceQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getDashboardMonthlySalesPaceQueryKey();

  const query = useQuery(
    {
      ...getDashboardMonthlySalesPaceQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
