/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { GetDashboardCurrentMonthSalesQueryResponse } from "../../types/dashboardController/GetDashboardCurrentMonthSales.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getDashboardCurrentMonthSales } from "../../clients/dashboardController/getDashboardCurrentMonthSales.ts";

export const getDashboardCurrentMonthSalesSuspenseQueryKey = () =>
  [{ url: "/dashboard/current-month-sales" }] as const;

export type GetDashboardCurrentMonthSalesSuspenseQueryKey = ReturnType<
  typeof getDashboardCurrentMonthSalesSuspenseQueryKey
>;

export function getDashboardCurrentMonthSalesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDashboardCurrentMonthSalesSuspenseQueryKey();
  return queryOptions<
    GetDashboardCurrentMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardCurrentMonthSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardCurrentMonthSales({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna o total de vendas do mes atual em centavos
 * {@link /dashboard/current-month-sales}
 */
export function useGetDashboardCurrentMonthSalesSuspense<
  TData = GetDashboardCurrentMonthSalesQueryResponse,
  TQueryKey extends QueryKey = GetDashboardCurrentMonthSalesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetDashboardCurrentMonthSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getDashboardCurrentMonthSalesSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getDashboardCurrentMonthSalesSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
