/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type { GetDashboardLastMonthSalesQueryResponse } from '../../types/dashboardController/GetDashboardLastMonthSales.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getDashboardLastMonthSales } from '../../clients/dashboardController/getDashboardLastMonthSales.ts'

export const getDashboardLastMonthSalesQueryKey = () =>
  [{ url: '/dashboard/last-month-sales' }] as const

export type GetDashboardLastMonthSalesQueryKey = ReturnType<
  typeof getDashboardLastMonthSalesQueryKey
>

export function getDashboardLastMonthSalesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getDashboardLastMonthSalesQueryKey()
  return queryOptions<
    GetDashboardLastMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardLastMonthSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardLastMonthSales({
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Retorna o total de vendas do mes passado em centavos
 * {@link /dashboard/last-month-sales}
 */
export function useGetDashboardLastMonthSales<
  TData = GetDashboardLastMonthSalesQueryResponse,
  TQueryData = GetDashboardLastMonthSalesQueryResponse,
  TQueryKey extends QueryKey = GetDashboardLastMonthSalesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDashboardLastMonthSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getDashboardLastMonthSalesQueryKey()

  const query = useQuery(
    {
      ...getDashboardLastMonthSalesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
