/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type { GetDashboardMonthlySalesQueryResponse } from '../../types/dashboardController/GetDashboardMonthlySales.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getDashboardMonthlySales } from '../../clients/dashboardController/getDashboardMonthlySales.ts'

export const getDashboardMonthlySalesSuspenseQueryKey = () =>
  [{ url: '/dashboard/monthly-sales' }] as const

export type GetDashboardMonthlySalesSuspenseQueryKey = ReturnType<
  typeof getDashboardMonthlySalesSuspenseQueryKey
>

export function getDashboardMonthlySalesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getDashboardMonthlySalesSuspenseQueryKey()
  return queryOptions<
    GetDashboardMonthlySalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardMonthlySalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardMonthlySales({
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Retorna faturamento diario do mes atual com media diaria
 * {@link /dashboard/monthly-sales}
 */
export function useGetDashboardMonthlySalesSuspense<
  TData = GetDashboardMonthlySalesQueryResponse,
  TQueryKey extends QueryKey = GetDashboardMonthlySalesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetDashboardMonthlySalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getDashboardMonthlySalesSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getDashboardMonthlySalesSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
