/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type { GetDashboardLastMonthSalesQueryResponse } from '../../types/dashboardController/GetDashboardLastMonthSales.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getDashboardLastMonthSales } from '../../clients/dashboardController/getDashboardLastMonthSales.ts'

export const getDashboardLastMonthSalesSuspenseQueryKey = () =>
  [{ url: '/dashboard/last-month-sales' }] as const

export type GetDashboardLastMonthSalesSuspenseQueryKey = ReturnType<
  typeof getDashboardLastMonthSalesSuspenseQueryKey
>

export function getDashboardLastMonthSalesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getDashboardLastMonthSalesSuspenseQueryKey()
  return queryOptions<
    GetDashboardLastMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetDashboardLastMonthSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getDashboardLastMonthSales({
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Retorna o total de vendas do mes passado em centavos
 * {@link /dashboard/last-month-sales}
 */
export function useGetDashboardLastMonthSalesSuspense<
  TData = GetDashboardLastMonthSalesQueryResponse,
  TQueryKey extends QueryKey = GetDashboardLastMonthSalesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetDashboardLastMonthSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getDashboardLastMonthSalesSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getDashboardLastMonthSalesSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
