/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type { PostNotificationsReadAllMutationResponse } from "../../types/notificationsController/PostNotificationsReadAll.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postNotificationsReadAll } from "../../clients/notificationsController/postNotificationsReadAll.ts";

export const postNotificationsReadAllMutationKey = () =>
  [{ url: "/notifications/read-all" }] as const;

export type PostNotificationsReadAllMutationKey = ReturnType<
  typeof postNotificationsReadAllMutationKey
>;

export function postNotificationsReadAllMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postNotificationsReadAllMutationKey();
  return mutationOptions<
    PostNotificationsReadAllMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return postNotificationsReadAll(config);
    },
  });
}

/**
 * @description Marca como lidas todas as notificações ainda não lidas.
 * {@link /notifications/read-all}
 */
export function usePostNotificationsReadAll<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostNotificationsReadAllMutationResponse,
      ResponseErrorConfig<Error>,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postNotificationsReadAllMutationKey();

  const baseOptions = postNotificationsReadAllMutationOptions(
    config,
  ) as UseMutationOptions<
    PostNotificationsReadAllMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;

  return useMutation<
    PostNotificationsReadAllMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostNotificationsReadAllMutationResponse,
    ResponseErrorConfig<Error>,
    void,
    TContext
  >;
}
