/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PatchNotificationsByIdReadMutationResponse,
  PatchNotificationsByIdReadPathParams,
  PatchNotificationsByIdRead404,
} from "../../types/notificationsController/PatchNotificationsByIdRead.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { patchNotificationsByIdRead } from "../../clients/notificationsController/patchNotificationsByIdRead.ts";

export const patchNotificationsByIdReadMutationKey = () =>
  [{ url: "/notifications/:id/read" }] as const;

export type PatchNotificationsByIdReadMutationKey = ReturnType<
  typeof patchNotificationsByIdReadMutationKey
>;

export function patchNotificationsByIdReadMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = patchNotificationsByIdReadMutationKey();
  return mutationOptions<
    PatchNotificationsByIdReadMutationResponse,
    ResponseErrorConfig<PatchNotificationsByIdRead404>,
    { id: PatchNotificationsByIdReadPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return patchNotificationsByIdRead(id, config);
    },
  });
}

/**
 * @description Marca uma notificação como lida. Uma já lida mantém a data original.
 * {@link /notifications/:id/read}
 */
export function usePatchNotificationsByIdRead<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchNotificationsByIdReadMutationResponse,
      ResponseErrorConfig<PatchNotificationsByIdRead404>,
      { id: PatchNotificationsByIdReadPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchNotificationsByIdReadMutationKey();

  const baseOptions = patchNotificationsByIdReadMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchNotificationsByIdReadMutationResponse,
    ResponseErrorConfig<PatchNotificationsByIdRead404>,
    { id: PatchNotificationsByIdReadPathParams["id"] },
    TContext
  >;

  return useMutation<
    PatchNotificationsByIdReadMutationResponse,
    ResponseErrorConfig<PatchNotificationsByIdRead404>,
    { id: PatchNotificationsByIdReadPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchNotificationsByIdReadMutationResponse,
    ResponseErrorConfig<PatchNotificationsByIdRead404>,
    { id: PatchNotificationsByIdReadPathParams["id"] },
    TContext
  >;
}
