/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  DeleteShipmentsByIdMutationResponse,
  DeleteShipmentsByIdPathParams,
  DeleteShipmentsById404,
  DeleteShipmentsById409,
} from "../../types/shipmentsController/DeleteShipmentsById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteShipmentsById } from "../../clients/shipmentsController/deleteShipmentsById.ts";

export const deleteShipmentsByIdMutationKey = () =>
  [{ url: "/shipments/:id" }] as const;

export type DeleteShipmentsByIdMutationKey = ReturnType<
  typeof deleteShipmentsByIdMutationKey
>;

export function deleteShipmentsByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteShipmentsByIdMutationKey();
  return mutationOptions<
    DeleteShipmentsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentsById404 | DeleteShipmentsById409>,
    { id: DeleteShipmentsByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteShipmentsById(id, config);
    },
  });
}

/**
 * {@link /shipments/:id}
 */
export function useDeleteShipmentsById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteShipmentsByIdMutationResponse,
      ResponseErrorConfig<DeleteShipmentsById404 | DeleteShipmentsById409>,
      { id: DeleteShipmentsByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteShipmentsByIdMutationKey();

  const baseOptions = deleteShipmentsByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteShipmentsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentsById404 | DeleteShipmentsById409>,
    { id: DeleteShipmentsByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteShipmentsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentsById404 | DeleteShipmentsById409>,
    { id: DeleteShipmentsByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteShipmentsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentsById404 | DeleteShipmentsById409>,
    { id: DeleteShipmentsByIdPathParams["id"] },
    TContext
  >;
}
