/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetShipmentsQueryResponse } from "../../types/shipmentsController/GetShipments.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getShipments } from "../../clients/shipmentsController/getShipments.ts";

export const getShipmentsQueryKey = () => [{ url: "/shipments" }] as const;

export type GetShipmentsQueryKey = ReturnType<typeof getShipmentsQueryKey>;

export function getShipmentsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getShipmentsQueryKey();
  return queryOptions<
    GetShipmentsQueryResponse,
    ResponseErrorConfig<Error>,
    GetShipmentsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getShipments({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * {@link /shipments}
 */
export function useGetShipments<
  TData = GetShipmentsQueryResponse,
  TQueryData = GetShipmentsQueryResponse,
  TQueryKey extends QueryKey = GetShipmentsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetShipmentsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getShipmentsQueryKey();

  const query = useQuery(
    {
      ...getShipmentsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
