/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type {
  GetShipmentsByIdQueryResponse,
  GetShipmentsByIdPathParams,
  GetShipmentsById404,
} from '../../types/shipmentsController/GetShipmentsById.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getShipmentsById } from '../../clients/shipmentsController/getShipmentsById.ts'

export const getShipmentsByIdQueryKey = (
  id: GetShipmentsByIdPathParams['id']
) => [{ url: '/shipments/:id', params: { id: id } }] as const

export type GetShipmentsByIdQueryKey = ReturnType<
  typeof getShipmentsByIdQueryKey
>

export function getShipmentsByIdQueryOptions(
  id: GetShipmentsByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getShipmentsByIdQueryKey(id)
  return queryOptions<
    GetShipmentsByIdQueryResponse,
    ResponseErrorConfig<GetShipmentsById404>,
    GetShipmentsByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getShipmentsById(id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /shipments/:id}
 */
export function useGetShipmentsById<
  TData = GetShipmentsByIdQueryResponse,
  TQueryData = GetShipmentsByIdQueryResponse,
  TQueryKey extends QueryKey = GetShipmentsByIdQueryKey,
>(
  id: GetShipmentsByIdPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetShipmentsByIdQueryResponse,
        ResponseErrorConfig<GetShipmentsById404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getShipmentsByIdQueryKey(id)

  const query = useQuery(
    {
      ...getShipmentsByIdQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<GetShipmentsById404>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
