/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type {
  GetShipmentsByIdQueryResponse,
  GetShipmentsByIdPathParams,
  GetShipmentsById404,
} from '../../types/shipmentsController/GetShipmentsById.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getShipmentsById } from '../../clients/shipmentsController/getShipmentsById.ts'

export const getShipmentsByIdSuspenseQueryKey = (
  id: GetShipmentsByIdPathParams['id']
) => [{ url: '/shipments/:id', params: { id: id } }] as const

export type GetShipmentsByIdSuspenseQueryKey = ReturnType<
  typeof getShipmentsByIdSuspenseQueryKey
>

export function getShipmentsByIdSuspenseQueryOptions(
  id: GetShipmentsByIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getShipmentsByIdSuspenseQueryKey(id)
  return queryOptions<
    GetShipmentsByIdQueryResponse,
    ResponseErrorConfig<GetShipmentsById404>,
    GetShipmentsByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getShipmentsById(id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /shipments/:id}
 */
export function useGetShipmentsByIdSuspense<
  TData = GetShipmentsByIdQueryResponse,
  TQueryKey extends QueryKey = GetShipmentsByIdSuspenseQueryKey,
>(
  id: GetShipmentsByIdPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetShipmentsByIdQueryResponse,
        ResponseErrorConfig<GetShipmentsById404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getShipmentsByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...getShipmentsByIdSuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetShipmentsById404>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
