/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type { GetShipmentsQueryResponse } from '../../types/shipmentsController/GetShipments.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getShipments } from '../../clients/shipmentsController/getShipments.ts'

export const getShipmentsSuspenseQueryKey = () =>
  [{ url: '/shipments' }] as const

export type GetShipmentsSuspenseQueryKey = ReturnType<
  typeof getShipmentsSuspenseQueryKey
>

export function getShipmentsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getShipmentsSuspenseQueryKey()
  return queryOptions<
    GetShipmentsQueryResponse,
    ResponseErrorConfig<Error>,
    GetShipmentsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getShipments({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /shipments}
 */
export function useGetShipmentsSuspense<
  TData = GetShipmentsQueryResponse,
  TQueryKey extends QueryKey = GetShipmentsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetShipmentsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getShipmentsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getShipmentsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
