/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PutShipmentsByIdMutationRequest,
  PutShipmentsByIdMutationResponse,
  PutShipmentsByIdPathParams,
  PutShipmentsById404,
  PutShipmentsById409,
} from '../../types/shipmentsController/PutShipmentsById.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { putShipmentsById } from '../../clients/shipmentsController/putShipmentsById.ts'

export const putShipmentsByIdMutationKey = () =>
  [{ url: '/shipments/:id' }] as const

export type PutShipmentsByIdMutationKey = ReturnType<
  typeof putShipmentsByIdMutationKey
>

export function putShipmentsByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PutShipmentsByIdMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = putShipmentsByIdMutationKey()
  return mutationOptions<
    PutShipmentsByIdMutationResponse,
    ResponseErrorConfig<PutShipmentsById404 | PutShipmentsById409>,
    {
      id: PutShipmentsByIdPathParams['id']
      data: PutShipmentsByIdMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return putShipmentsById(id, data, config)
    },
  })
}

/**
 * {@link /shipments/:id}
 */
export function usePutShipmentsById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PutShipmentsByIdMutationResponse,
      ResponseErrorConfig<PutShipmentsById404 | PutShipmentsById409>,
      {
        id: PutShipmentsByIdPathParams['id']
        data: PutShipmentsByIdMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PutShipmentsByIdMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? putShipmentsByIdMutationKey()

  const baseOptions = putShipmentsByIdMutationOptions(
    config
  ) as UseMutationOptions<
    PutShipmentsByIdMutationResponse,
    ResponseErrorConfig<PutShipmentsById404 | PutShipmentsById409>,
    {
      id: PutShipmentsByIdPathParams['id']
      data: PutShipmentsByIdMutationRequest
    },
    TContext
  >

  return useMutation<
    PutShipmentsByIdMutationResponse,
    ResponseErrorConfig<PutShipmentsById404 | PutShipmentsById409>,
    {
      id: PutShipmentsByIdPathParams['id']
      data: PutShipmentsByIdMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PutShipmentsByIdMutationResponse,
    ResponseErrorConfig<PutShipmentsById404 | PutShipmentsById409>,
    {
      id: PutShipmentsByIdPathParams['id']
      data: PutShipmentsByIdMutationRequest
    },
    TContext
  >
}
