/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PostShipmentsMutationRequest,
  PostShipmentsMutationResponse,
  PostShipments404,
} from '../../types/shipmentsController/PostShipments.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { postShipments } from '../../clients/shipmentsController/postShipments.ts'

export const postShipmentsMutationKey = () => [{ url: '/shipments' }] as const

export type PostShipmentsMutationKey = ReturnType<
  typeof postShipmentsMutationKey
>

export function postShipmentsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostShipmentsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postShipmentsMutationKey()
  return mutationOptions<
    PostShipmentsMutationResponse,
    ResponseErrorConfig<PostShipments404>,
    { data: PostShipmentsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postShipments(data, config)
    },
  })
}

/**
 * {@link /shipments}
 */
export function usePostShipments<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostShipmentsMutationResponse,
      ResponseErrorConfig<PostShipments404>,
      { data: PostShipmentsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostShipmentsMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postShipmentsMutationKey()

  const baseOptions = postShipmentsMutationOptions(
    config
  ) as UseMutationOptions<
    PostShipmentsMutationResponse,
    ResponseErrorConfig<PostShipments404>,
    { data: PostShipmentsMutationRequest },
    TContext
  >

  return useMutation<
    PostShipmentsMutationResponse,
    ResponseErrorConfig<PostShipments404>,
    { data: PostShipmentsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostShipmentsMutationResponse,
    ResponseErrorConfig<PostShipments404>,
    { data: PostShipmentsMutationRequest },
    TContext
  >
}
