/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostShipmentsByIdConfirmMutationResponse,
  PostShipmentsByIdConfirmPathParams,
  PostShipmentsByIdConfirm404,
  PostShipmentsByIdConfirm409,
  PostShipmentsByIdConfirm422,
} from "../../types/shipmentsController/PostShipmentsByIdConfirm.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postShipmentsByIdConfirm } from "../../clients/shipmentsController/postShipmentsByIdConfirm.ts";

export const postShipmentsByIdConfirmMutationKey = () =>
  [{ url: "/shipments/:id/confirm" }] as const;

export type PostShipmentsByIdConfirmMutationKey = ReturnType<
  typeof postShipmentsByIdConfirmMutationKey
>;

export function postShipmentsByIdConfirmMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postShipmentsByIdConfirmMutationKey();
  return mutationOptions<
    PostShipmentsByIdConfirmMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdConfirm404
      | PostShipmentsByIdConfirm409
      | PostShipmentsByIdConfirm422
    >,
    { id: PostShipmentsByIdConfirmPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postShipmentsByIdConfirm(id, config);
    },
  });
}

/**
 * {@link /shipments/:id/confirm}
 */
export function usePostShipmentsByIdConfirm<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostShipmentsByIdConfirmMutationResponse,
      ResponseErrorConfig<
        | PostShipmentsByIdConfirm404
        | PostShipmentsByIdConfirm409
        | PostShipmentsByIdConfirm422
      >,
      { id: PostShipmentsByIdConfirmPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postShipmentsByIdConfirmMutationKey();

  const baseOptions = postShipmentsByIdConfirmMutationOptions(
    config,
  ) as UseMutationOptions<
    PostShipmentsByIdConfirmMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdConfirm404
      | PostShipmentsByIdConfirm409
      | PostShipmentsByIdConfirm422
    >,
    { id: PostShipmentsByIdConfirmPathParams["id"] },
    TContext
  >;

  return useMutation<
    PostShipmentsByIdConfirmMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdConfirm404
      | PostShipmentsByIdConfirm409
      | PostShipmentsByIdConfirm422
    >,
    { id: PostShipmentsByIdConfirmPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostShipmentsByIdConfirmMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdConfirm404
      | PostShipmentsByIdConfirm409
      | PostShipmentsByIdConfirm422
    >,
    { id: PostShipmentsByIdConfirmPathParams["id"] },
    TContext
  >;
}
