/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostShipmentsByIdReceiveMutationResponse,
  PostShipmentsByIdReceivePathParams,
  PostShipmentsByIdReceive404,
  PostShipmentsByIdReceive409,
} from "../../types/shipmentsController/PostShipmentsByIdReceive.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postShipmentsByIdReceive } from "../../clients/shipmentsController/postShipmentsByIdReceive.ts";

export const postShipmentsByIdReceiveMutationKey = () =>
  [{ url: "/shipments/:id/receive" }] as const;

export type PostShipmentsByIdReceiveMutationKey = ReturnType<
  typeof postShipmentsByIdReceiveMutationKey
>;

export function postShipmentsByIdReceiveMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postShipmentsByIdReceiveMutationKey();
  return mutationOptions<
    PostShipmentsByIdReceiveMutationResponse,
    ResponseErrorConfig<
      PostShipmentsByIdReceive404 | PostShipmentsByIdReceive409
    >,
    { id: PostShipmentsByIdReceivePathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postShipmentsByIdReceive(id, config);
    },
  });
}

/**
 * @description Confirma a entrada no centro de distribuição: credita o estoque full de destino
 * {@link /shipments/:id/receive}
 */
export function usePostShipmentsByIdReceive<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostShipmentsByIdReceiveMutationResponse,
      ResponseErrorConfig<
        PostShipmentsByIdReceive404 | PostShipmentsByIdReceive409
      >,
      { id: PostShipmentsByIdReceivePathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postShipmentsByIdReceiveMutationKey();

  const baseOptions = postShipmentsByIdReceiveMutationOptions(
    config,
  ) as UseMutationOptions<
    PostShipmentsByIdReceiveMutationResponse,
    ResponseErrorConfig<
      PostShipmentsByIdReceive404 | PostShipmentsByIdReceive409
    >,
    { id: PostShipmentsByIdReceivePathParams["id"] },
    TContext
  >;

  return useMutation<
    PostShipmentsByIdReceiveMutationResponse,
    ResponseErrorConfig<
      PostShipmentsByIdReceive404 | PostShipmentsByIdReceive409
    >,
    { id: PostShipmentsByIdReceivePathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostShipmentsByIdReceiveMutationResponse,
    ResponseErrorConfig<
      PostShipmentsByIdReceive404 | PostShipmentsByIdReceive409
    >,
    { id: PostShipmentsByIdReceivePathParams["id"] },
    TContext
  >;
}
