/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostShipmentsByIdDispatchMutationResponse,
  PostShipmentsByIdDispatchPathParams,
  PostShipmentsByIdDispatch404,
  PostShipmentsByIdDispatch409,
  PostShipmentsByIdDispatch422,
} from "../../types/shipmentsController/PostShipmentsByIdDispatch.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postShipmentsByIdDispatch } from "../../clients/shipmentsController/postShipmentsByIdDispatch.ts";

export const postShipmentsByIdDispatchMutationKey = () =>
  [{ url: "/shipments/:id/dispatch" }] as const;

export type PostShipmentsByIdDispatchMutationKey = ReturnType<
  typeof postShipmentsByIdDispatchMutationKey
>;

export function postShipmentsByIdDispatchMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = postShipmentsByIdDispatchMutationKey();
  return mutationOptions<
    PostShipmentsByIdDispatchMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdDispatch404
      | PostShipmentsByIdDispatch409
      | PostShipmentsByIdDispatch422
    >,
    { id: PostShipmentsByIdDispatchPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postShipmentsByIdDispatch(id, config);
    },
  });
}

/**
 * @description Despacha o envio: debita o estoque de origem e marca como em trânsito
 * {@link /shipments/:id/dispatch}
 */
export function usePostShipmentsByIdDispatch<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostShipmentsByIdDispatchMutationResponse,
      ResponseErrorConfig<
        | PostShipmentsByIdDispatch404
        | PostShipmentsByIdDispatch409
        | PostShipmentsByIdDispatch422
      >,
      { id: PostShipmentsByIdDispatchPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postShipmentsByIdDispatchMutationKey();

  const baseOptions = postShipmentsByIdDispatchMutationOptions(
    config,
  ) as UseMutationOptions<
    PostShipmentsByIdDispatchMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdDispatch404
      | PostShipmentsByIdDispatch409
      | PostShipmentsByIdDispatch422
    >,
    { id: PostShipmentsByIdDispatchPathParams["id"] },
    TContext
  >;

  return useMutation<
    PostShipmentsByIdDispatchMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdDispatch404
      | PostShipmentsByIdDispatch409
      | PostShipmentsByIdDispatch422
    >,
    { id: PostShipmentsByIdDispatchPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostShipmentsByIdDispatchMutationResponse,
    ResponseErrorConfig<
      | PostShipmentsByIdDispatch404
      | PostShipmentsByIdDispatch409
      | PostShipmentsByIdDispatch422
    >,
    { id: PostShipmentsByIdDispatchPathParams["id"] },
    TContext
  >;
}
