/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetStores200 = {
  /**
   * @type array
   */
  stores: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    name: string;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  }[];
};

export type GetStoresQueryResponse = GetStores200;

export type GetStoresQuery = {
  Response: GetStores200;
  Errors: any;
};
