/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetDashboardCurrentMonthSalesQueryResponse } from "../../types/dashboardController/GetDashboardCurrentMonthSales.ts";

function getGetDashboardCurrentMonthSalesUrl() {
  const res = { method: "GET", url: `/dashboard/current-month-sales` as const };
  return res;
}

/**
 * @description Retorna o total de vendas do mes atual em centavos
 * {@link /dashboard/current-month-sales}
 */
export async function getDashboardCurrentMonthSales(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDashboardCurrentMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetDashboardCurrentMonthSalesUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
