/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type { GetDashboardLastMonthSalesQueryResponse } from '../../types/dashboardController/GetDashboardLastMonthSales.ts'

function getGetDashboardLastMonthSalesUrl() {
  const res = { method: 'GET', url: `/dashboard/last-month-sales` as const }
  return res
}

/**
 * @description Retorna o total de vendas do mes passado em centavos
 * {@link /dashboard/last-month-sales}
 */
export async function getDashboardLastMonthSales(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetDashboardLastMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetDashboardLastMonthSalesUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
