/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetDashboardLast15DaysSalesQueryResponse } from "../../types/dashboardController/GetDashboardLast15DaysSales.ts";

function getGetDashboardLast15DaysSalesUrl() {
  const res = { method: "GET", url: `/dashboard/last-15-days-sales` as const };
  return res;
}

/**
 * @description Retorna faturamento diario dos ultimos 15 dias com media diaria
 * {@link /dashboard/last-15-days-sales}
 */
export async function getDashboardLast15DaysSales(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDashboardLast15DaysSalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetDashboardLast15DaysSalesUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
