/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type { GetDashboardMonthlySalesQueryResponse } from '../../types/dashboardController/GetDashboardMonthlySales.ts'

function getGetDashboardMonthlySalesUrl() {
  const res = { method: 'GET', url: `/dashboard/monthly-sales` as const }
  return res
}

/**
 * @description Retorna faturamento diario do mes atual com media diaria
 * {@link /dashboard/monthly-sales}
 */
export async function getDashboardMonthlySales(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetDashboardMonthlySalesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetDashboardMonthlySalesUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}
