/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type { GetDashboardMonthlySalesPaceQueryResponse } from "../../types/dashboardController/GetDashboardMonthlySalesPace.ts";

function getGetDashboardMonthlySalesPaceUrl() {
  const res = { method: "GET", url: `/dashboard/monthly-sales-pace` as const };
  return res;
}

/**
 * @description Retorna faturamento acumulado por dia do mes, comparando o mes atual com o mes passado
 * {@link /dashboard/monthly-sales-pace}
 */
export async function getDashboardMonthlySalesPace(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDashboardMonthlySalesPaceQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetDashboardMonthlySalesPaceUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
