/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProductsProductIdStockEntriesPathParams = {
  /**
   * @type string, uuid
   */
  productId: string;
};

/**
 * @description Default Response
 */
export type GetProductsProductIdStockEntries200 = {
  /**
   * @type array
   */
  entries: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    stock_id: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @type string
     */
    notes: string | null;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string
     */
    stock_title: string;
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @type string
     */
    product_sku: string;
    /**
     * @type string, uuid
     */
    brand_id: string | null;
    /**
     * @type string
     */
    brand_name: string | null;
  }[];
};

export type GetProductsProductIdStockEntriesQueryResponse =
  GetProductsProductIdStockEntries200;

export type GetProductsProductIdStockEntriesQuery = {
  Response: GetProductsProductIdStockEntries200;
  PathParams: GetProductsProductIdStockEntriesPathParams;
  Errors: any;
};
