/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostStocksStockIdExitsPathParams = {
  /**
   * @type string, uuid
   */
  stockId: string;
};

/**
 * @description Default Response
 */
export type PostStocksStockIdExits201 = {
  /**
   * @type object
   */
  entry: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    stock_id: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @type string
     */
    notes: string | null;
    /**
     * @type string, date-time
     */
    created_at: string;
  };
};

/**
 * @description Default Response
 */
export type PostStocksStockIdExits404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostStocksStockIdExits422 = {
  /**
   * @type string
   */
  error: string;
};

export type PostStocksStockIdExitsMutationRequest = {
  /**
   * @minLength 1
   * @maxLength 9007199254740991
   * @type integer
   */
  quantity: number;
  /**
   * @type string
   */
  notes?: string | null;
};

export type PostStocksStockIdExitsMutationResponse = PostStocksStockIdExits201;

export type PostStocksStockIdExitsMutation = {
  Response: PostStocksStockIdExits201;
  Request: PostStocksStockIdExitsMutationRequest;
  PathParams: PostStocksStockIdExitsPathParams;
  Errors: PostStocksStockIdExits404 | PostStocksStockIdExits422;
};
