/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostStocksStockIdEntriesPathParams = {
  /**
   * @type string, uuid
   */
  stockId: string;
};

/**
 * @description Default Response
 */
export type PostStocksStockIdEntries201 = {
  /**
   * @type object
   */
  entry: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    stock_id: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @type string
     */
    notes: string | null;
    /**
     * @type string, date-time
     */
    created_at: string;
  };
};

/**
 * @description Default Response
 */
export type PostStocksStockIdEntries404 = {
  /**
   * @type string
   */
  error: string;
};

export type PostStocksStockIdEntriesMutationRequest = {
  /**
   * @minLength 1
   * @maxLength 9007199254740991
   * @type integer
   */
  quantity: number;
  /**
   * @type string
   */
  notes?: string | null;
};

export type PostStocksStockIdEntriesMutationResponse =
  PostStocksStockIdEntries201;

export type PostStocksStockIdEntriesMutation = {
  Response: PostStocksStockIdEntries201;
  Request: PostStocksStockIdEntriesMutationRequest;
  PathParams: PostStocksStockIdEntriesPathParams;
  Errors: PostStocksStockIdEntries404;
};
