/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  GetProductsProductIdStocksQueryResponse,
  GetProductsProductIdStocksPathParams,
  GetProductsProductIdStocks404,
} from '../../types/stocksController/GetProductsProductIdStocks.ts'

function getGetProductsProductIdStocksUrl(
  productId: GetProductsProductIdStocksPathParams['productId']
) {
  const res = { method: 'GET', url: `/products/${productId}/stocks` as const }
  return res
}

/**
 * @description Lista os estoques de um produto
 * {@link /products/:productId/stocks}
 */
export async function getProductsProductIdStocks(
  productId: GetProductsProductIdStocksPathParams['productId'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetProductsProductIdStocksQueryResponse,
    ResponseErrorConfig<GetProductsProductIdStocks404>,
    unknown
  >({
    method: 'GET',
    url: getGetProductsProductIdStocksUrl(productId).url.toString(),
    ...requestConfig,
  })
  return res.data
}
