/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PatchStocksStockIdMutationRequest,
  PatchStocksStockIdMutationResponse,
  PatchStocksStockIdPathParams,
  PatchStocksStockId404,
} from "../../types/stocksController/PatchStocksStockId.ts";

function getPatchStocksStockIdUrl(
  stockId: PatchStocksStockIdPathParams["stockId"],
) {
  const res = { method: "PATCH", url: `/stocks/${stockId}` as const };
  return res;
}

/**
 * @description Atualiza um estoque
 * {@link /stocks/:stockId}
 */
export async function patchStocksStockId(
  stockId: PatchStocksStockIdPathParams["stockId"],
  data: PatchStocksStockIdMutationRequest,
  config: Partial<RequestConfig<PatchStocksStockIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchStocksStockIdMutationResponse,
    ResponseErrorConfig<PatchStocksStockId404>,
    PatchStocksStockIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchStocksStockIdUrl(stockId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
