/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostProductsProductIdStocksMutationRequest,
  PostProductsProductIdStocksMutationResponse,
  PostProductsProductIdStocksPathParams,
  PostProductsProductIdStocks404,
} from "../../types/stocksController/PostProductsProductIdStocks.ts";

function getPostProductsProductIdStocksUrl(
  productId: PostProductsProductIdStocksPathParams["productId"],
) {
  const res = { method: "POST", url: `/products/${productId}/stocks` as const };
  return res;
}

/**
 * @description Cria um estoque para um produto
 * {@link /products/:productId/stocks}
 */
export async function postProductsProductIdStocks(
  productId: PostProductsProductIdStocksPathParams["productId"],
  data: PostProductsProductIdStocksMutationRequest,
  config: Partial<RequestConfig<PostProductsProductIdStocksMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostProductsProductIdStocksMutationResponse,
    ResponseErrorConfig<PostProductsProductIdStocks404>,
    PostProductsProductIdStocksMutationRequest
  >({
    method: "POST",
    url: getPostProductsProductIdStocksUrl(productId).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
