/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  GetProductsSalesVelocityQueryResponse,
  GetProductsSalesVelocityQueryParams,
} from "../../types/productsController/GetProductsSalesVelocity.ts";

function getGetProductsSalesVelocityUrl() {
  const res = { method: "GET", url: `/products/sales-velocity` as const };
  return res;
}

/**
 * @description Retorna unidades vendidas por produto nos últimos 15, 30, 60 e 90 dias
 * {@link /products/sales-velocity}
 */
export async function getProductsSalesVelocity(
  params?: GetProductsSalesVelocityQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProductsSalesVelocityQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetProductsSalesVelocityUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
