/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  GetProductSalesDailyQueryResponse,
  GetProductSalesDailyPathParams,
} from '../../types/productsController/GetProductSalesDaily.ts'

function getGetProductSalesDailyUrl(id: GetProductSalesDailyPathParams['id']) {
  const res = { method: 'GET', url: `/products/${id}/sales-daily` as const }
  return res
}

/**
 * @description Retorna vendas diárias por loja e período para um produto
 * {@link /products/:id/sales-daily}
 */
export async function getProductSalesDaily(
  id: GetProductSalesDailyPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetProductSalesDailyQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: getGetProductSalesDailyUrl(id).url.toString(),
    ...requestConfig,
  })
  return res.data
}
