/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  GetProductsQueryResponse,
  GetProductsQueryParams,
} from "../../types/productsController/GetProducts.ts";

function getGetProductsUrl() {
  const res = { method: "GET", url: `/products` as const };
  return res;
}

/**
 * @description Lista todos os produtos com paginação
 * {@link /products}
 */
export async function getProducts(
  params?: GetProductsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetProductsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getGetProductsUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
