/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PatchProductsIdMutationRequest,
  PatchProductsIdMutationResponse,
  PatchProductsIdPathParams,
  PatchProductsId404,
  PatchProductsId409,
} from "../../types/productsController/PatchProductsId.ts";

function getPatchProductsIdUrl(id: PatchProductsIdPathParams["id"]) {
  const res = { method: "PATCH", url: `/products/${id}` as const };
  return res;
}

/**
 * @description Atualiza dados de um produto
 * {@link /products/:id}
 */
export async function patchProductsId(
  id: PatchProductsIdPathParams["id"],
  data: PatchProductsIdMutationRequest,
  config: Partial<RequestConfig<PatchProductsIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchProductsIdMutationResponse,
    ResponseErrorConfig<PatchProductsId404 | PatchProductsId409>,
    PatchProductsIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchProductsIdUrl(id).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
