/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/kubb-axios-client'
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@/lib/kubb-axios-client'
import type {
  PostProductsMutationRequest,
  PostProductsMutationResponse,
  PostProducts404,
  PostProducts409,
} from '../../types/productsController/PostProducts.ts'

function getPostProductsUrl() {
  const res = { method: 'POST', url: `/products` as const }
  return res
}

/**
 * @description Cria um produto
 * {@link /products}
 */
export async function postProducts(
  data: PostProductsMutationRequest,
  config: Partial<RequestConfig<PostProductsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    PostProductsMutationResponse,
    ResponseErrorConfig<PostProducts404 | PostProducts409>,
    PostProductsMutationRequest
  >({
    method: 'POST',
    url: getPostProductsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}
