/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetMetricsMonthlySales200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @type string
     */
    date: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    total_cents: number;
  }[];
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  daily_average_cents: number;
};

export type GetMetricsMonthlySalesQueryResponse = GetMetricsMonthlySales200;

export type GetMetricsMonthlySalesQuery = {
  Response: GetMetricsMonthlySales200;
  Errors: any;
};
