/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetMetricsLastMonthSales200 = {
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  total_cents: number;
};

export type GetMetricsLastMonthSalesQueryResponse = GetMetricsLastMonthSales200;

export type GetMetricsLastMonthSalesQuery = {
  Response: GetMetricsLastMonthSales200;
  Errors: any;
};
