/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetMetricsLastMonthSalesQueryResponse } from "../../types/metricsController/GetMetricsLastMonthSales.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getMetricsLastMonthSales } from "../../clients/metricsController/getMetricsLastMonthSales.ts";

export const getMetricsLastMonthSalesQueryKey = () =>
  [{ url: "/metrics/last-month-sales" }] as const;

export type GetMetricsLastMonthSalesQueryKey = ReturnType<
  typeof getMetricsLastMonthSalesQueryKey
>;

export function getMetricsLastMonthSalesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getMetricsLastMonthSalesQueryKey();
  return queryOptions<
    GetMetricsLastMonthSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetMetricsLastMonthSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getMetricsLastMonthSales({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna o total de vendas do mes passado em centavos
 * {@link /metrics/last-month-sales}
 */
export function useGetMetricsLastMonthSales<
  TData = GetMetricsLastMonthSalesQueryResponse,
  TQueryData = GetMetricsLastMonthSalesQueryResponse,
  TQueryKey extends QueryKey = GetMetricsLastMonthSalesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetMetricsLastMonthSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getMetricsLastMonthSalesQueryKey();

  const query = useQuery(
    {
      ...getMetricsLastMonthSalesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
