/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetMetricsMonthlySalesQueryResponse } from "../../types/metricsController/GetMetricsMonthlySales.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getMetricsMonthlySales } from "../../clients/metricsController/getMetricsMonthlySales.ts";

export const getMetricsMonthlySalesQueryKey = () =>
  [{ url: "/metrics/monthly-sales" }] as const;

export type GetMetricsMonthlySalesQueryKey = ReturnType<
  typeof getMetricsMonthlySalesQueryKey
>;

export function getMetricsMonthlySalesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getMetricsMonthlySalesQueryKey();
  return queryOptions<
    GetMetricsMonthlySalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetMetricsMonthlySalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getMetricsMonthlySales({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna faturamento diario do mes atual com media diaria
 * {@link /metrics/monthly-sales}
 */
export function useGetMetricsMonthlySales<
  TData = GetMetricsMonthlySalesQueryResponse,
  TQueryData = GetMetricsMonthlySalesQueryResponse,
  TQueryKey extends QueryKey = GetMetricsMonthlySalesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetMetricsMonthlySalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getMetricsMonthlySalesQueryKey();

  const query = useQuery(
    {
      ...getMetricsMonthlySalesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
