/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { GetMetricsMonthlySalesQueryResponse } from "../../types/metricsController/GetMetricsMonthlySales.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getMetricsMonthlySales } from "../../clients/metricsController/getMetricsMonthlySales.ts";

export const getMetricsMonthlySalesSuspenseQueryKey = () =>
  [{ url: "/metrics/monthly-sales" }] as const;

export type GetMetricsMonthlySalesSuspenseQueryKey = ReturnType<
  typeof getMetricsMonthlySalesSuspenseQueryKey
>;

export function getMetricsMonthlySalesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getMetricsMonthlySalesSuspenseQueryKey();
  return queryOptions<
    GetMetricsMonthlySalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetMetricsMonthlySalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getMetricsMonthlySales({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna faturamento diario do mes atual com media diaria
 * {@link /metrics/monthly-sales}
 */
export function useGetMetricsMonthlySalesSuspense<
  TData = GetMetricsMonthlySalesQueryResponse,
  TQueryKey extends QueryKey = GetMetricsMonthlySalesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetMetricsMonthlySalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getMetricsMonthlySalesSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getMetricsMonthlySalesSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
