/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PostFbaAnalyzeMutationRequest,
  PostFbaAnalyzeMutationResponse,
  PostFbaAnalyze400,
} from "../../types/fbaController/PostFbaAnalyze.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postFbaAnalyze } from "../../clients/fbaController/postFbaAnalyze.ts";

export const postFbaAnalyzeMutationKey = () =>
  [{ url: "/fba/analyze" }] as const;

export type PostFbaAnalyzeMutationKey = ReturnType<
  typeof postFbaAnalyzeMutationKey
>;

export function postFbaAnalyzeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostFbaAnalyzeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postFbaAnalyzeMutationKey();
  return mutationOptions<
    PostFbaAnalyzeMutationResponse,
    ResponseErrorConfig<PostFbaAnalyze400>,
    { data: PostFbaAnalyzeMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postFbaAnalyze(data, config);
    },
  });
}

/**
 * @description Analisa um CSV de 90 dias para recomendacao de envio ao Amazon FBA
 * {@link /fba/analyze}
 */
export function usePostFbaAnalyze<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostFbaAnalyzeMutationResponse,
      ResponseErrorConfig<PostFbaAnalyze400>,
      { data: PostFbaAnalyzeMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostFbaAnalyzeMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postFbaAnalyzeMutationKey();

  const baseOptions = postFbaAnalyzeMutationOptions(
    config,
  ) as UseMutationOptions<
    PostFbaAnalyzeMutationResponse,
    ResponseErrorConfig<PostFbaAnalyze400>,
    { data: PostFbaAnalyzeMutationRequest },
    TContext
  >;

  return useMutation<
    PostFbaAnalyzeMutationResponse,
    ResponseErrorConfig<PostFbaAnalyze400>,
    { data: PostFbaAnalyzeMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostFbaAnalyzeMutationResponse,
    ResponseErrorConfig<PostFbaAnalyze400>,
    { data: PostFbaAnalyzeMutationRequest },
    TContext
  >;
}
