/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProductPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Default Response
 */
export type DeleteProduct204 = object;

/**
 * @description Default Response
 */
export type DeleteProduct404 = {
  /**
   * @type string
   */
  error: string;
};

export type DeleteProductMutationResponse = DeleteProduct204;

export type DeleteProductMutation = {
  Response: DeleteProduct204;
  PathParams: DeleteProductPathParams;
  Errors: DeleteProduct404;
};
