/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getProductsSalesVelocityQueryParamsWithoutImageEnum = {
  true: 'true',
  false: 'false',
} as const

export type GetProductsSalesVelocityQueryParamsWithoutImageEnumKey =
  (typeof getProductsSalesVelocityQueryParamsWithoutImageEnum)[keyof typeof getProductsSalesVelocityQueryParamsWithoutImageEnum]

export type GetProductsSalesVelocityQueryParams = {
  /**
   * @default "0"
   * @type string | undefined
   */
  pageIndex?: string
  /**
   * @type string | undefined
   */
  search?: string
  /**
   * @type string | undefined
   */
  withoutImage?: GetProductsSalesVelocityQueryParamsWithoutImageEnumKey
}

/**
 * @description Default Response
 */
export type GetProductsSalesVelocity200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @type string, uuid
     */
    product_id: string
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    units_15d: number
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    units_30d: number
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    units_60d: number
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    units_90d: number
  }[]
}

export type GetProductsSalesVelocityQueryResponse = GetProductsSalesVelocity200

export type GetProductsSalesVelocityQuery = {
  Response: GetProductsSalesVelocity200
  QueryParams: GetProductsSalesVelocityQueryParams
  Errors: any
}
