/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getProductsQueryParamsWithoutImageEnum = {
  true: "true",
  false: "false",
} as const;

export type GetProductsQueryParamsWithoutImageEnumKey =
  (typeof getProductsQueryParamsWithoutImageEnum)[keyof typeof getProductsQueryParamsWithoutImageEnum];

export type GetProductsQueryParams = {
  /**
   * @description Índice da página (zero-based)
   * @default "0"
   * @type string | undefined
   */
  pageIndex?: string;
  /**
   * @description Pesquisa por SKU ou EAN
   * @type string | undefined
   */
  search?: string;
  /**
   * @description Filtrar apenas produtos sem imagem
   * @type string | undefined
   */
  withoutImage?: GetProductsQueryParamsWithoutImageEnumKey;
};

/**
 * @description Default Response
 */
export type GetProducts200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    ean: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    sale_price_cents: number | null;
    /**
     * @type string, uuid
     */
    brand_id: string | null;
    /**
     * @type object
     */
    brand: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      name: string;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    } | null;
    /**
     * @type string
     */
    url_image: string | null;
    /**
     * @type string
     */
    technical_title: string | null;
    /**
     * @type string
     */
    technical_subtitle: string | null;
    /**
     * @type string
     */
    technical_analysis: string | null;
    /**
     * @type string
     */
    technical_movement: string | null;
    /**
     * @type string
     */
    technical_case_and_crystal: string | null;
    /**
     * @type string
     */
    technical_specific_functionality: string | null;
    /**
     * @type string
     */
    technical_dial_and_luminosity: string | null;
    /**
     * @type string
     */
    technical_bracelet_construction: string | null;
    /**
     * @type string
     */
    technical_table: string | null;
    /**
     * @type array
     */
    stocks: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type string
       */
      title: string;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number;
      /**
       * @type boolean
       */
      full: boolean;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    }[];
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  }[];
  /**
   * @type number
   */
  total: number;
  /**
   * @type number
   */
  pageIndex: number;
};

export type GetProductsQueryResponse = GetProducts200;

export type GetProductsQuery = {
  Response: GetProducts200;
  QueryParams: GetProductsQueryParams;
  Errors: any;
};
