/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchProductsIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

export const stocksMarketplaceEnum3 = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type StocksMarketplaceEnum3Key =
  (typeof stocksMarketplaceEnum3)[keyof typeof stocksMarketplaceEnum3];

/**
 * @description Default Response
 */
export type PatchProductsId200 = {
  /**
   * @type object
   */
  product: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    ean: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    sale_price_cents: number | null;
    /**
     * @type string, uuid
     */
    brand_id: string | null;
    /**
     * @type object
     */
    brand: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      name: string;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    } | null;
    /**
     * @type string
     */
    url_image: string | null;
    /**
     * @type string
     */
    technical_title: string | null;
    /**
     * @type string
     */
    technical_description: string | null;
    /**
     * @type array
     */
    stocks: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type string
       */
      title: string;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number;
      /**
       * @type boolean
       */
      full: boolean;
      /**
       * @type string
       */
      marketplace: StocksMarketplaceEnum3Key | null;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    }[];
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PatchProductsId404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PatchProductsId409 = {
  /**
   * @type string
   */
  error: string;
};

export type PatchProductsIdMutationRequest = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  sku?: string;
  /**
   * @minLength 1
   * @type string | undefined
   */
  ean?: string;
  /**
   * @minLength 1
   * @maxLength 9007199254740991
   * @type integer
   */
  sale_price_cents?: number | null;
  /**
   * @type string | undefined, uuid
   */
  brand_id?: string;
  /**
   * @type string, uri
   */
  url_image?: string | null;
  /**
   * @type string
   */
  technical_title?: string | null;
  /**
   * @type string
   */
  technical_description?: string | null;
};

export type PatchProductsIdMutationResponse = PatchProductsId200;

export type PatchProductsIdMutation = {
  Response: PatchProductsId200;
  Request: PatchProductsIdMutationRequest;
  PathParams: PatchProductsIdPathParams;
  Errors: PatchProductsId404 | PatchProductsId409;
};
