/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PatchProductsIdImagePathParams = {
    /**
     * @type string, uuid
    */
    id: string;
};

/**
 * @description Default Response
*/
export type PatchProductsIdImage200 = {
    /**
     * @type object
    */
    product: {
        /**
         * @type string, uuid
        */
        id: string;
        /**
         * @type string
        */
        sku: string;
        /**
         * @type string
        */
        ean: string;
        /**
         * @minLength -9007199254740991
         * @maxLength 9007199254740991
         * @type integer
        */
        sale_price_cents: number | null;
        /**
         * @type string, uuid
        */
        brand_id: string | null;
        /**
         * @type object
        */
        brand: {
            /**
             * @type string, uuid
            */
            id: string;
            /**
             * @type string
            */
            name: string;
            /**
             * @type string, date-time
            */
            created_at: string;
            /**
             * @type string, date-time
            */
            updated_at: string;
        } | null;
        /**
         * @type string
        */
        url_image: string | null;
        /**
         * @type array
        */
        stocks: {
            /**
             * @type string, uuid
            */
            id: string;
            /**
             * @type string, uuid
            */
            product_id: string;
            /**
             * @type string
            */
            title: string;
            /**
             * @minLength -9007199254740991
             * @maxLength 9007199254740991
             * @type integer
            */
            qtde: number;
            /**
             * @type boolean
            */
            full: boolean;
            /**
             * @type string, date-time
            */
            created_at: string;
            /**
             * @type string, date-time
            */
            updated_at: string;
        }[];
        /**
         * @type string, date-time
        */
        created_at: string;
        /**
         * @type string, date-time
        */
        updated_at: string;
    };
};

/**
 * @description Default Response
*/
export type PatchProductsIdImage404 = {
    /**
     * @type string
    */
    error: string;
};

export type PatchProductsIdImageMutationRequest = {
    /**
     * @description URL da imagem do produto
     * @type string, uri
    */
    url_image: string;
};

export type PatchProductsIdImageMutationResponse = PatchProductsIdImage200;

export type PatchProductsIdImageMutation = {
    Response: PatchProductsIdImage200;
    Request: PatchProductsIdImageMutationRequest;
    PathParams: PatchProductsIdImagePathParams;
    Errors: PatchProductsIdImage404;
};