/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const stocksMarketplaceEnum = {
  mercado_livre: "mercado_livre",
  amazon: "amazon",
  shopee: "shopee",
} as const;

export type StocksMarketplaceEnumKey =
  (typeof stocksMarketplaceEnum)[keyof typeof stocksMarketplaceEnum];

/**
 * @description Default Response
 */
export type PostProducts201 = {
  /**
   * @type object
   */
  product: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    sku: string;
    /**
     * @type string
     */
    ean: string;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    sale_price_cents: number | null;
    /**
     * @type string, uuid
     */
    brand_id: string | null;
    /**
     * @type object
     */
    brand: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      name: string;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    } | null;
    /**
     * @type string
     */
    url_image: string | null;
    /**
     * @type string
     */
    technical_title: string | null;
    /**
     * @type string
     */
    technical_description: string | null;
    /**
     * @type array
     */
    stocks: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type string
       */
      title: string;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      qtde: number;
      /**
       * @type boolean
       */
      full: boolean;
      /**
       * @type string
       */
      marketplace: StocksMarketplaceEnumKey | null;
      /**
       * @type string, date-time
       */
      created_at: string;
      /**
       * @type string, date-time
       */
      updated_at: string;
    }[];
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PostProducts404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostProducts409 = {
  /**
   * @type string
   */
  error: string;
};

export type PostProductsMutationRequest = {
  /**
   * @description SKU do produto
   * @minLength 1
   * @type string
   */
  sku: string;
  /**
   * @description EAN do produto
   * @minLength 1
   * @type string
   */
  ean: string;
  /**
   * @type string, uuid
   */
  brand_id: string;
  /**
   * @type string | undefined, uri
   */
  url_image?: string;
};

export type PostProductsMutationResponse = PostProducts201;

export type PostProductsMutation = {
  Response: PostProducts201;
  Request: PostProductsMutationRequest;
  Errors: PostProducts404 | PostProducts409;
};
