/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteShipmentsByIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Default Response
 */
export type DeleteShipmentsById204 = any;

/**
 * @description Default Response
 */
export type DeleteShipmentsById404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type DeleteShipmentsById409 = {
  /**
   * @type string
   */
  error: string;
};

export type DeleteShipmentsByIdMutationResponse = DeleteShipmentsById204;

export type DeleteShipmentsByIdMutation = {
  Response: DeleteShipmentsById204;
  PathParams: DeleteShipmentsByIdPathParams;
  Errors: DeleteShipmentsById404 | DeleteShipmentsById409;
};
