/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetShipmentsByIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

export const shipmentStatusEnum2 = {
  rascunho: "rascunho",
  confirmado: "confirmado",
} as const;

export type ShipmentStatusEnum2Key =
  (typeof shipmentStatusEnum2)[keyof typeof shipmentStatusEnum2];

/**
 * @description Default Response
 */
export type GetShipmentsById200 = {
  /**
   * @type object
   */
  shipment: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    account_id: string;
    /**
     * @type string
     */
    account_name: string;
    /**
     * @type string, date-time
     */
    date: string;
    /**
     * @type string
     */
    notes: string | null;
    /**
     * @type string
     */
    status: ShipmentStatusEnum2Key;
    /**
     * @type array
     */
    items: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      shipment_id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type number
       */
      quantity: number;
      /**
       * @type string, uuid
       */
      source_stock_id: string;
      /**
       * @type string, uuid
       */
      destination_stock_id: string;
      /**
       * @type string, date-time
       */
      created_at: string;
    }[];
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type GetShipmentsById404 = {
  /**
   * @type string
   */
  error: string;
};

export type GetShipmentsByIdQueryResponse = GetShipmentsById200;

export type GetShipmentsByIdQuery = {
  Response: GetShipmentsById200;
  PathParams: GetShipmentsByIdPathParams;
  Errors: GetShipmentsById404;
};
