/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const shipmentsStatusEnum = {
  rascunho: "rascunho",
  confirmado: "confirmado",
} as const;

export type ShipmentsStatusEnumKey =
  (typeof shipmentsStatusEnum)[keyof typeof shipmentsStatusEnum];

/**
 * @description Default Response
 */
export type GetShipments200 = {
  /**
   * @type array
   */
  shipments: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    account_id: string;
    /**
     * @type string
     */
    account_name: string;
    /**
     * @type string, date-time
     */
    date: string;
    /**
     * @type string
     */
    notes: string | null;
    /**
     * @type string
     */
    status: ShipmentsStatusEnumKey;
    /**
     * @type number
     */
    item_count: number;
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  }[];
};

export type GetShipmentsQueryResponse = GetShipments200;

export type GetShipmentsQuery = {
  Response: GetShipments200;
  Errors: any;
};
