/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostShipmentsByIdConfirmPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Default Response
 */
export type PostShipmentsByIdConfirm204 = any

/**
 * @description Default Response
 */
export type PostShipmentsByIdConfirm404 = {
  /**
   * @type string
   */
  error: string
}

/**
 * @description Default Response
 */
export type PostShipmentsByIdConfirm409 = {
  /**
   * @type string
   */
  error: string
}

/**
 * @description Default Response
 */
export type PostShipmentsByIdConfirm422 = {
  /**
   * @type string
   */
  error: string
}

export type PostShipmentsByIdConfirmMutationResponse =
  PostShipmentsByIdConfirm204

export type PostShipmentsByIdConfirmMutation = {
  Response: PostShipmentsByIdConfirm204
  PathParams: PostShipmentsByIdConfirmPathParams
  Errors:
    | PostShipmentsByIdConfirm404
    | PostShipmentsByIdConfirm409
    | PostShipmentsByIdConfirm422
}
