/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const shipmentStatusEnum = {
  rascunho: "rascunho",
  em_transito: "em_transito",
  recebido: "recebido",
} as const;

export type ShipmentStatusEnumKey =
  (typeof shipmentStatusEnum)[keyof typeof shipmentStatusEnum];

/**
 * @description Default Response
 */
export type PostShipments201 = {
  /**
   * @type object
   */
  shipment: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    account_id: string;
    /**
     * @type string
     */
    account_name: string;
    /**
     * @type string, date-time
     */
    date: string;
    /**
     * @type string
     */
    notes: string | null;
    /**
     * @type string
     */
    status: ShipmentStatusEnumKey;
    /**
     * @type array
     */
    items: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      shipment_id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type number
       */
      quantity: number;
      /**
       * @type string, uuid
       */
      source_stock_id: string;
      /**
       * @type string, uuid
       */
      destination_stock_id: string;
      /**
       * @type string, date-time
       */
      created_at: string;
    }[];
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PostShipments404 = {
  /**
   * @type string
   */
  error: string;
};

export type PostShipmentsMutationRequest = {
  /**
   * @type string, uuid
   */
  account_id: string;
  /**
   * @type string, date-time
   */
  date: string;
  /**
   * @type string
   */
  notes?: string | null;
  /**
   * @type array
   */
  items: {
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @type string, uuid
     */
    source_stock_id: string;
    /**
     * @type string, uuid
     */
    destination_stock_id: string;
  }[];
};

export type PostShipmentsMutationResponse = PostShipments201;

export type PostShipmentsMutation = {
  Response: PostShipments201;
  Request: PostShipmentsMutationRequest;
  Errors: PostShipments404;
};
