/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostShipmentsByIdReceivePathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Default Response
 */
export type PostShipmentsByIdReceive204 = any;

/**
 * @description Default Response
 */
export type PostShipmentsByIdReceive404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostShipmentsByIdReceive409 = {
  /**
   * @type string
   */
  error: string;
};

export type PostShipmentsByIdReceiveMutationResponse =
  PostShipmentsByIdReceive204;

export type PostShipmentsByIdReceiveMutation = {
  Response: PostShipmentsByIdReceive204;
  PathParams: PostShipmentsByIdReceivePathParams;
  Errors: PostShipmentsByIdReceive404 | PostShipmentsByIdReceive409;
};
