/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PostShipmentsByIdDispatchPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

/**
 * @description Default Response
 */
export type PostShipmentsByIdDispatch204 = any;

/**
 * @description Default Response
 */
export type PostShipmentsByIdDispatch404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostShipmentsByIdDispatch409 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PostShipmentsByIdDispatch422 = {
  /**
   * @type string
   */
  error: string;
};

export type PostShipmentsByIdDispatchMutationResponse =
  PostShipmentsByIdDispatch204;

export type PostShipmentsByIdDispatchMutation = {
  Response: PostShipmentsByIdDispatch204;
  PathParams: PostShipmentsByIdDispatchPathParams;
  Errors:
    | PostShipmentsByIdDispatch404
    | PostShipmentsByIdDispatch409
    | PostShipmentsByIdDispatch422;
};
