/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutShipmentsByIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string;
};

export const shipmentStatusEnum3 = {
  rascunho: "rascunho",
  em_transito: "em_transito",
  recebido: "recebido",
} as const;

export type ShipmentStatusEnum3Key =
  (typeof shipmentStatusEnum3)[keyof typeof shipmentStatusEnum3];

/**
 * @description Default Response
 */
export type PutShipmentsById200 = {
  /**
   * @type object
   */
  shipment: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    account_id: string;
    /**
     * @type string
     */
    account_name: string;
    /**
     * @type string, date-time
     */
    date: string;
    /**
     * @type string
     */
    notes: string | null;
    /**
     * @type string
     */
    status: ShipmentStatusEnum3Key;
    /**
     * @type array
     */
    items: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      shipment_id: string;
      /**
       * @type string, uuid
       */
      product_id: string;
      /**
       * @type number
       */
      quantity: number;
      /**
       * @type string, uuid
       */
      source_stock_id: string;
      /**
       * @type string, uuid
       */
      destination_stock_id: string;
      /**
       * @type string, date-time
       */
      created_at: string;
    }[];
    /**
     * @type string, date-time
     */
    created_at: string;
    /**
     * @type string, date-time
     */
    updated_at: string;
  };
};

/**
 * @description Default Response
 */
export type PutShipmentsById404 = {
  /**
   * @type string
   */
  error: string;
};

/**
 * @description Default Response
 */
export type PutShipmentsById409 = {
  /**
   * @type string
   */
  error: string;
};

export type PutShipmentsByIdMutationRequest = {
  /**
   * @type string | undefined, uuid
   */
  account_id?: string;
  /**
   * @type string | undefined, date-time
   */
  date?: string;
  /**
   * @type string
   */
  notes?: string | null;
  /**
   * @type array | undefined
   */
  items?: {
    /**
     * @type string, uuid
     */
    product_id: string;
    /**
     * @maxLength 9007199254740991
     * @type integer
     */
    quantity: number;
    /**
     * @type string, uuid
     */
    source_stock_id: string;
    /**
     * @type string, uuid
     */
    destination_stock_id: string;
  }[];
};

export type PutShipmentsByIdMutationResponse = PutShipmentsById200;

export type PutShipmentsByIdMutation = {
  Response: PutShipmentsById200;
  Request: PutShipmentsByIdMutationRequest;
  PathParams: PutShipmentsByIdPathParams;
  Errors: PutShipmentsById404 | PutShipmentsById409;
};
