/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetDashboardCurrentMonthSales200 = {
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  total_cents: number;
};

export type GetDashboardCurrentMonthSalesQueryResponse =
  GetDashboardCurrentMonthSales200;

export type GetDashboardCurrentMonthSalesQuery = {
  Response: GetDashboardCurrentMonthSales200;
  Errors: any;
};
