/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetDashboardMonthlySalesPace200 = {
  /**
   * @type array
   */
  items: {
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    day: number;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    current_month_cents: number | null;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    last_month_cents: number | null;
  }[];
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  current_month_total_cents: number;
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  last_month_total_cents: number;
};

export type GetDashboardMonthlySalesPaceQueryResponse =
  GetDashboardMonthlySalesPace200;

export type GetDashboardMonthlySalesPaceQuery = {
  Response: GetDashboardMonthlySalesPace200;
  Errors: any;
};
