/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type GetDashboardLastMonthSales200 = {
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  total_cents: number
}

export type GetDashboardLastMonthSalesQueryResponse =
  GetDashboardLastMonthSales200

export type GetDashboardLastMonthSalesQuery = {
  Response: GetDashboardLastMonthSales200
  Errors: any
}
