/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  DeleteStocksStockIdMutationResponse,
  DeleteStocksStockIdPathParams,
  DeleteStocksStockId404,
} from "../../types/stocksController/DeleteStocksStockId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteStocksStockId } from "../../clients/stocksController/deleteStocksStockId.ts";

export const deleteStocksStockIdMutationKey = () =>
  [{ url: "/stocks/:stockId" }] as const;

export type DeleteStocksStockIdMutationKey = ReturnType<
  typeof deleteStocksStockIdMutationKey
>;

export function deleteStocksStockIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteStocksStockIdMutationKey();
  return mutationOptions<
    DeleteStocksStockIdMutationResponse,
    ResponseErrorConfig<DeleteStocksStockId404>,
    { stockId: DeleteStocksStockIdPathParams["stockId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ stockId }) => {
      return deleteStocksStockId(stockId, config);
    },
  });
}

/**
 * @description Exclui um estoque
 * {@link /stocks/:stockId}
 */
export function useDeleteStocksStockId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteStocksStockIdMutationResponse,
      ResponseErrorConfig<DeleteStocksStockId404>,
      { stockId: DeleteStocksStockIdPathParams["stockId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteStocksStockIdMutationKey();

  const baseOptions = deleteStocksStockIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteStocksStockIdMutationResponse,
    ResponseErrorConfig<DeleteStocksStockId404>,
    { stockId: DeleteStocksStockIdPathParams["stockId"] },
    TContext
  >;

  return useMutation<
    DeleteStocksStockIdMutationResponse,
    ResponseErrorConfig<DeleteStocksStockId404>,
    { stockId: DeleteStocksStockIdPathParams["stockId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteStocksStockIdMutationResponse,
    ResponseErrorConfig<DeleteStocksStockId404>,
    { stockId: DeleteStocksStockIdPathParams["stockId"] },
    TContext
  >;
}
