/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetProductsProductIdStocksQueryResponse,
  GetProductsProductIdStocksPathParams,
  GetProductsProductIdStocks404,
} from "../../types/stocksController/GetProductsProductIdStocks.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getProductsProductIdStocks } from "../../clients/stocksController/getProductsProductIdStocks.ts";

export const getProductsProductIdStocksQueryKey = (
  productId: GetProductsProductIdStocksPathParams["productId"],
) =>
  [
    { url: "/products/:productId/stocks", params: { productId: productId } },
  ] as const;

export type GetProductsProductIdStocksQueryKey = ReturnType<
  typeof getProductsProductIdStocksQueryKey
>;

export function getProductsProductIdStocksQueryOptions(
  productId: GetProductsProductIdStocksPathParams["productId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProductsProductIdStocksQueryKey(productId);
  return queryOptions<
    GetProductsProductIdStocksQueryResponse,
    ResponseErrorConfig<GetProductsProductIdStocks404>,
    GetProductsProductIdStocksQueryResponse,
    typeof queryKey
  >({
    enabled: !!productId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProductsProductIdStocks(productId, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Lista os estoques de um produto
 * {@link /products/:productId/stocks}
 */
export function useGetProductsProductIdStocks<
  TData = GetProductsProductIdStocksQueryResponse,
  TQueryData = GetProductsProductIdStocksQueryResponse,
  TQueryKey extends QueryKey = GetProductsProductIdStocksQueryKey,
>(
  productId: GetProductsProductIdStocksPathParams["productId"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProductsProductIdStocksQueryResponse,
        ResponseErrorConfig<GetProductsProductIdStocks404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getProductsProductIdStocksQueryKey(productId);

  const query = useQuery(
    {
      ...getProductsProductIdStocksQueryOptions(productId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetProductsProductIdStocks404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
