/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PostProductsProductIdStocksMutationRequest,
  PostProductsProductIdStocksMutationResponse,
  PostProductsProductIdStocksPathParams,
  PostProductsProductIdStocks404,
} from '../../types/stocksController/PostProductsProductIdStocks.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { postProductsProductIdStocks } from '../../clients/stocksController/postProductsProductIdStocks.ts'

export const postProductsProductIdStocksMutationKey = () =>
  [{ url: '/products/:productId/stocks' }] as const

export type PostProductsProductIdStocksMutationKey = ReturnType<
  typeof postProductsProductIdStocksMutationKey
>

export function postProductsProductIdStocksMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostProductsProductIdStocksMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postProductsProductIdStocksMutationKey()
  return mutationOptions<
    PostProductsProductIdStocksMutationResponse,
    ResponseErrorConfig<PostProductsProductIdStocks404>,
    {
      productId: PostProductsProductIdStocksPathParams['productId']
      data: PostProductsProductIdStocksMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ productId, data }) => {
      return postProductsProductIdStocks(productId, data, config)
    },
  })
}

/**
 * @description Cria um estoque para um produto
 * {@link /products/:productId/stocks}
 */
export function usePostProductsProductIdStocks<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostProductsProductIdStocksMutationResponse,
      ResponseErrorConfig<PostProductsProductIdStocks404>,
      {
        productId: PostProductsProductIdStocksPathParams['productId']
        data: PostProductsProductIdStocksMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<
      RequestConfig<PostProductsProductIdStocksMutationRequest>
    > & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postProductsProductIdStocksMutationKey()

  const baseOptions = postProductsProductIdStocksMutationOptions(
    config
  ) as UseMutationOptions<
    PostProductsProductIdStocksMutationResponse,
    ResponseErrorConfig<PostProductsProductIdStocks404>,
    {
      productId: PostProductsProductIdStocksPathParams['productId']
      data: PostProductsProductIdStocksMutationRequest
    },
    TContext
  >

  return useMutation<
    PostProductsProductIdStocksMutationResponse,
    ResponseErrorConfig<PostProductsProductIdStocks404>,
    {
      productId: PostProductsProductIdStocksPathParams['productId']
      data: PostProductsProductIdStocksMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostProductsProductIdStocksMutationResponse,
    ResponseErrorConfig<PostProductsProductIdStocks404>,
    {
      productId: PostProductsProductIdStocksPathParams['productId']
      data: PostProductsProductIdStocksMutationRequest
    },
    TContext
  >
}
