/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PatchStocksStockIdMutationRequest,
  PatchStocksStockIdMutationResponse,
  PatchStocksStockIdPathParams,
  PatchStocksStockId404,
} from "../../types/stocksController/PatchStocksStockId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { patchStocksStockId } from "../../clients/stocksController/patchStocksStockId.ts";

export const patchStocksStockIdMutationKey = () =>
  [{ url: "/stocks/:stockId" }] as const;

export type PatchStocksStockIdMutationKey = ReturnType<
  typeof patchStocksStockIdMutationKey
>;

export function patchStocksStockIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchStocksStockIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = patchStocksStockIdMutationKey();
  return mutationOptions<
    PatchStocksStockIdMutationResponse,
    ResponseErrorConfig<PatchStocksStockId404>,
    {
      stockId: PatchStocksStockIdPathParams["stockId"];
      data: PatchStocksStockIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ stockId, data }) => {
      return patchStocksStockId(stockId, data, config);
    },
  });
}

/**
 * @description Atualiza um estoque
 * {@link /stocks/:stockId}
 */
export function usePatchStocksStockId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchStocksStockIdMutationResponse,
      ResponseErrorConfig<PatchStocksStockId404>,
      {
        stockId: PatchStocksStockIdPathParams["stockId"];
        data: PatchStocksStockIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchStocksStockIdMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchStocksStockIdMutationKey();

  const baseOptions = patchStocksStockIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchStocksStockIdMutationResponse,
    ResponseErrorConfig<PatchStocksStockId404>,
    {
      stockId: PatchStocksStockIdPathParams["stockId"];
      data: PatchStocksStockIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchStocksStockIdMutationResponse,
    ResponseErrorConfig<PatchStocksStockId404>,
    {
      stockId: PatchStocksStockIdPathParams["stockId"];
      data: PatchStocksStockIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchStocksStockIdMutationResponse,
    ResponseErrorConfig<PatchStocksStockId404>,
    {
      stockId: PatchStocksStockIdPathParams["stockId"];
      data: PatchStocksStockIdMutationRequest;
    },
    TContext
  >;
}
