/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as VendasRouteImport } from './pages/vendas'
import { Route as RelatorioDeEstoqueRouteImport } from './pages/relatorio-de-estoque'
import { Route as MarcasRouteImport } from './pages/marcas'
import { Route as LoginRouteImport } from './pages/login'
import { Route as LancamentosDeEstoqueRouteImport } from './pages/lancamentos-de-estoque'
import { Route as GerenciadorDeProdutosRouteImport } from './pages/gerenciador-de-produtos'
import { Route as IndexRouteImport } from './pages/index'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioDeEstoqueRoute = RelatorioDeEstoqueRouteImport.update({
  id: '/relatorio-de-estoque',
  path: '/relatorio-de-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosDeEstoqueRoute = LancamentosDeEstoqueRouteImport.update({
  id: '/lancamentos-de-estoque',
  path: '/lancamentos-de-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciadorDeProdutosRoute = GerenciadorDeProdutosRouteImport.update({
  id: '/gerenciador-de-produtos',
  path: '/gerenciador-de-produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gerenciador-de-produtos': typeof GerenciadorDeProdutosRoute
  '/lancamentos-de-estoque': typeof LancamentosDeEstoqueRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/relatorio-de-estoque': typeof RelatorioDeEstoqueRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gerenciador-de-produtos': typeof GerenciadorDeProdutosRoute
  '/lancamentos-de-estoque': typeof LancamentosDeEstoqueRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/relatorio-de-estoque': typeof RelatorioDeEstoqueRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gerenciador-de-produtos': typeof GerenciadorDeProdutosRoute
  '/lancamentos-de-estoque': typeof LancamentosDeEstoqueRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/relatorio-de-estoque': typeof RelatorioDeEstoqueRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gerenciador-de-produtos'
    | '/lancamentos-de-estoque'
    | '/login'
    | '/marcas'
    | '/relatorio-de-estoque'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gerenciador-de-produtos'
    | '/lancamentos-de-estoque'
    | '/login'
    | '/marcas'
    | '/relatorio-de-estoque'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/gerenciador-de-produtos'
    | '/lancamentos-de-estoque'
    | '/login'
    | '/marcas'
    | '/relatorio-de-estoque'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GerenciadorDeProdutosRoute: typeof GerenciadorDeProdutosRoute
  LancamentosDeEstoqueRoute: typeof LancamentosDeEstoqueRoute
  LoginRoute: typeof LoginRoute
  MarcasRoute: typeof MarcasRoute
  RelatorioDeEstoqueRoute: typeof RelatorioDeEstoqueRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-de-estoque': {
      id: '/relatorio-de-estoque'
      path: '/relatorio-de-estoque'
      fullPath: '/relatorio-de-estoque'
      preLoaderRoute: typeof RelatorioDeEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos-de-estoque': {
      id: '/lancamentos-de-estoque'
      path: '/lancamentos-de-estoque'
      fullPath: '/lancamentos-de-estoque'
      preLoaderRoute: typeof LancamentosDeEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciador-de-produtos': {
      id: '/gerenciador-de-produtos'
      path: '/gerenciador-de-produtos'
      fullPath: '/gerenciador-de-produtos'
      preLoaderRoute: typeof GerenciadorDeProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GerenciadorDeProdutosRoute: GerenciadorDeProdutosRoute,
  LancamentosDeEstoqueRoute: LancamentosDeEstoqueRoute,
  LoginRoute: LoginRoute,
  MarcasRoute: MarcasRoute,
  RelatorioDeEstoqueRoute: RelatorioDeEstoqueRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
