/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as VendasRouteImport } from './pages/vendas'
import { Route as RelatorioDeVendasRouteImport } from './pages/relatorio-de-vendas'
import { Route as RelatorioDeEstoqueRouteImport } from './pages/relatorio-de-estoque'
import { Route as RelatorioAbcRouteImport } from './pages/relatorio-abc'
import { Route as MarcasRouteImport } from './pages/marcas'
import { Route as LoginRouteImport } from './pages/login'
import { Route as LancamentosDeEstoqueRouteImport } from './pages/lancamentos-de-estoque'
import { Route as GerenciadorDeProdutosRouteImport } from './pages/gerenciador-de-produtos'
import { Route as EnviosRouteImport } from './pages/envios'
import { Route as IndexRouteImport } from './pages/index'
import { Route as EnviosIndexRouteImport } from './pages/envios.index'
import { Route as EnviosNovoRouteImport } from './pages/envios.novo'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioDeVendasRoute = RelatorioDeVendasRouteImport.update({
  id: '/relatorio-de-vendas',
  path: '/relatorio-de-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioDeEstoqueRoute = RelatorioDeEstoqueRouteImport.update({
  id: '/relatorio-de-estoque',
  path: '/relatorio-de-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioAbcRoute = RelatorioAbcRouteImport.update({
  id: '/relatorio-abc',
  path: '/relatorio-abc',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosDeEstoqueRoute = LancamentosDeEstoqueRouteImport.update({
  id: '/lancamentos-de-estoque',
  path: '/lancamentos-de-estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciadorDeProdutosRoute = GerenciadorDeProdutosRouteImport.update({
  id: '/gerenciador-de-produtos',
  path: '/gerenciador-de-produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosIndexRoute = EnviosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnviosRoute,
} as any)
const EnviosNovoRoute = EnviosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => EnviosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/envios': typeof EnviosRouteWithChildren
  '/gerenciador-de-produtos': typeof GerenciadorDeProdutosRoute
  '/lancamentos-de-estoque': typeof LancamentosDeEstoqueRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/relatorio-abc': typeof RelatorioAbcRoute
  '/relatorio-de-estoque': typeof RelatorioDeEstoqueRoute
  '/relatorio-de-vendas': typeof RelatorioDeVendasRoute
  '/vendas': typeof VendasRoute
  '/envios/novo': typeof EnviosNovoRoute
  '/envios/': typeof EnviosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gerenciador-de-produtos': typeof GerenciadorDeProdutosRoute
  '/lancamentos-de-estoque': typeof LancamentosDeEstoqueRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/relatorio-abc': typeof RelatorioAbcRoute
  '/relatorio-de-estoque': typeof RelatorioDeEstoqueRoute
  '/relatorio-de-vendas': typeof RelatorioDeVendasRoute
  '/vendas': typeof VendasRoute
  '/envios/novo': typeof EnviosNovoRoute
  '/envios': typeof EnviosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/envios': typeof EnviosRouteWithChildren
  '/gerenciador-de-produtos': typeof GerenciadorDeProdutosRoute
  '/lancamentos-de-estoque': typeof LancamentosDeEstoqueRoute
  '/login': typeof LoginRoute
  '/marcas': typeof MarcasRoute
  '/relatorio-abc': typeof RelatorioAbcRoute
  '/relatorio-de-estoque': typeof RelatorioDeEstoqueRoute
  '/relatorio-de-vendas': typeof RelatorioDeVendasRoute
  '/vendas': typeof VendasRoute
  '/envios/novo': typeof EnviosNovoRoute
  '/envios/': typeof EnviosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/envios'
    | '/gerenciador-de-produtos'
    | '/lancamentos-de-estoque'
    | '/login'
    | '/marcas'
    | '/relatorio-abc'
    | '/relatorio-de-estoque'
    | '/relatorio-de-vendas'
    | '/vendas'
    | '/envios/novo'
    | '/envios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gerenciador-de-produtos'
    | '/lancamentos-de-estoque'
    | '/login'
    | '/marcas'
    | '/relatorio-abc'
    | '/relatorio-de-estoque'
    | '/relatorio-de-vendas'
    | '/vendas'
    | '/envios/novo'
    | '/envios'
  id:
    | '__root__'
    | '/'
    | '/envios'
    | '/gerenciador-de-produtos'
    | '/lancamentos-de-estoque'
    | '/login'
    | '/marcas'
    | '/relatorio-abc'
    | '/relatorio-de-estoque'
    | '/relatorio-de-vendas'
    | '/vendas'
    | '/envios/novo'
    | '/envios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnviosRoute: typeof EnviosRouteWithChildren
  GerenciadorDeProdutosRoute: typeof GerenciadorDeProdutosRoute
  LancamentosDeEstoqueRoute: typeof LancamentosDeEstoqueRoute
  LoginRoute: typeof LoginRoute
  MarcasRoute: typeof MarcasRoute
  RelatorioAbcRoute: typeof RelatorioAbcRoute
  RelatorioDeEstoqueRoute: typeof RelatorioDeEstoqueRoute
  RelatorioDeVendasRoute: typeof RelatorioDeVendasRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-de-vendas': {
      id: '/relatorio-de-vendas'
      path: '/relatorio-de-vendas'
      fullPath: '/relatorio-de-vendas'
      preLoaderRoute: typeof RelatorioDeVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-de-estoque': {
      id: '/relatorio-de-estoque'
      path: '/relatorio-de-estoque'
      fullPath: '/relatorio-de-estoque'
      preLoaderRoute: typeof RelatorioDeEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio-abc': {
      id: '/relatorio-abc'
      path: '/relatorio-abc'
      fullPath: '/relatorio-abc'
      preLoaderRoute: typeof RelatorioAbcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos-de-estoque': {
      id: '/lancamentos-de-estoque'
      path: '/lancamentos-de-estoque'
      fullPath: '/lancamentos-de-estoque'
      preLoaderRoute: typeof LancamentosDeEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciador-de-produtos': {
      id: '/gerenciador-de-produtos'
      path: '/gerenciador-de-produtos'
      fullPath: '/gerenciador-de-produtos'
      preLoaderRoute: typeof GerenciadorDeProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios/': {
      id: '/envios/'
      path: '/'
      fullPath: '/envios/'
      preLoaderRoute: typeof EnviosIndexRouteImport
      parentRoute: typeof EnviosRoute
    }
    '/envios/novo': {
      id: '/envios/novo'
      path: '/novo'
      fullPath: '/envios/novo'
      preLoaderRoute: typeof EnviosNovoRouteImport
      parentRoute: typeof EnviosRoute
    }
  }
}

interface EnviosRouteChildren {
  EnviosNovoRoute: typeof EnviosNovoRoute
  EnviosIndexRoute: typeof EnviosIndexRoute
}

const EnviosRouteChildren: EnviosRouteChildren = {
  EnviosNovoRoute: EnviosNovoRoute,
  EnviosIndexRoute: EnviosIndexRoute,
}

const EnviosRouteWithChildren =
  EnviosRoute._addFileChildren(EnviosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnviosRoute: EnviosRouteWithChildren,
  GerenciadorDeProdutosRoute: GerenciadorDeProdutosRoute,
  LancamentosDeEstoqueRoute: LancamentosDeEstoqueRoute,
  LoginRoute: LoginRoute,
  MarcasRoute: MarcasRoute,
  RelatorioAbcRoute: RelatorioAbcRoute,
  RelatorioDeEstoqueRoute: RelatorioDeEstoqueRoute,
  RelatorioDeVendasRoute: RelatorioDeVendasRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
