/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetProductsQueryResponse,
  GetProductsQueryParams,
} from "../../types/productsController/GetProducts.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getProducts } from "../../clients/productsController/getProducts.ts";

export const getProductsQueryKey = (params?: GetProductsQueryParams) =>
  [{ url: "/products" }, ...(params ? [params] : [])] as const;

export type GetProductsQueryKey = ReturnType<typeof getProductsQueryKey>;

export function getProductsQueryOptions(
  params?: GetProductsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProductsQueryKey(params);
  return queryOptions<
    GetProductsQueryResponse,
    ResponseErrorConfig<Error>,
    GetProductsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProducts(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Lista todos os produtos com paginação
 * {@link /products}
 */
export function useGetProducts<
  TData = GetProductsQueryResponse,
  TQueryData = GetProductsQueryResponse,
  TQueryKey extends QueryKey = GetProductsQueryKey,
>(
  params?: GetProductsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProductsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getProductsQueryKey(params);

  const query = useQuery(
    {
      ...getProductsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
