/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetProductSalesDailyQueryResponse,
  GetProductSalesDailyPathParams,
} from "../../types/productsController/GetProductSalesDaily.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getProductSalesDaily } from "../../clients/productsController/getProductSalesDaily.ts";

export const getProductSalesDailySuspenseQueryKey = (
  id: GetProductSalesDailyPathParams["id"],
) => [{ url: "/products/:id/sales-daily", params: { id: id } }] as const;

export type GetProductSalesDailySuspenseQueryKey = ReturnType<
  typeof getProductSalesDailySuspenseQueryKey
>;

export function getProductSalesDailySuspenseQueryOptions(
  id: GetProductSalesDailyPathParams["id"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProductSalesDailySuspenseQueryKey(id);
  return queryOptions<
    GetProductSalesDailyQueryResponse,
    ResponseErrorConfig<Error>,
    GetProductSalesDailyQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProductSalesDaily(id, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna vendas diárias por loja e período para um produto
 * {@link /products/:id/sales-daily}
 */
export function useGetProductSalesDailySuspense<
  TData = GetProductSalesDailyQueryResponse,
  TQueryKey extends QueryKey = GetProductSalesDailySuspenseQueryKey,
>(
  id: GetProductSalesDailyPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProductSalesDailyQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getProductSalesDailySuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getProductSalesDailySuspenseQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
