/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type {
  GetProductsSalesVelocityQueryResponse,
  GetProductsSalesVelocityQueryParams,
} from '../../types/productsController/GetProductsSalesVelocity.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getProductsSalesVelocity } from '../../clients/productsController/getProductsSalesVelocity.ts'

export const getProductsSalesVelocityQueryKey = (
  params?: GetProductsSalesVelocityQueryParams
) => [{ url: '/products/sales-velocity' }, ...(params ? [params] : [])] as const

export type GetProductsSalesVelocityQueryKey = ReturnType<
  typeof getProductsSalesVelocityQueryKey
>

export function getProductsSalesVelocityQueryOptions(
  params?: GetProductsSalesVelocityQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getProductsSalesVelocityQueryKey(params)
  return queryOptions<
    GetProductsSalesVelocityQueryResponse,
    ResponseErrorConfig<Error>,
    GetProductsSalesVelocityQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProductsSalesVelocity(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Retorna unidades vendidas por produto nos últimos 15, 30, 60 e 90 dias
 * {@link /products/sales-velocity}
 */
export function useGetProductsSalesVelocity<
  TData = GetProductsSalesVelocityQueryResponse,
  TQueryData = GetProductsSalesVelocityQueryResponse,
  TQueryKey extends QueryKey = GetProductsSalesVelocityQueryKey,
>(
  params?: GetProductsSalesVelocityQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProductsSalesVelocityQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getProductsSalesVelocityQueryKey(params)

  const query = useQuery(
    {
      ...getProductsSalesVelocityQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
