/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type {
  GetProductsQueryResponse,
  GetProductsQueryParams,
} from '../../types/productsController/GetProducts.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getProducts } from '../../clients/productsController/getProducts.ts'

export const getProductsSuspenseQueryKey = (params?: GetProductsQueryParams) =>
  [{ url: '/products' }, ...(params ? [params] : [])] as const

export type GetProductsSuspenseQueryKey = ReturnType<
  typeof getProductsSuspenseQueryKey
>

export function getProductsSuspenseQueryOptions(
  params?: GetProductsQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getProductsSuspenseQueryKey(params)
  return queryOptions<
    GetProductsQueryResponse,
    ResponseErrorConfig<Error>,
    GetProductsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProducts(params, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Lista todos os produtos com paginação
 * {@link /products}
 */
export function useGetProductsSuspense<
  TData = GetProductsQueryResponse,
  TQueryKey extends QueryKey = GetProductsSuspenseQueryKey,
>(
  params?: GetProductsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProductsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    resolvedOptions?.queryKey ?? getProductsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getProductsSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
