/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type {
  GetProductSalesDailyQueryResponse,
  GetProductSalesDailyPathParams,
} from '../../types/productsController/GetProductSalesDaily.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getProductSalesDaily } from '../../clients/productsController/getProductSalesDaily.ts'

export const getProductSalesDailyQueryKey = (
  id: GetProductSalesDailyPathParams['id']
) => [{ url: '/products/:id/sales-daily', params: { id: id } }] as const

export type GetProductSalesDailyQueryKey = ReturnType<
  typeof getProductSalesDailyQueryKey
>

export function getProductSalesDailyQueryOptions(
  id: GetProductSalesDailyPathParams['id'],
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getProductSalesDailyQueryKey(id)
  return queryOptions<
    GetProductSalesDailyQueryResponse,
    ResponseErrorConfig<Error>,
    GetProductSalesDailyQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      return getProductSalesDaily(id, {
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * @description Retorna vendas diárias por loja e período para um produto
 * {@link /products/:id/sales-daily}
 */
export function useGetProductSalesDaily<
  TData = GetProductSalesDailyQueryResponse,
  TQueryData = GetProductSalesDailyQueryResponse,
  TQueryKey extends QueryKey = GetProductSalesDailyQueryKey,
>(
  id: GetProductSalesDailyPathParams['id'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProductSalesDailyQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getProductSalesDailyQueryKey(id)

  const query = useQuery(
    {
      ...getProductSalesDailyQueryOptions(id, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
