/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetProductsSalesVelocityQueryResponse,
  GetProductsSalesVelocityQueryParams,
} from "../../types/productsController/GetProductsSalesVelocity.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getProductsSalesVelocity } from "../../clients/productsController/getProductsSalesVelocity.ts";

export const getProductsSalesVelocitySuspenseQueryKey = (
  params?: GetProductsSalesVelocityQueryParams,
) =>
  [{ url: "/products/sales-velocity" }, ...(params ? [params] : [])] as const;

export type GetProductsSalesVelocitySuspenseQueryKey = ReturnType<
  typeof getProductsSalesVelocitySuspenseQueryKey
>;

export function getProductsSalesVelocitySuspenseQueryOptions(
  params?: GetProductsSalesVelocityQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getProductsSalesVelocitySuspenseQueryKey(params);
  return queryOptions<
    GetProductsSalesVelocityQueryResponse,
    ResponseErrorConfig<Error>,
    GetProductsSalesVelocityQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getProductsSalesVelocity(params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Retorna unidades vendidas por produto nos últimos 15, 30, 60 e 90 dias
 * {@link /products/sales-velocity}
 */
export function useGetProductsSalesVelocitySuspense<
  TData = GetProductsSalesVelocityQueryResponse,
  TQueryKey extends QueryKey = GetProductsSalesVelocitySuspenseQueryKey,
>(
  params?: GetProductsSalesVelocityQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetProductsSalesVelocityQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getProductsSalesVelocitySuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getProductsSalesVelocitySuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
