/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PatchProductsIdMutationRequest,
  PatchProductsIdMutationResponse,
  PatchProductsIdPathParams,
  PatchProductsId404,
  PatchProductsId409,
} from '../../types/productsController/PatchProductsId.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { patchProductsId } from '../../clients/productsController/patchProductsId.ts'

export const patchProductsIdMutationKey = () =>
  [{ url: '/products/:id' }] as const

export type PatchProductsIdMutationKey = ReturnType<
  typeof patchProductsIdMutationKey
>

export function patchProductsIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchProductsIdMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = patchProductsIdMutationKey()
  return mutationOptions<
    PatchProductsIdMutationResponse,
    ResponseErrorConfig<PatchProductsId404 | PatchProductsId409>,
    {
      id: PatchProductsIdPathParams['id']
      data: PatchProductsIdMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchProductsId(id, data, config)
    },
  })
}

/**
 * @description Atualiza dados de um produto
 * {@link /products/:id}
 */
export function usePatchProductsId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchProductsIdMutationResponse,
      ResponseErrorConfig<PatchProductsId404 | PatchProductsId409>,
      {
        id: PatchProductsIdPathParams['id']
        data: PatchProductsIdMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PatchProductsIdMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? patchProductsIdMutationKey()

  const baseOptions = patchProductsIdMutationOptions(
    config
  ) as UseMutationOptions<
    PatchProductsIdMutationResponse,
    ResponseErrorConfig<PatchProductsId404 | PatchProductsId409>,
    {
      id: PatchProductsIdPathParams['id']
      data: PatchProductsIdMutationRequest
    },
    TContext
  >

  return useMutation<
    PatchProductsIdMutationResponse,
    ResponseErrorConfig<PatchProductsId404 | PatchProductsId409>,
    {
      id: PatchProductsIdPathParams['id']
      data: PatchProductsIdMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PatchProductsIdMutationResponse,
    ResponseErrorConfig<PatchProductsId404 | PatchProductsId409>,
    {
      id: PatchProductsIdPathParams['id']
      data: PatchProductsIdMutationRequest
    },
    TContext
  >
}
