/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PostProductsMutationRequest,
  PostProductsMutationResponse,
  PostProducts404,
  PostProducts409,
} from '../../types/productsController/PostProducts.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { postProducts } from '../../clients/productsController/postProducts.ts'

export const postProductsMutationKey = () => [{ url: '/products' }] as const

export type PostProductsMutationKey = ReturnType<typeof postProductsMutationKey>

export function postProductsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostProductsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postProductsMutationKey()
  return mutationOptions<
    PostProductsMutationResponse,
    ResponseErrorConfig<PostProducts404 | PostProducts409>,
    { data: PostProductsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postProducts(data, config)
    },
  })
}

/**
 * @description Cria um produto
 * {@link /products}
 */
export function usePostProducts<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostProductsMutationResponse,
      ResponseErrorConfig<PostProducts404 | PostProducts409>,
      { data: PostProductsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostProductsMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postProductsMutationKey()

  const baseOptions = postProductsMutationOptions(config) as UseMutationOptions<
    PostProductsMutationResponse,
    ResponseErrorConfig<PostProducts404 | PostProducts409>,
    { data: PostProductsMutationRequest },
    TContext
  >

  return useMutation<
    PostProductsMutationResponse,
    ResponseErrorConfig<PostProducts404 | PostProducts409>,
    { data: PostProductsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostProductsMutationResponse,
    ResponseErrorConfig<PostProducts404 | PostProducts409>,
    { data: PostProductsMutationRequest },
    TContext
  >
}
