/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PatchProductsIdImageMutationRequest,
  PatchProductsIdImageMutationResponse,
  PatchProductsIdImagePathParams,
  PatchProductsIdImage404,
} from '../../types/productsController/PatchProductsIdImage.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { patchProductsIdImage } from '../../clients/productsController/patchProductsIdImage.ts'

export const patchProductsIdImageMutationKey = () =>
  [{ url: '/products/:id/image' }] as const

export type PatchProductsIdImageMutationKey = ReturnType<
  typeof patchProductsIdImageMutationKey
>

export function patchProductsIdImageMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchProductsIdImageMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = patchProductsIdImageMutationKey()
  return mutationOptions<
    PatchProductsIdImageMutationResponse,
    ResponseErrorConfig<PatchProductsIdImage404>,
    {
      id: PatchProductsIdImagePathParams['id']
      data: PatchProductsIdImageMutationRequest
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchProductsIdImage(id, data, config)
    },
  })
}

/**
 * @description Atualiza a URL da imagem de um produto
 * {@link /products/:id/image}
 */
export function usePatchProductsIdImage<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchProductsIdImageMutationResponse,
      ResponseErrorConfig<PatchProductsIdImage404>,
      {
        id: PatchProductsIdImagePathParams['id']
        data: PatchProductsIdImageMutationRequest
      },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PatchProductsIdImageMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? patchProductsIdImageMutationKey()

  const baseOptions = patchProductsIdImageMutationOptions(
    config
  ) as UseMutationOptions<
    PatchProductsIdImageMutationResponse,
    ResponseErrorConfig<PatchProductsIdImage404>,
    {
      id: PatchProductsIdImagePathParams['id']
      data: PatchProductsIdImageMutationRequest
    },
    TContext
  >

  return useMutation<
    PatchProductsIdImageMutationResponse,
    ResponseErrorConfig<PatchProductsIdImage404>,
    {
      id: PatchProductsIdImagePathParams['id']
      data: PatchProductsIdImageMutationRequest
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PatchProductsIdImageMutationResponse,
    ResponseErrorConfig<PatchProductsIdImage404>,
    {
      id: PatchProductsIdImagePathParams['id']
      data: PatchProductsIdImageMutationRequest
    },
    TContext
  >
}
