/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  DeleteBrandsIdMutationResponse,
  DeleteBrandsIdPathParams,
  DeleteBrandsId404,
  DeleteBrandsId409,
} from '../../types/brandsController/DeleteBrandsId.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { deleteBrandsId } from '../../clients/brandsController/deleteBrandsId.ts'

export const deleteBrandsIdMutationKey = () => [{ url: '/brands/:id' }] as const

export type DeleteBrandsIdMutationKey = ReturnType<
  typeof deleteBrandsIdMutationKey
>

export function deleteBrandsIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const mutationKey = deleteBrandsIdMutationKey()
  return mutationOptions<
    DeleteBrandsIdMutationResponse,
    ResponseErrorConfig<DeleteBrandsId404 | DeleteBrandsId409>,
    { id: DeleteBrandsIdPathParams['id'] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteBrandsId(id, config)
    },
  })
}

/**
 * @description Exclui uma marca
 * {@link /brands/:id}
 */
export function useDeleteBrandsId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteBrandsIdMutationResponse,
      ResponseErrorConfig<DeleteBrandsId404 | DeleteBrandsId409>,
      { id: DeleteBrandsIdPathParams['id'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteBrandsIdMutationKey()

  const baseOptions = deleteBrandsIdMutationOptions(
    config
  ) as UseMutationOptions<
    DeleteBrandsIdMutationResponse,
    ResponseErrorConfig<DeleteBrandsId404 | DeleteBrandsId409>,
    { id: DeleteBrandsIdPathParams['id'] },
    TContext
  >

  return useMutation<
    DeleteBrandsIdMutationResponse,
    ResponseErrorConfig<DeleteBrandsId404 | DeleteBrandsId409>,
    { id: DeleteBrandsIdPathParams['id'] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    DeleteBrandsIdMutationResponse,
    ResponseErrorConfig<DeleteBrandsId404 | DeleteBrandsId409>,
    { id: DeleteBrandsIdPathParams['id'] },
    TContext
  >
}
