/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type { GetBrandsQueryResponse } from '../../types/brandsController/GetBrands.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getBrands } from '../../clients/brandsController/getBrands.ts'

export const getBrandsSuspenseQueryKey = () => [{ url: '/brands' }] as const

export type GetBrandsSuspenseQueryKey = ReturnType<
  typeof getBrandsSuspenseQueryKey
>

export function getBrandsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getBrandsSuspenseQueryKey()
  return queryOptions<
    GetBrandsQueryResponse,
    ResponseErrorConfig<Error>,
    GetBrandsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getBrands({ ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Lista todas as marcas
 * {@link /brands}
 */
export function useGetBrandsSuspense<
  TData = GetBrandsQueryResponse,
  TQueryKey extends QueryKey = GetBrandsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetBrandsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getBrandsSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getBrandsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
