/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type { GetBrandsQueryResponse } from "../../types/brandsController/GetBrands.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getBrands } from "../../clients/brandsController/getBrands.ts";

export const getBrandsQueryKey = () => [{ url: "/brands" }] as const;

export type GetBrandsQueryKey = ReturnType<typeof getBrandsQueryKey>;

export function getBrandsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getBrandsQueryKey();
  return queryOptions<
    GetBrandsQueryResponse,
    ResponseErrorConfig<Error>,
    GetBrandsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getBrands({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Lista todas as marcas
 * {@link /brands}
 */
export function useGetBrands<
  TData = GetBrandsQueryResponse,
  TQueryData = GetBrandsQueryResponse,
  TQueryKey extends QueryKey = GetBrandsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetBrandsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getBrandsQueryKey();

  const query = useQuery(
    {
      ...getBrandsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
