/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PostBrandsMutationRequest,
  PostBrandsMutationResponse,
  PostBrands409,
} from '../../types/brandsController/PostBrands.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { postBrands } from '../../clients/brandsController/postBrands.ts'

export const postBrandsMutationKey = () => [{ url: '/brands' }] as const

export type PostBrandsMutationKey = ReturnType<typeof postBrandsMutationKey>

export function postBrandsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostBrandsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postBrandsMutationKey()
  return mutationOptions<
    PostBrandsMutationResponse,
    ResponseErrorConfig<PostBrands409>,
    { data: PostBrandsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postBrands(data, config)
    },
  })
}

/**
 * @description Cria uma marca
 * {@link /brands}
 */
export function usePostBrands<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostBrandsMutationResponse,
      ResponseErrorConfig<PostBrands409>,
      { data: PostBrandsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostBrandsMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postBrandsMutationKey()

  const baseOptions = postBrandsMutationOptions(config) as UseMutationOptions<
    PostBrandsMutationResponse,
    ResponseErrorConfig<PostBrands409>,
    { data: PostBrandsMutationRequest },
    TContext
  >

  return useMutation<
    PostBrandsMutationResponse,
    ResponseErrorConfig<PostBrands409>,
    { data: PostBrandsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostBrandsMutationResponse,
    ResponseErrorConfig<PostBrands409>,
    { data: PostBrandsMutationRequest },
    TContext
  >
}
