/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PatchBrandsIdMutationRequest,
  PatchBrandsIdMutationResponse,
  PatchBrandsIdPathParams,
  PatchBrandsId404,
  PatchBrandsId409,
} from "../../types/brandsController/PatchBrandsId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { patchBrandsId } from "../../clients/brandsController/patchBrandsId.ts";

export const patchBrandsIdMutationKey = () => [{ url: "/brands/:id" }] as const;

export type PatchBrandsIdMutationKey = ReturnType<
  typeof patchBrandsIdMutationKey
>;

export function patchBrandsIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchBrandsIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = patchBrandsIdMutationKey();
  return mutationOptions<
    PatchBrandsIdMutationResponse,
    ResponseErrorConfig<PatchBrandsId404 | PatchBrandsId409>,
    { id: PatchBrandsIdPathParams["id"]; data: PatchBrandsIdMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchBrandsId(id, data, config);
    },
  });
}

/**
 * @description Atualiza uma marca
 * {@link /brands/:id}
 */
export function usePatchBrandsId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchBrandsIdMutationResponse,
      ResponseErrorConfig<PatchBrandsId404 | PatchBrandsId409>,
      { id: PatchBrandsIdPathParams["id"]; data: PatchBrandsIdMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchBrandsIdMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? patchBrandsIdMutationKey();

  const baseOptions = patchBrandsIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchBrandsIdMutationResponse,
    ResponseErrorConfig<PatchBrandsId404 | PatchBrandsId409>,
    { id: PatchBrandsIdPathParams["id"]; data: PatchBrandsIdMutationRequest },
    TContext
  >;

  return useMutation<
    PatchBrandsIdMutationResponse,
    ResponseErrorConfig<PatchBrandsId404 | PatchBrandsId409>,
    { id: PatchBrandsIdPathParams["id"]; data: PatchBrandsIdMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchBrandsIdMutationResponse,
    ResponseErrorConfig<PatchBrandsId404 | PatchBrandsId409>,
    { id: PatchBrandsIdPathParams["id"]; data: PatchBrandsIdMutationRequest },
    TContext
  >;
}
