/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/kubb-axios-client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/kubb-axios-client";
import type {
  PostFbaAnalyzeMutationRequest,
  PostFbaAnalyzeMutationResponse,
  PostFbaAnalyze400,
} from "../../types/fbaController/PostFbaAnalyze.ts";

function getPostFbaAnalyzeUrl() {
  const res = { method: "POST", url: `/fba/analyze` as const };
  return res;
}

/**
 * @description Analisa um CSV de 90 dias para recomendacao de envio ao Amazon FBA
 * {@link /fba/analyze}
 */
export async function postFbaAnalyze(
  data: PostFbaAnalyzeMutationRequest,
  config: Partial<RequestConfig<PostFbaAnalyzeMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostFbaAnalyzeMutationResponse,
    ResponseErrorConfig<PostFbaAnalyze400>,
    PostFbaAnalyzeMutationRequest
  >({
    method: "POST",
    url: getPostFbaAnalyzeUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
