/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  DeleteShipmentAccountsByIdMutationResponse,
  DeleteShipmentAccountsByIdPathParams,
  DeleteShipmentAccountsById404,
} from "../../types/shipmentAccountsController/DeleteShipmentAccountsById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteShipmentAccountsById } from "../../clients/shipmentAccountsController/deleteShipmentAccountsById.ts";

export const deleteShipmentAccountsByIdMutationKey = () =>
  [{ url: "/shipment-accounts/:id" }] as const;

export type DeleteShipmentAccountsByIdMutationKey = ReturnType<
  typeof deleteShipmentAccountsByIdMutationKey
>;

export function deleteShipmentAccountsByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const mutationKey = deleteShipmentAccountsByIdMutationKey();
  return mutationOptions<
    DeleteShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentAccountsById404>,
    { id: DeleteShipmentAccountsByIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteShipmentAccountsById(id, config);
    },
  });
}

/**
 * {@link /shipment-accounts/:id}
 */
export function useDeleteShipmentAccountsById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteShipmentAccountsByIdMutationResponse,
      ResponseErrorConfig<DeleteShipmentAccountsById404>,
      { id: DeleteShipmentAccountsByIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteShipmentAccountsByIdMutationKey();

  const baseOptions = deleteShipmentAccountsByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentAccountsById404>,
    { id: DeleteShipmentAccountsByIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentAccountsById404>,
    { id: DeleteShipmentAccountsByIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<DeleteShipmentAccountsById404>,
    { id: DeleteShipmentAccountsByIdPathParams["id"] },
    TContext
  >;
}
