/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type { GetShipmentAccountsQueryResponse } from "../../types/shipmentAccountsController/GetShipmentAccounts.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getShipmentAccounts } from "../../clients/shipmentAccountsController/getShipmentAccounts.ts";

export const getShipmentAccountsSuspenseQueryKey = () =>
  [{ url: "/shipment-accounts" }] as const;

export type GetShipmentAccountsSuspenseQueryKey = ReturnType<
  typeof getShipmentAccountsSuspenseQueryKey
>;

export function getShipmentAccountsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getShipmentAccountsSuspenseQueryKey();
  return queryOptions<
    GetShipmentAccountsQueryResponse,
    ResponseErrorConfig<Error>,
    GetShipmentAccountsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getShipmentAccounts({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /shipment-accounts}
 */
export function useGetShipmentAccountsSuspense<
  TData = GetShipmentAccountsQueryResponse,
  TQueryKey extends QueryKey = GetShipmentAccountsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetShipmentAccountsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getShipmentAccountsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getShipmentAccountsSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
