/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type { GetShipmentAccountsQueryResponse } from '../../types/shipmentAccountsController/GetShipmentAccounts.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { getShipmentAccounts } from '../../clients/shipmentAccountsController/getShipmentAccounts.ts'

export const getShipmentAccountsQueryKey = () =>
  [{ url: '/shipment-accounts' }] as const

export type GetShipmentAccountsQueryKey = ReturnType<
  typeof getShipmentAccountsQueryKey
>

export function getShipmentAccountsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getShipmentAccountsQueryKey()
  return queryOptions<
    GetShipmentAccountsQueryResponse,
    ResponseErrorConfig<Error>,
    GetShipmentAccountsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getShipmentAccounts({
        ...config,
        signal: config.signal ?? signal,
      })
    },
  })
}

/**
 * {@link /shipment-accounts}
 */
export function useGetShipmentAccounts<
  TData = GetShipmentAccountsQueryResponse,
  TQueryData = GetShipmentAccountsQueryResponse,
  TQueryKey extends QueryKey = GetShipmentAccountsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetShipmentAccountsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getShipmentAccountsQueryKey()

  const query = useQuery(
    {
      ...getShipmentAccountsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
