/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  PutShipmentAccountsByIdMutationRequest,
  PutShipmentAccountsByIdMutationResponse,
  PutShipmentAccountsByIdPathParams,
  PutShipmentAccountsById404,
  PutShipmentAccountsById409,
} from "../../types/shipmentAccountsController/PutShipmentAccountsById.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { putShipmentAccountsById } from "../../clients/shipmentAccountsController/putShipmentAccountsById.ts";

export const putShipmentAccountsByIdMutationKey = () =>
  [{ url: "/shipment-accounts/:id" }] as const;

export type PutShipmentAccountsByIdMutationKey = ReturnType<
  typeof putShipmentAccountsByIdMutationKey
>;

export function putShipmentAccountsByIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PutShipmentAccountsByIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = putShipmentAccountsByIdMutationKey();
  return mutationOptions<
    PutShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<
      PutShipmentAccountsById404 | PutShipmentAccountsById409
    >,
    {
      id: PutShipmentAccountsByIdPathParams["id"];
      data: PutShipmentAccountsByIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return putShipmentAccountsById(id, data, config);
    },
  });
}

/**
 * {@link /shipment-accounts/:id}
 */
export function usePutShipmentAccountsById<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PutShipmentAccountsByIdMutationResponse,
      ResponseErrorConfig<
        PutShipmentAccountsById404 | PutShipmentAccountsById409
      >,
      {
        id: PutShipmentAccountsByIdPathParams["id"];
        data: PutShipmentAccountsByIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PutShipmentAccountsByIdMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? putShipmentAccountsByIdMutationKey();

  const baseOptions = putShipmentAccountsByIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PutShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<
      PutShipmentAccountsById404 | PutShipmentAccountsById409
    >,
    {
      id: PutShipmentAccountsByIdPathParams["id"];
      data: PutShipmentAccountsByIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PutShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<
      PutShipmentAccountsById404 | PutShipmentAccountsById409
    >,
    {
      id: PutShipmentAccountsByIdPathParams["id"];
      data: PutShipmentAccountsByIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PutShipmentAccountsByIdMutationResponse,
    ResponseErrorConfig<
      PutShipmentAccountsById404 | PutShipmentAccountsById409
    >,
    {
      id: PutShipmentAccountsByIdPathParams["id"];
      data: PutShipmentAccountsByIdMutationRequest;
    },
    TContext
  >;
}
