/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import type {
  PostShipmentAccountsMutationRequest,
  PostShipmentAccountsMutationResponse,
  PostShipmentAccounts409,
} from '../../types/shipmentAccountsController/PostShipmentAccounts.ts'
import { mutationOptions, useMutation } from '@tanstack/react-query'
import { postShipmentAccounts } from '../../clients/shipmentAccountsController/postShipmentAccounts.ts'

export const postShipmentAccountsMutationKey = () =>
  [{ url: '/shipment-accounts' }] as const

export type PostShipmentAccountsMutationKey = ReturnType<
  typeof postShipmentAccountsMutationKey
>

export function postShipmentAccountsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostShipmentAccountsMutationRequest>> & {
    client?: Client
  } = {}
) {
  const mutationKey = postShipmentAccountsMutationKey()
  return mutationOptions<
    PostShipmentAccountsMutationResponse,
    ResponseErrorConfig<PostShipmentAccounts409>,
    { data: PostShipmentAccountsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postShipmentAccounts(data, config)
    },
  })
}

/**
 * {@link /shipment-accounts}
 */
export function usePostShipmentAccounts<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostShipmentAccountsMutationResponse,
      ResponseErrorConfig<PostShipmentAccounts409>,
      { data: PostShipmentAccountsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostShipmentAccountsMutationRequest>> & {
      client?: Client
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postShipmentAccountsMutationKey()

  const baseOptions = postShipmentAccountsMutationOptions(
    config
  ) as UseMutationOptions<
    PostShipmentAccountsMutationResponse,
    ResponseErrorConfig<PostShipmentAccounts409>,
    { data: PostShipmentAccountsMutationRequest },
    TContext
  >

  return useMutation<
    PostShipmentAccountsMutationResponse,
    ResponseErrorConfig<PostShipmentAccounts409>,
    { data: PostShipmentAccountsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    PostShipmentAccountsMutationResponse,
    ResponseErrorConfig<PostShipmentAccounts409>,
    { data: PostShipmentAccountsMutationRequest },
    TContext
  >
}
