/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { DeleteSalesIdMutationResponse, DeleteSalesIdPathParams, DeleteSalesId404 } from "../../types/salesController/DeleteSalesId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { deleteSalesId } from "../../clients/salesController/deleteSalesId.ts";

export const deleteSalesIdMutationKey = () => [{ url: '/sales/:id' }] as const

export type DeleteSalesIdMutationKey = ReturnType<typeof deleteSalesIdMutationKey>

export function deleteSalesIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {

        const mutationKey = deleteSalesIdMutationKey()
        return mutationOptions<DeleteSalesIdMutationResponse, ResponseErrorConfig<DeleteSalesId404>, {id: DeleteSalesIdPathParams["id"]}, TContext>({
          mutationKey,
          mutationFn: async({ id }) => {
            return deleteSalesId(id, config)
          },
        })

}

/**
 * @description Exclui uma venda e devolve estoque
 * {@link /sales/:id}
 */
export function useDeleteSalesId<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteSalesIdMutationResponse, ResponseErrorConfig<DeleteSalesId404>, {id: DeleteSalesIdPathParams["id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? deleteSalesIdMutationKey()

          const baseOptions = deleteSalesIdMutationOptions(config) as UseMutationOptions<DeleteSalesIdMutationResponse, ResponseErrorConfig<DeleteSalesId404>, {id: DeleteSalesIdPathParams["id"]}, TContext>
          

          return useMutation<DeleteSalesIdMutationResponse, ResponseErrorConfig<DeleteSalesId404>, {id: DeleteSalesIdPathParams["id"]}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<DeleteSalesIdMutationResponse, ResponseErrorConfig<DeleteSalesId404>, {id: DeleteSalesIdPathParams["id"]}, TContext>
      
}