/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetSalesQueryResponse,
  GetSalesQueryParams,
} from "../../types/salesController/GetSales.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getSales } from "../../clients/salesController/getSales.ts";

export const getSalesQueryKey = (params?: GetSalesQueryParams) =>
  [{ url: "/sales" }, ...(params ? [params] : [])] as const;

export type GetSalesQueryKey = ReturnType<typeof getSalesQueryKey>;

export function getSalesQueryOptions(
  params?: GetSalesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getSalesQueryKey(params);
  return queryOptions<
    GetSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getSales(params, { ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Lista vendas com filtros por período
 * {@link /sales}
 */
export function useGetSales<
  TData = GetSalesQueryResponse,
  TQueryData = GetSalesQueryResponse,
  TQueryKey extends QueryKey = GetSalesQueryKey,
>(
  params?: GetSalesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getSalesQueryKey(params);

  const query = useQuery(
    {
      ...getSalesQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
