/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type {
  GetSalesQueryResponse,
  GetSalesQueryParams,
} from '../../types/salesController/GetSales.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'
import { getSales } from '../../clients/salesController/getSales.ts'

export const getSalesSuspenseQueryKey = (params?: GetSalesQueryParams) =>
  [{ url: '/sales' }, ...(params ? [params] : [])] as const

export type GetSalesSuspenseQueryKey = ReturnType<
  typeof getSalesSuspenseQueryKey
>

export function getSalesSuspenseQueryOptions(
  params?: GetSalesQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {}
) {
  const queryKey = getSalesSuspenseQueryKey(params)
  return queryOptions<
    GetSalesQueryResponse,
    ResponseErrorConfig<Error>,
    GetSalesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getSales(params, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * @description Lista vendas com filtros por período
 * {@link /sales}
 */
export function useGetSalesSuspense<
  TData = GetSalesQueryResponse,
  TQueryKey extends QueryKey = GetSalesSuspenseQueryKey,
>(
  params?: GetSalesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetSalesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? getSalesSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getSalesSuspenseQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
