/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PostSalesMutationRequest, PostSalesMutationResponse, PostSales400, PostSales404 } from "../../types/salesController/PostSales.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { postSales } from "../../clients/salesController/postSales.ts";

export const postSalesMutationKey = () => [{ url: '/sales' }] as const

export type PostSalesMutationKey = ReturnType<typeof postSalesMutationKey>

export function postSalesMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PostSalesMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = postSalesMutationKey()
        return mutationOptions<PostSalesMutationResponse, ResponseErrorConfig<PostSales400 | PostSales404>, {data: PostSalesMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return postSales(data, config)
          },
        })

}

/**
 * @description Cria uma venda com baixa automática no estoque
 * {@link /sales}
 */
export function usePostSales<TContext>(options: 
{
  mutation?: UseMutationOptions<PostSalesMutationResponse, ResponseErrorConfig<PostSales400 | PostSales404>, {data: PostSalesMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PostSalesMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? postSalesMutationKey()

          const baseOptions = postSalesMutationOptions(config) as UseMutationOptions<PostSalesMutationResponse, ResponseErrorConfig<PostSales400 | PostSales404>, {data: PostSalesMutationRequest}, TContext>
          

          return useMutation<PostSalesMutationResponse, ResponseErrorConfig<PostSales400 | PostSales404>, {data: PostSalesMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PostSalesMutationResponse, ResponseErrorConfig<PostSales400 | PostSales404>, {data: PostSalesMutationRequest}, TContext>
      
}