/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import type { PatchSalesIdMutationRequest, PatchSalesIdMutationResponse, PatchSalesIdPathParams, PatchSalesId400, PatchSalesId404 } from "../../types/salesController/PatchSalesId.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";
import { patchSalesId } from "../../clients/salesController/patchSalesId.ts";

export const patchSalesIdMutationKey = () => [{ url: '/sales/:id' }] as const

export type PatchSalesIdMutationKey = ReturnType<typeof patchSalesIdMutationKey>

export function patchSalesIdMutationOptions<TContext = unknown>(config: Partial<RequestConfig<PatchSalesIdMutationRequest>> & { client?: Client } = {}) {

        const mutationKey = patchSalesIdMutationKey()
        return mutationOptions<PatchSalesIdMutationResponse, ResponseErrorConfig<PatchSalesId400 | PatchSalesId404>, {id: PatchSalesIdPathParams["id"], data: PatchSalesIdMutationRequest}, TContext>({
          mutationKey,
          mutationFn: async({ id, data }) => {
            return patchSalesId(id, data, config)
          },
        })

}

/**
 * @description Atualiza uma venda e ajusta estoque
 * {@link /sales/:id}
 */
export function usePatchSalesId<TContext>(options: 
{
  mutation?: UseMutationOptions<PatchSalesIdMutationResponse, ResponseErrorConfig<PatchSalesId400 | PatchSalesId404>, {id: PatchSalesIdPathParams["id"], data: PatchSalesIdMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PatchSalesIdMutationRequest>> & { client?: Client },
}
 = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? patchSalesIdMutationKey()

          const baseOptions = patchSalesIdMutationOptions(config) as UseMutationOptions<PatchSalesIdMutationResponse, ResponseErrorConfig<PatchSalesId400 | PatchSalesId404>, {id: PatchSalesIdPathParams["id"], data: PatchSalesIdMutationRequest}, TContext>
          

          return useMutation<PatchSalesIdMutationResponse, ResponseErrorConfig<PatchSalesId400 | PatchSalesId404>, {id: PatchSalesIdPathParams["id"], data: PatchSalesIdMutationRequest}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<PatchSalesIdMutationResponse, ResponseErrorConfig<PatchSalesId400 | PatchSalesId404>, {id: PatchSalesIdPathParams["id"], data: PatchSalesIdMutationRequest}, TContext>
      
}